### ISSUE TITLE
Allow customisation of the Authenticating component [context]

### ISSUE THREAD

**Issue by citypaul** [AxaGuilDEv/react-oidc#147]
### Issue and Steps to Reproduce
[I came across this issue in the context package. If it is an issue in the Redux package though I think the same applies]

Firstly, thank you very much for this component. I had started the work to do something similar myself, then found this library and decided you had done most of the hard work for me, so thank you for that :-)

I have spotted one or two issues however. You allow for customisation of the `NotAuthenticated` and `NotAuthorized` components, but not the `Authenticating` component.

This results in a flash of French text for me when I'm trying to protect a route, which isn't what I would want in my application.

### Versions

1.1.5

### Screenshots

![image](https://user-images.githubusercontent.com/5850178/53289029-67ea5080-3788-11e9-95da-856294ae2b76.png)

#### Expected

Allow the consumer to override the Authenticating component via an `authenticating` prop on the `AuthenticationProvider`.

The example I looked at was for the context API, but I think this would need to be changed for all packages.

**Comment by citypaul** [comment]
I've created this issue just to log in and start a conversation, but I may have a go at doing this myself...

**Comment by guillaumechervetaxa** [comment]
It is already possible,
I am with my mobile phone so I will rigth a short answer. You can inject custom component at the beginning :
const propTypes = {
  notAuthentified: PropTypes.node, // react component displayed during authentication
  notAuthorized: PropTypes.node, // react component displayed in case user is not Authorised
  configuration: PropTypes.shape({

**Comment by guillaumechervetaxa** [comment]
Thank you very much for the issue! 
It is an important one to fix. 
Do you need the fix very quickly?

**Comment by citypaul** [comment]
I'm working on it now. I will have a PR for you in an hour or so :-)

**Comment by guillaumechervetaxa** [comment]
Thank you very much Paul.

**Comment by citypaul** [comment]
PR here: https://github.com/AxaGuilDEv/react-oidc/pull/150 :+1:

**Comment by guillaumechervetaxa** [comment]
Awesome! thank you, I will need to check it out on my computer tomorrow (I have just my phone for now), as soon as it is merged I can deploy a new version on npm if you need it.

**Comment by citypaul** [comment]
That would be fantastic @guillaumechervetaxa. As it happens, I'm working on a prototype on Monday that could really do with using this, so I'd very much appreciate it if you'd be able to merge and release. That would be brilliant.

I noticed one or two other fairly minor things, and some improvements that I think could be made to the docs, so I may continue raising issues and issuing pull requests next week if that sounds good to you!

Appreciate the fast feedback. Have a great weekend :+1: :100:

**Comment by guillaumechervetaxa** [comment]
Thank you very much @citypaul for your help! A new version is running to npm with your new feature! 
Thank you for your help and feel free to propose improvement! We will try to react as quickly as possible :)

**Comment by citypaul** [comment]
Thanks great @guillaumechervetaxa, thanks! :)

**Comment by citypaul** [comment]
Closing the issue, as this feature has been added in: https://github.com/AxaGuilDEv/react-oidc/pull/150

**Comment by citypaul** [comment]
Closing the issue, as this feature has been added in: https://github.com/AxaGuilDEv/react-oidc/pull/150

**Comment by this-fifo** [comment]
hey, thanks a lot for this incredibly helpful library, I'm having this exact same issue and the authenticating overriding is not working for me I still get the french default message, was this fix possibly lost after the big refactor?

my configuration is the following:
```jsx
<AuthenticationProvider
    isEnabled
    configuration={configuration}
    authenticating={() => (
        <Text>Authenticating, please wait ...</Text>
    )}
>
```

and then in my router

```jsx
<Route
    path="/users"
    component={withOidcSecure(ManageUsers)}
/>
```
