### ISSUE TITLE
[context] Authentication callback with IE

### ISSUE THREAD

**Issue by Sebo1000** [AxaGuilDEv/react-oidc#158]
### Issue and Steps to Reproduce

When using _IE 11_ to perform authentication.
Once the user has submitted the third-party login form with valid credentials, the browser redirects the user to a `/authentication/not-authenticated?message=No matching state found in storage` URL.
A message is displayed : _Authentification Vous n'êtes pas authentifié._

However, the access_token has been successfully retrieved as it is stored in the sessionStorage and added in API calls.
 
If the user types the requested URL, then the library works as expected.

### Versions

* oidc-client : **1.5.1**
* @axa-fr/react-oidc-context : **1.2.0**
* @axa-fr/react-oidc-context-fetch : **1.2.0**
* isomorphic-fetch : **2.2.1**
* es6-promise : **4.2.6**

### Screenshots

![2019-02-28_13h43_36](https://user-images.githubusercontent.com/4377523/53568447-51fed600-3b62-11e9-9338-e4457a87c485.png)

#### Expected
* The browser should redirect to the URL called before the authentication 
* A valid access_token should be present in the sessionStorage

#### Actual
* The browser redirect to `/authentication/not-authenticated?message=No matching state found in storage` and display _Vous n'êtes pas authentifié._
* A valid access_token is present in the sessionStorage
* The browser console display the following error message : `OidcClient.processSigninResponse: No matching state found in storage`

### Additional Details

- Workflow
> Access to a URL which need authentication

> Browser redirects the user to the SSO Login form

> User login with valid credentials 

> Brower redirects to `/authentication/callback` URL with params
> * scope
> * realm
> * state
> * access_token (valid access_token)
> * token_type
> * expires_in

> Browser redirects to `/authentication/not-authenticated?message=No matching state found in storage`

- OIDC configuration
```
 "oidc": {
    "client_id": "xxxx",
    "redirect_uri": "http://localhost:3000/authentication/callback",
    "response_type": "token",
    "post_logout_redirect_uri": "http://localhost:3000/",
    "scope": "openid profile email",
    "authority": "xxx",
    "silent_redirect_uri": "http://localhost:3000/authentication/silent_callback",
    "automaticSilentRenew": false,
    "loadUserInfo": false,
    "triggerAuthFlow": false
  }
```

**Comment by guillaumechervetaxa** [comment]
I'am on it Sebastien !

**Comment by guillaumechervetaxa** [comment]
Sébastien, how many time do you have to fix this issue? It is working with pure oidc in vannila js, I still have to test it on the demo of this package.

**Comment by Sebo1000** [comment]
The sooner, the better :smile: 
Update: We've got the same issue with Firefox (65.0)

**Comment by citypaul** [comment]
Hi guys,

Was this issue fixed in https://github.com/AxaGuilDEv/react-oidc/pull/168? If so can you please close this issue? I did notice this issue previously when I built a prototype using this library. I'm considering using this for the real thing and was about to raise this same issue with you. It would be awesome if this had already been fixed :) :+1:

**Comment by citypaul** [comment]
(Btw, this was occurring for me using Chrome, so definitely not browser specific)

**Comment by guillaumechervetaxa** [comment]
It should be fixed. By the last release. @Sebo100 do you confirm it is working now?

**Comment by Sebo1000** [comment]
@guillaumechervetaxa I've tried with the version _1.3.1-alpha.0_ and it does not work better

**Comment by citypaul** [comment]
Any update on this one? Would be great if this fix could go in soon...

**Comment by guillaumechervetaxa** [comment]
I will be back the 27 March, @Sebo1000 or @youf-olivier are you able to look at this bug?

**Comment by citypaul** [comment]
@Sebo1000 @youf-olivier is there any update on this?

**Comment by guillaumechervetaxa** [comment]
@Sebo1000 @youf-olivier are you working on this problem? May be not? Any news will be polite :p

**Comment by oyouf** [comment]
Sorry.

We are on It. But the problem seems to be more complex than you thought.

**Comment by oyouf** [comment]
I found the problem.

I Will fix it in the coming days.

**Comment by citypaul** [comment]
Hi @oyouf 

I just tried this fix out locally, and it does solve the issue in the URL. However, I am now seeing this component rendered every time:

![image](https://user-images.githubusercontent.com/5850178/55071795-7b3b5500-5081-11e9-82cb-95e099e2bb09.png)


Is there a way to not show the above component?

**Comment by youf-olivier** [comment]
Is the component block the flow (have you your application after that?) ? Or you just want to customize/hide this temporary loading component  ?

**Comment by citypaul** [comment]
Hi @youf-olivier 

The flow is not broken - I get back into the application as expected. I would just like to be able to customise or hide the temporary loading component. I know other components are possible to hide, but I couldn't see a mechanism for hiding this one.

I raised an issue for this here: https://github.com/AxaGuilDEv/react-oidc/issues/181

**Comment by youf-olivier** [comment]
Yes I saw It but I really wanted to be sure :)

**Comment by hamzahamidi** [comment]
#26

**Comment by hamzahamidi** [comment]
We're facing the same issue in IE 11.0.09. The browser is just stuck in not authenticated page

**Comment by RichardHpa** [comment]
Im still having this issue come up with I am trying to format my app to work on ie11
Has anyone found a solution to this?
