### ISSUE TITLE
Can't working with Hooks 

### ISSUE THREAD

**Issue by oyouf** [AxaGuilDEv/react-oidc#166]
If we use new React Hook on a package (Context in my case) we got an error message that say 

> hooks can only be called inside the body of a function component

I bump React in all packages but the problem stay.

I find an issue on react GH

https://github.com/facebook/react/issues/13991

**Comment by guillaumechervetaxa** [comment]
We may close this @oyouf?

**Comment by youf-olivier** [comment]
Yes, it will be closed with the hooks version
