### ISSUE TITLE
Allow customisation of the callback component

### ISSUE THREAD

**Issue by citypaul** [AxaGuilDEv/react-oidc#181]
### Issue and Steps to Reproduce

Thank you for this fix https://github.com/AxaGuilDEv/react-oidc/pull/180 against this issue https://github.com/AxaGuilDEv/react-oidc/issues/158.

This no longer routes towards an authenticated route, but I do get a flash of text that appears to be the callback component.

I could not see a way to customise this component, so it would be great to be able to do this.

### Versions

`v1.3.2-alpha.0`

### Screenshots
![image](https://user-images.githubusercontent.com/5850178/55073857-bab87000-5086-11e9-98cb-162cc4730585.png)

#### Expected

I'd expect to be able to override the React callback component via a prop, and see this render (or return `null` and render no text) instead.

#### Actual

See above screenshot for current actual behaviour.

### Additional Details

- Installed packages:

**Comment by youf-olivier** [comment]
Seems legit. We will study it.

**Comment by citypaul** [comment]
Thanks @youf-olivier. I did a PR that did something similar but just not for this component here: https://github.com/AxaGuilDEv/react-oidc/pull/150

That PR may be useful to you?

**Comment by youf-olivier** [comment]
Yes we will doing something similar. But for Callback, I think it could be just little more tricky, but very similar.

**Comment by guillaumechervetaxa** [comment]
Do you need it quickly ?
I think it is quite fast to do it. it is already done for some other displayed component.

**Comment by Madebymaurice** [comment]
Thanks for the quick response, yes it's a bit urgent, i'll try to submit a PR.

**Comment by guillaumechervetaxa** [comment]
It already done for some components (cf. screen bellow). I think we just need to make it for all components.

![image](https://user-images.githubusercontent.com/43414465/64762127-da145e00-d53d-11e9-98bb-65cc49b083d4.png)

**Comment by Madebymaurice** [comment]
Yes, I already use the props notAuthenticated and notAthorized, so i'll try to do the same for the callback component

**Comment by guillaumechervetaxa** [comment]
@Madebymaurice, do you have the time to make the PullRequest?

**Comment by Madebymaurice** [comment]
Yes i made it this morning, but forgot to update the doc so I did want to push, i'll do today.

**Comment by Android3000** [comment]
@guillaumechervetaxa @Madebymaurice 
When using these various overrides via AuthenticationProvider (like callbackComponentOverride, notAuthorized), I'm passing a custom component similar to the [example here](https://github.com/AxaGuilDEv/react-oidc/blob/master/examples/context/src/index.js).

When I do that, I get a bunch of PropType warnings in my console: 
```
Warning: Failed prop type: Invalid prop `callbackComponentOverride` supplied to `OidcRoutes`, expected a ReactNode.
    in OidcRoutes (created by AuthenticationProviderInt)
    in AuthenticationProviderInt (created by AuthenticationProvider)
    in AuthenticationProvider
```

The example does the same thing when run. Do you know if this PR cleans up the expected PropTypes to get rid of these warnings as well?

**Comment by youf-olivier** [comment]
The current PR will fix that 

https://github.com/AxaGuilDEv/react-oidc/pull/310/files

**Comment by youf-olivier** [comment]
https://github.com/AxaGuilDEv/react-oidc/pull/303
