### ISSUE TITLE
Default customisable components to render nothing [requires api change - thoughts?]

### ISSUE THREAD

**Issue by citypaul** [AxaGuilDEv/react-oidc#184]
Hey :-)

So I've got an initial setup that looks like this:

```jsx
  <AuthenticationProvider
    configuration={oidcConfiguration}
    loggerLevel={oidcLog.DEBUG}
    notAuthenticated={() => null}
    notAuthorized={() => null}
    authenticating={() => null}
  >
```

I'd also like to have a `null` component returned for the callback component, as outlinded in this issue: https://github.com/AxaGuilDEv/react-oidc/issues/181, but until that issue is resolved this is not yet possible.

While trying to test this on my consuming application, I am currently looking at mocking out the `<AuthenticationProvider>` at the unit test level, and having a mock for `withOidcSecure()` which proves this function is called when rendering protected routes.

I am planning to properly test the oidc logic using an integration test that uses something like 
[testcafe](https://devexpress.github.io/testcafe/). This will login to our identity provider and prove the logic works properly.

However, the unit tests have code coverage running on them, and the lines exposed by the above props that are returning `null` will be uncovered by the unit tests using this setup.

While thinking about this problem, I thought it might make sense to ask you to consider changing this api so that these components all render nothing unless explicitly passed in a React component. This behaviour would still allow for any custom component to be rendered, but would by default display nothing to the end user, it would just redirect them.

If you are happy to make this change (I appreciate this is a breaking API change so may require a major version release), I'd be happy to pick up this work and make the required changes myself. I don't want to do this if you don't agree with the idea though.

Can you please let me know what you think, and if you like this idea I'll have a go at this myself probably early next week (earliest I think I'd be able to do this would be next week).

Just to clarify what you'd end up with. If we made these changes, then this:

```jsx
  <AuthenticationProvider
    configuration={oidcConfiguration}
    loggerLevel={oidcLog.DEBUG}
  >
```

Would render no text to the user, but would handle the redirection and callback logic, eventually bouncing a user back into their application on successful login.

Whereas this:

```jsx
  <AuthenticationProvider
    configuration={oidcConfiguration}
    loggerLevel={oidcLog.DEBUG}
    notAuthenticated={() => <h1>Authenticated!</h1>}
    notAuthorized={() => <h1>Not Authorized!</h1>}
    authenticating={() => <h1>Authenticating</h1>}
    callback={() => <h1>Callback component</h1>}
  >
```
Would render the respective components.

As to whether the `callback` is part of this piece of work or not would depend on a discussion between ourselves.

Please let me know what you think!

**Comment by guillaumechervetaxa** [comment]
Hi @citypaul,

I am back :)
Thank you very much for this very rich Issue .

Big thanks to @youf-olivier for the previous bug fix (small warning about history, don't forget to squash your change in order to have a beautiful readme)

I'am for allowing null component to be set, but I don't know what to think about set null to every component by default. I would prefer no breaking change, because it will impact many internal project. I prefer a smouth solution.

May be a breaking change will be understand if we combinate it with beautifull custom auth component.
@samuel-gomez-axa, is it possible to think about setting up beautifull auth components in the toolkit ? https://github.com/AxaGuilDEv/react-toolkit

**Comment by citypaul** [comment]
@guillaumechervetaxa I do understand your reasoning for not wanting to make a breaking change. However, if the change is a major version number change, consumers of the application would be able to update in their own time, and the change is only a small one.

I'd argue the change makes sense because removing the text on these routes by default means that consumers of the library are able to take advantage of the authentication flows alone, and if they have the requirement to display text to the user they can choose to do so easily. It means that people can use your library and it still remains flexible to handle all the previous use cases.

It's your decision to make of course. But in my opinion this would be a nice change :-)

**Comment by guillaumechervetaxa** [comment]
Hi @citypaul,
I am agree with you, I think that displayed components should not be inside the library.instead, I think the demo should have these samples components in order to explain what it is possible to do! If you have the time, this change will be very cool!

**Comment by youf-olivier** [comment]
Hello you both.

I'm working hard on a new version with Hooks. I will introduce the customized component in the version.

The PR will come in few days.

**Comment by citypaul** [comment]
Sounds good @youf-olivier. Will look forward to seeing your version then in that case :)

**Comment by guillaumechervetaxa** [comment]
Hi @citypaul, now in version 3.x.x your are able to set up customize every callback Component as you want. 
Is it ok for you?

**Comment by citypaul** [comment]
Hey @guillaumechervetaxa, sounds cool! Nice work :) 🎉
