### ISSUE TITLE
[context] Issue with react-router 5.0.0

### ISSUE THREAD

**Issue by jeromegervais** [AxaGuilDEv/react-oidc#203]
### Issue and Steps to Reproduce

Im' using the react-oidc-context.
When migrating react-router from 4.3.1 to 5.0.0, I'm getting this error :
"Invariant Violation: You should not use <Route> or withRouter() outside a <Router>"

### Additional Details
I think it comes from the file AuthenticationContext.js : OidcRoutes are outside a <Router> component

**Comment by guillaumechervetaxa** [comment]
@youf-olivier , do you think upgrade to react router 5 will be possible after your migration to hooks ?
I think you are the best specialist on it ^^
