### ISSUE TITLE
Logout flow doesn't work as expected in protected routes

### ISSUE THREAD

**Issue by irsooti** [AxaGuilDEv/react-oidc#208]
### Logout flow doesn't work as expected in protected routes

As title suggests:

### Versions

Current repo.

### Screenshots
![2019-05-10_11-30-53](https://user-images.githubusercontent.com/7157155/57517629-90a9cd00-7317-11e9-995c-85c8a049749c.gif)

#### Expected

Should logout.

#### Actual

It works as expected in non-protected routes only (Home route)

**Comment by irsooti** [comment]
As workaround I wrapped the logout function in another function:

```js
import React from 'react';
import { AuthenticationConsumer } from '@axa-fr/react-oidc-context';
import { Link, withRouter } from 'react-router-dom';

const headerStyle = {
  display: 'flex',
  backgroundColor: '#26c6da',
  justifyContent: 'space-between',
  padding: 10
};

const linkStyle = {
  color: 'white',
  textDecoration: 'underline'
};

export default withRouter(props => {
  
  const handleLogout = (logoutFn) => () => {
    props.history.push('/');
    logoutFn()
  }

  return (
    <header>
      <AuthenticationConsumer>
        {props => {
          return (
            <div style={headerStyle}>
              <h3>
                <Link style={linkStyle} to="/">
                  HOME
                </Link>
              </h3>

              {props.oidcUser || !props.isEnabled ? (
                <ul>
                  <li>
                    <Link style={linkStyle} to="/dashboard">
                      Dashboard
                    </Link>
                  </li>
                  <li>
                    <Link style={linkStyle} to="/admin">
                      Admin
                    </Link>
                  </li>
                  <button onClick={handleLogout(props.logout)}>
                    logout
                  </button>
                </ul>
              ) : (
                <button onClick={props.login}>login</button>
              )}
            </div>
          );
        }}
      </AuthenticationConsumer>
    </header>
  );
});
```

**Comment by guillaumechervetaxa** [comment]
Thank you very much for the feedback @irsooti, 
it seems post_logout_redirect_uri are not working well. 
We are going to look at it as soon as @youf-olivier has finish its migration to hooks.

**Comment by youf-olivier** [comment]
There was a Bug in the order of logout execution, but I thougth i fixed it.

We will look at it.

**Comment by phuocnelet** [comment]
Hello, got some updates about it ? :)

**Comment by guillaume-chervet** [comment]
Is this bug still here in 3.0.0?

**Comment by youf-olivier** [comment]
I don't think so.

**Comment by guillaume-chervet** [comment]
May be the logout function may access an uri or a path in input or nothing seem to me a good solution. What do you think about it?

**Comment by youf-olivier** [comment]
The callback url is in the config file (post_logout_redirect_uri), but it could be nice to give it as a param, but generally you have just one post logout uri, right ?

**Comment by guillaume-chervet** [comment]
May be to use the config logout url seeme a good idea :p

May be add also the ability to override it dynamically can be nice.

**Comment by cheets** [comment]
I ran into same issue with 3.0.0-alpha.0 and fixed it by using the above solution. Attached a screenshot of the console errors I get when trying to log out from a protected page.
![logout-error](https://user-images.githubusercontent.com/289477/65682051-d5ce6180-e062-11e9-8ba6-5a33d7558164.png)

**Comment by youf-olivier** [comment]
Close with lasts PR.

https://github.com/AxaGuilDEv/react-oidc/pull/303
https://github.com/AxaGuilDEv/react-oidc/pull/253

**Comment by chmieludaniel** [comment]
I have the very same problem,  I'm using `3.0.9-alpha.0`. Currently using workaround, but if anyone has a good solution, I'd love to see one

**Comment by guillaumechervetaxa** [comment]
@Gparquet , Hi, I think we may be have the same on our  current application and it is ramdom !
