### ISSUE TITLE
Support code flow (with pkce)

### ISSUE THREAD

**Issue by guillaumechervetaxa** [AxaGuilDEv/react-oidc#284]
study and code the support for code flow (with pkce).

oidc client already support it.

https://github.com/IdentityModel/oidc-client-js/issues/552

**Comment by guillaumechervetaxa** [comment]
It is seem to be only response_type to be change to "code" and it works if ther oidc server support it ! =>  response_type: "code",

https://www.scottbrady91.com/Angular/Migrating-oidc-client-js-to-use-the-OpenID-Connect-Authorization-Code-Flow-and-PKCE

**Comment by youf-olivier** [comment]
It Works very well
