### ISSUE TITLE
Migrate to typescript

### ISSUE THREAD

**Issue by guillaume-chervet** [AxaGuilDEv/react-oidc#291]

**Comment by ghostd** [comment]
Hi,

How do you plan this migration? Maybe i could spend some spare time on this. Did you think about using something like [tsdx](https://github.com/jaredpalmer/tsdx) or [microbundle](https://github.com/developit/microbundle)? Do you prefer keeping the custom build?

**Comment by guillaumechervetaxa** [comment]
Hi,

The build system his already compatible with TypeScript like in https://github.com/AxaGuilDEv/react-toolkit/tree/master/packages we can migrate packages by packages.

It can be interresting to study alternatives ^^

**Comment by ghostd** [comment]
Hi,

How can i compile the project with typescript?
I tried:
* `npm run dev:ts`, for each package i get the log 'No tsconfig.json'
  * should i copy the `tsconfig.json` from the root into the package i want to migrate?
* `npm run prepare`, it returns and nothing seems built
* `npx lerna exec --scope=@axa-fr/react-oidc-redux -- node ../../scripts/watch-ts.js`, i get the log 'No tsconfig.json'

I'll update the docs when i'll find how to run the right command.

Regards

**Comment by guillaume-chervet** [comment]
It is the rigth message. Take a look to the toolkit.
https://github.com/AxaGuilDEv/react-toolkit/tree/master/packages/restitution
The build ts script is run only if tsconfig is found.

**Comment by DASPRiD** [comment]
Is there a way to already use this package with typescript? I couldn't find a @types package for the packages in this repository.

**Comment by ghostd** [comment]
Yes.

My project use create-react-app, so i added (partial) type definitions into `react-app-env.d.ts`. Here are the definitions i needed for my cases:
```typescript
/// <reference types="react-scripts" />

declare module '@axa-fr/react-oidc-context' {
  import * as React from 'react';
  import * as oidcClient from 'oidc-client';

  export class OidcSecure extends React.Component<{}, any> {}

  type AuthenticationProviderProps = {
    configuration: any;
    loggerLevel: LogLevel;
    UserStore?: any;
    callbackComponentOverride?: any;
  };
  export class AuthenticationProvider extends React.Component<AuthenticationProviderProps, any> {}

  type OidcLog = {
    NONE: 0;
    ERROR: 1;
    WARN: 2;
    INFO: 3;
    DEBUG: 4;
    debug: (message?: any, ...optionalParams: any[]) => void;
    info: (message?: any, ...optionalParams: any[]) => void;
    warn: (message?: any, ...optionalParams: any[]) => void;
    error: (message?: any, ...optionalParams: any[]) => void;
  };

  export const oidcLog: OidcLog;

  export const InMemoryWebStorage = oidcClient.InMemoryWebStorage;

  export function getUserManager(): oidcClient.UserManager;

  type AuthenticationCtx = {
    isLoading: boolean;
    oidcUser: oidcClient.User | null;
    error: string;
    authenticating: React.ReactNode;
    isEnabled: boolean;
    login: () => void;
    logout: () => void;
    events: oidcClient.UserManagerEvents;
  };
  export const AuthenticationContext: React.Context<AuthenticationCtx>;

  interface WithOidcUserProps {
    oidcUser: oidcClient.User | null;
  }
  export function withOidcUser<P extends WithOidcUserProps>(
    component: Component<P>
  ): React.ComponentClass<Omit<P, keyof WithOidcUserProps>>;
}
```

If you dont user create-react-app, create an [ambient module](https://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules) into your project

Regards

**Comment by DASPRiD** [comment]
Well yeah, I know about defining modules oneself. My question was more about already existing definitions, so I don't have to copy paste manual definitions all over my projects :)

**Comment by ghostd** [comment]
I started the migration, if someone has comments...: #410

**Comment by damien7792** [comment]
Thanks ghostd for the react-app-env.d.ts file, it's very useful.

I tried it in my typescript project and I get errors. 
First, I'm assuming `loggerLevel: LogLevel; ` should be replaced with `loggerLevel: OidcLog;` , right?

Also, I'm getting an error on `export const InMemoryWebStorage`, saying that: 
`A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.`
Did you get the same error?

Thanks
Damien

**Comment by ghostd** [comment]
Hi,

`loggerLevel` should be a number or union type of `0 | 1 | 2 | 3 | 4`

I don't have errors about the web storage (i'm using the version 3.8 of TS)

**Comment by youf-olivier** [comment]
I am on a refactoring of the context package, I saw the issue about the type of OidcLog, and I fixed it.

**Comment by damien7792** [comment]
Thanks, I eventually got it to work.

Olivier, are you planning on doing it also for the redux package? If so, where can I find the types definition?

Thanks for your hard work on this!
