### ISSUE TITLE
Getting AccessToken

### ISSUE THREAD

**Issue by mthota15** [AxaGuilDEv/react-oidc#298]
Thank you so much for nice plugin.

After authentication is done, How can i access AccessToken? I need to use in Non React Component like ApolloClient for authentication with API.

**Comment by guillaumechervetaxa** [comment]
Thank you for using it :)

acces_token is available inside the user data.

you can checkout the sample bellow with fetch :

https://github.com/AxaGuilDEv/react-oidc/blob/master/packages/context-fetch/src/withFetchToken.js
https://github.com/AxaGuilDEv/react-oidc/blob/master/packages/fetch-core/src/fetchToken.js

**Comment by guillaume-chervet** [comment]
@mthota15 did you succeed with the access token.
I am interresting to see sample of code with Apollo.

**Comment by youf-olivier** [comment]
Yes, a short sample could be nice to understand your problem.

You can get the token in the user prop in the context, then send it to your apollo client with props or function param. It exists two way to get token, useReactOidc or withOidcUser (and also directly the context API consumer)

With Apollo , can you put the Apollo provider under the AuthenticationProvider and then transmit the user to the client ? 

Let me know, and a short sample can help us to help you ;)

**Comment by mthota15** [comment]
@guillaume-chervet @youf-olivier yes i did succeed with the access token. I posted my question and answer on stackoverflow. please let take a look and see if there is a better way to implement it.

https://stackoverflow.com/questions/57931814/how-to-fetch-accesstoken/57931854#57931854

**Comment by youf-olivier** [comment]
For me it is a perfect way :)

Good job !

**Comment by bkershaw** [comment]
Does this still work in 2023?  access_token is hidden from the client by the service worker.  I can log the access_token from inside the service worker, but the access_token is not being passed to API when I perform REST operations via Axios or fetch.  I also tried using fetch from the useOidcFetch

**Comment by guillaume-chervet** [comment]
Hi @bkershaw , thank you for your issue.
Did you configure the file trustedDomains.js? You can also disable serviceworlker mode if you want.

**Comment by guillaume-chervet** [comment]
Hi @bkershaw , thank you for your issue.
Did you configure the file trustedDomains.js? You can also disable serviceworlker mode if you want. So accessToken will be bring back to tjz javascript client.

**Comment by bkershaw** [comment]
@guillaume-chervet ✅ Configured the trusted domains.  But I didn't add the downstream API to the list I will add it and give it another try.  I didn't know it was possible to disable the service worker.  Is that a config flag?

**Comment by guillaume-chervet** [comment]
hi @bkershaw , you can disable it like that:
```javascript
const configuration = {
  client_id: 'interactive.public.short',
  redirect_uri: window.location.origin + '/authentication/callback',
  silent_redirect_uri: window.location.origin + '/authentication/silent-callback', // Optional activate silent-signin that use cookies between OIDC server and client javascript to restore the session
  scope: 'openid profile email api offline_access',
  authority: 'https://demo.duendesoftware.com',
  //service_worker_relative_url:'/OidcServiceWorker.js',
  //service_worker_only:true,
};
```

**Comment by bkershaw** [comment]
I just realized the user's profile information, such as roles, is not provided in oidcUser.  Is that by design?
