### ISSUE TITLE
Catch action from context

### ISSUE THREAD

**Issue by Madebymaurice** [AxaGuilDEv/react-oidc#299]
### Issue and Steps to Reproduce
Hi,
Thanks for your great work, I use the context package for implementing in react-admin with Azure. It work pretty well, but for react-admin in need to catch actions from the context to do some necessary stuff.
How can I access to actions like ON_LOADING, ON_ERROR, ON_LOAD_USER, ON_LOADING (like we usually did with Redux) or do you some accessible events for do something on similar case ?
Thanks for your help

### Versions
"@axa-fr/react-oidc-context": "^3.0.0-alpha.0",
"oidc-client": "^1.9.1",
### Additional Details

- Installed packages:

**Comment by guillaumechervetaxa** [comment]
@youf-olivier ,
I think it can be interesting to set up this kind of informaiton inside context state.
The react-oidc-redux already have state information like user.isLoading, that is really useful.
What do you think about it?

**Comment by youf-olivier** [comment]
Yes of course. I didn't think about feature like that, but it can be interesting

**Comment by youf-olivier** [comment]
I will take this one soon.
