### ISSUE TITLE
Redirection to login page, even if user is not active, cause unexpected behaviour

### ISSUE THREAD

**Issue by jhujhul** [AxaGuilDEv/react-oidc#301]
### Issue and Steps to Reproduce
When a user logs in, after a long period of time (usually between 12h and 24h), he is redirected to a login page, even if he closed his computer session.
In the context of Axa France, I'm talking about this login page:
![Capture](https://user-images.githubusercontent.com/15234610/65162686-eadf3b00-da39-11e9-9db8-72fcf69b458c.PNG)

The issue occurs when he tries to login 10 minutes after the redirection, which happens often when his session is closed: because he took too much time to authenticate, he will be redirected to this page:
![expired](https://user-images.githubusercontent.com/15234610/65161260-8b802b80-da37-11e9-9b8c-8ff6cc67037f.PNG)

### Versions
Package: @axa-fr/react-oidc-redux
Version: 2.0.8

**Comment by youf-olivier** [comment]
I'm not sure that is a real issue, but I already had this case. I will check that in few days. 

Thanks to the repport.

**Comment by guillaume-chervet** [comment]
It is a good use case to add to the library.
I think the best solution is to add a new route with new component that advert we lose the session. Of course this component will be overridable and have by defailt a button for reconnect. We should not make it automaticaly in that case.
