### ISSUE TITLE
The new history.push seems not Working on IE

### ISSUE THREAD

**Issue by youf-olivier** [AxaGuilDEv/react-oidc#312]
The History.push is created by the package : 
![image](https://user-images.githubusercontent.com/40664502/66194777-7fca7100-e695-11e9-9845-d4f723b39017.png)
But the function doesn't work
![image](https://user-images.githubusercontent.com/40664502/66194806-953f9b00-e695-11e9-85dc-9f549c2b951f.png)

**Comment by youf-olivier** [comment]
IE 11

On my personnal laptop, the example doesnt work at all.

I'm working on It.

**Comment by guillaumechervetaxa** [comment]
![image](https://user-images.githubusercontent.com/43414465/66198305-67118980-e69c-11e9-9976-3f5650fe3a8e.png)

**Comment by Sebo1000** [comment]
@guillaumechervetaxa We had to add `require('isomorphic-fetch');` in our project to avoid this issue with react-oidc on IE

**Comment by youf-olivier** [comment]
i will put https://github.com/github/fetch on the exemples. It is the library recommended by the Mozilla documentation 

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Polyfill
