### ISSUE TITLE
[all] F5 always reauthenticate

### ISSUE THREAD

**Issue by guillaumechervetaxa** [AxaGuilDEv/react-oidc#317]
Bug fixed on version 2.X.X is back in 3.X.X

The correct version to take is
https://github.com/AxaGuilDEv/react-oidc/blob/65bc3a6e0375c1181401eadd8c049bb0710071a4/packages/redux/src/authenticate.js
 
I will fixe it on monday

**Comment by youf-olivier** [comment]
In the same case : when token is expired the silent signin is not launched.

**Comment by guillaumechervetaxa** [comment]
It is not the same case at all Olivier :p
