### ISSUE TITLE
Using callbackComponentOverride causes errors when logging in

### ISSUE THREAD

**Issue by cheets** [AxaGuilDEv/react-oidc#329]
### Issue and Steps to Reproduce

When using callbackComponentOverride there's something extra happening that causes errors in the console. The errors happen when you login, after further page loads they do not happen. These errors happen with dev and production builds. I used [React Profiler](https://reactjs.org/docs/profiler.html) to check what's happening with `AuthenticationProvider` and it seems it is doing two extra updates (re-renders) compared to using default callback component. I suspect there is a race condition and some code tries to check state before it's ready. 

I tried to follow code in `AuthenticationContext.container.js` from the line `const CallbackComponent = callbackComponentOverride
    ? withComponentOverrideProps(CallbackInt, callbackComponentOverride)
    : CallbackInt;` but I'm not completely sure which part triggers the re-renders.

Error happens with the code below and it goes away if I remove `callbackComponentOverride={CallbackComponent}`. I've tested with Chrome and Firefox as well.

```jsx
<AuthenticationProvider
        configuration={oidcConfiguration}
        logger={console}
        loggerLevel={oidcLog.DEBUG}
        isEnabled={true}
        callbackComponentOverride={CallbackComponent}
>
```

### Versions

react-oidc-context": "^3.0.2-alpha.0"

### Screenshots

With custom callback component two extra "update" phases (total of 5 events in `AuthenticationProvider`):

![with-custom-callback](https://user-images.githubusercontent.com/289477/68026089-3a5e8b00-fcb7-11e9-8c0c-4fbb4eae037f.png)

With default callback component (total of 3 events in `AuthenticationProvider`)

![without-custom-callback](https://user-images.githubusercontent.com/289477/68026095-3fbbd580-fcb7-11e9-81eb-9ae350a9851e.png)

#### Expected

No errors.

#### Actual

Errors:

```
OidcClient.readSigninResponseState: No matching state found in storage
ERROR [react-context-oidc] : There was an error handling the token callback: No matching state found in storage
OidcClient.readSigninResponseState: No state in response
ERROR [react-context-oidc] : There was an error handling the token callback: No state in response
```

### Additional Details

- Installed packages:

```json
    "@apollo/react-hooks": "^3.1.2",
    "@axa-fr/react-oidc-context": "^3.0.2-alpha.0",
    "@axa-fr/react-oidc-context-fetch": "^3.0.2-alpha.0",
    "apollo-boost": "^0.4.4",
    "graphql": "^14.5.8",
    "oidc-client": "^1.9.1",
    "prop-types": "^15.7.2",
    "pure-react-carousel": "^1.23.0",
    "react": "^16.10.2",
    "react-dom": "^16.10.2",
    "react-router-dom": "5.1.2",
    "react-scripts": "3.2.0",
    "styled-components": "^5.0.0-beta.9",
    "use-async-effect": "^2.2.1"
```

**Comment by youf-olivier** [comment]
This is because the default callback component is under a Memo Hook, but if you change the props  the memo hook reload the component. 

I can fix it with a memo.

Thanks :)
