### ISSUE TITLE
Set storage in Cookie

### ISSUE THREAD

**Issue by youf-olivier** [AxaGuilDEv/react-oidc#342]
https://medium.com/redteam/stealing-jwts-in-localstorage-via-xss-6048d91378a0

It could be necessary to let the user to choose between default storage (session storage in this case) and a Cookie storage.

**Comment by trickydisco78** [comment]
In the vanilla implementing it has the option of in memory storage

`Oidc.WebStorageStateStore({ store: new Oidc.InMemoryWebStorage() }),`

Can we have this option?

**Comment by youf-olivier** [comment]
I'm on it :).

**Comment by trickydisco78** [comment]
oh wow. thanks

**Comment by youf-olivier** [comment]
Actually, I work on it still yesterday. But I didnt notice that was a InMemoryWebStroage in the oidc package, so thanks to you

**Comment by youf-olivier** [comment]
Abandoned. We will work with memory (https://tools.ietf.org/html/rfc6819#section-5.1.6)
