### ISSUE TITLE
How to pass audience for authorize request

### ISSUE THREAD

**Issue by christopherfowers** [AxaGuilDEv/react-oidc#344]
The config object does not seem to support passing an audience for authorize requests. It is not uncommon for providers to require this for jwt based access tokens. Am I missing something in the docs or is this not really supported?

**Comment by christopherfowers** [comment]
ughhh I feel dumb. Found my answer on the oidc-client repo. For anyone else looking for this (or other params)

![image](https://user-images.githubusercontent.com/5230453/69077311-58d8bc00-0a03-11ea-95c0-b7fc61cda1ed.png)

**Comment by Florian-Guillot-Axa** [comment]
For react-oidc use `token_request_extras` like `token_request_extras: {audience: MY-AUDIENCE}`
