### ISSUE TITLE
Authorization code with PKCE

### ISSUE THREAD

**Issue by promontis** [AxaGuilDEv/react-oidc#346]
Auth0 provides in their blog some guidelines on the state of OAuth2 to invoke API from JavaScript in Single Page Applications (SPAs): https://auth0.com/blog/oauth2-implicit-grant-and-spa/

Basically it boils down to:
> If you are building a new SPA, you should consider implementing the new guidance based on authorization code with PKCE. More details below.

Have you guys given some thought on this?

**Comment by guillaumechervetaxa** [comment]
Yes it is already working !

https://github.com/AxaGuilDEv/react-oidc/issues/284
Checkout the sample oidc-context, It is working with a pkce configuration.

**Comment by promontis** [comment]
Ah yes, sorry, didn't see that one :) thnx!
