### ISSUE TITLE
Can't get working with Gatsby

### ISSUE THREAD

**Issue by trickydisco78** [AxaGuilDEv/react-oidc#351]
Struggling to get this working with Gatsby.

First its due to gatsby running in node so we have to add a window check.. 
I fixed this by adding a window check for the withRouter 

```
if (typeof window !== 'undefined') {
var _default = withRouter(window, CreateEvent(window, document), generateKey);
}
```
but then i i get lots of other others. Wondering if it's easy to add some window checks to get this working in Gatsby?

### Versions
    "@axa-fr/react-oidc-context": "^3.0.4-alpha.0",
    "@axa-fr/react-oidc-context-fetch": "^3.0.4-alpha.0",
  "gatsby": "^2.15.14",

**Comment by guillaumechervetaxa** [comment]
Hi @trickydisco78 ,

Thank you for your issue. 
We never used Gastby before, so it will take time for us to understand your need.

Do you have your Gastby code accessible somewhere ? (in order to understand your problem)

What you need is to make the oidc-lib not crashing during a server side rendering ? Do you know why window is undefined ? @samuel-gomez-axa you are a Gastby expert, do you understand the need here ?

Regards,

**Comment by trickydisco78** [comment]
Hi,
I've now got it working by wrapping lots of calls in 
`if (typeof window !== 'undefined') `

In callBackcontainer (line 56)
authenticationConsumers (line 71)
withRouter (oidc-core) line 68

Gatsby runs all code in node to build out pages.. and then the rest is standard react components with fetch calls for components. We are using the context version with hooks

**Comment by samuel-gomez-axa** [comment]
hi
i never see this problem, but i never use react-oidc with gatsby ;)
Gatsby have his own routing system, so i'm not sure there are compatibles.
Is it possible to have an access of your source code, please ?

**Comment by trickydisco78** [comment]
I'm sorry it's an authenticated app that isn't in production yet so covered by NDA stuff. 
Like i say i got it working by adding a window!== undefined check around a few functions:

In callBackcontainer (line 56)
authenticationConsumers (line 71)
withRouter (oidc-core) line 68

and this allowed it to build.
Although wondering if like youy say requires more work because of the routing?
