### ISSUE TITLE
When the user is logged out from Identity server from different window, it does not redirect the user to logout page.

### ISSUE THREAD

**Issue by Shashank-11** [AxaGuilDEv/react-oidc#360]
Package: @axa-fr/react-oidc-context

Senario: When the same application is opened on 2 different windows, and the user logs out of the 1st application, the second application does not log off the user. Instead it gets stuck at 
```  authenticating={Authenticating}```.
Expected result: The user should log out of the application even if it's on different window.

Here are few logs on console. 
![Screen Shot 2019-12-23 at 1 32 46 pm](https://user-images.githubusercontent.com/28638340/71332044-bfb03e80-2588-11ea-891c-bf136ffab4a0.png)

```ResponseValidator._processSigninParams: Response was error login_required``` should it expose some event and we can redirect user to logout/login uri.

**Comment by guillaumechervetaxa** [comment]
And also, in the context version, the logout call display the login callback component ^^ 
this is look strange

**Comment by guillaumechervetaxa** [comment]
thanjk you @Shashank-11 for this issue,

Do you need a resolution quickly ?

Have you tried to add token invalidation in the configuration during logout ? does-it work ? 
configuration available here
 https://github.com/IdentityModel/oidc-client-js/wiki

**Comment by Shashank-11** [comment]
> thanjk you @Shashank-11 for this issue,
> 
> Do you need a resolution quickly ?
> 
> Have you tried to add token invalidation in the configuration during logout ? does-it work ?
> configuration available here
> https://github.com/IdentityModel/oidc-client-js/wiki

Is there a quick fix to it? I do need it quickly :)

If you mean `revokeAccessTokenOnSignout: true,` ? I tried that flag as well.

**Comment by Shashank-11** [comment]
@guillaumechervetaxa any plans of looking at it in near future?

**Comment by guillaumechervetaxa** [comment]
I have to do it before april for one Application in my team.
I won't have enougth time in January to do it.
@youf-olivier ?

**Comment by youf-olivier** [comment]
Yes. I'll take this one.

**Comment by Shashank-11** [comment]
thanks @youf-olivier and @guillaumechervetaxa

**Comment by dragos-rosca** [comment]
Hope this helps:
If you look at your screenshot you will see that the UserManager still finds the user in it's storage ... so as a work around i just added a callback to the userSignedOut event (you have events in returned by your useReactOidc() hook or just find the events in userManager) and in that callback I just called userManager.removeUser() and it seems to work.

```javascript
const { events } = useReactOidc();
    useEffect(() => {
        if (!events) return
        events.addUserSignedOut(addUserSignedOut);
        return () => {
            events.removeUserSignedOut(addUserSignedOut);
        };
    }, [events])
```
and something like:

```javascript
const addUserSignedOut = () => {
    const userManager = getUserManager()
    userManager.removeUser();
}
```

I'm still looking for an official solution!

**Comment by carmenbreezy** [comment]
Hi there, has there been an official fix for this issue yet? Currently experiencing the same thing on version 3.1.6.

Thanks!

**Comment by youf-olivier** [comment]
Not Yet, sorry :(

**Comment by MadikMayCry** [comment]
Yo, i'm facing the same problem with @axa-fr/react-oidc-redux package
`import * as ReduxOidc from "redux-oidc";`
    `const logout = () => {
    dispatch(ReduxOidc.userSignedOut());
    setTimeout(() => {
      history.push("/");
    }, 200);
  }`

**Comment by guillaume-chervet** [comment]
Hi @Shashank-11 and @carmenbreezy and @dragos-rosca this was fixed in v5.
Very sorry for the delay. I close the issue feel free to reopen it if needed.
