### ISSUE TITLE
oidc-client should be in dependencies and not peerDependencies

### ISSUE THREAD

**Issue by guillaumechervetaxa** [AxaGuilDEv/react-oidc#388]
When we install the lib the run crash because it does not install oidc-client.
when we are doing npm i

we need to install oidc-client manually by:
npm i oidc-client

**Comment by guillaumechervetaxa** [comment]
sample here https://github.com/AxaGuilDEv/react-toolkit/pull/508/files

**Comment by guillaumechervetaxa** [comment]
i have sthe same with recompose.

We should remove recompose dependency.

**Comment by drwaky** [comment]
Same here, I also have the same with "recompose" and "redux-oidc" on "react-oidc-redux".
