### ISSUE TITLE
Update proptypes package version inside package.json

### ISSUE THREAD

**Issue by guillaumechervetaxa** [AxaGuilDEv/react-oidc#389]
i do not have PropTypes installed on my project and  when I install reac-oidc, it install an old version that crash at runtime :

![image](https://user-images.githubusercontent.com/43414465/72627314-8af79300-394c-11ea-9543-79fff0832c4f.png)

I add to install a recent version od PropTypes in order to make it works.

**Comment by guillaumechervetaxa** [comment]
https://github.com/AxaGuilDEv/react-toolkit/pull/508/files sample here

**Comment by guillaume-chervet** [comment]
Not relevant any more
