### ISSUE TITLE
react-oidc-client 3.0.6 -> UserManager undefined

### ISSUE THREAD

**Issue by RamaBerthin** [AxaGuilDEv/react-oidc#390]
### Issue and Steps to Reproduce
Refresh browser (F5)
Look at browser's console.
### Versions
react-oidc v3.0.6
### Screenshots
![react-oidc](https://user-images.githubusercontent.com/34276455/72734792-cf786e00-3b9a-11ea-9026-9a26e8cb2060.png)

#### Expected
No error
#### Actual
UserManager undefined
### Additional Details
.
- Installed packages:
.

**Comment by ludojmj** [comment]
Same issue as [#403 Unhandled Rejection (TypeError): userManager is undefined](https://github.com/AxaGuilDEv/react-oidc/issues/403)
