### ISSUE TITLE
User session seems lost

### ISSUE THREAD

**Issue by ghostd** [AxaGuilDEv/react-oidc#391]
Hi,

I cloned master (commit b222ce7c2) and ran the following commands:
```sh
npm i
npm run bootstrap
npm run example:context
```

I open the example app in Chromium, i authenticate with 'bob' and when i'm back to the app, the header does not contain the navigation links. I added `console.log` into `Header` to debug the props, the oidcUser is null. (and if i click on 'login' again, nothing happens; the application seems to have an inconsistent state)

Any idea what's wrong?

Regards

**Comment by ghostd** [comment]
It works fine with Firefox... i guess there is a problem with the storage or something like that.

**Comment by ghostd** [comment]
Ok i fixed (worked around?) the problem by changing my chrome settings: Advanced -> Privacy and security -> Site settings -> Cookies and site data -> add 'demo.identityserver.io' into 'Allow' section

**Comment by guillaume-chervet** [comment]
I think it should come from your internal enterprise policies.

**Comment by ghostd** [comment]
That's possible. I close the issue. Thanks
