### ISSUE TITLE
React oidc core still has a console.

### ISSUE THREAD

**Issue by Shashank-11** [AxaGuilDEv/react-oidc#397]
`authenticationService.js` has a console log `console.log('overridenConfiguration', overridenConfiguration);`. Can we release the latest version? I have seen it has been replaced by oidcLog.dubug but haven't been released yet.

@guillaumechervetaxa

**Comment by guillaumechervetaxa** [comment]
sure we can !

**Comment by guillaumechervetaxa** [comment]
Done :)
