### ISSUE TITLE
Feature Request : add a widget mode

### ISSUE THREAD

**Issue by rpetigny** [AxaGuilDEv/react-oidc#400]
I want to use the package in a widget context, without an redirection during the signin process.
If there is no current session, I just want to be notified, but not being redirected to a signin ou an error page.

**Comment by guillaume-chervet** [comment]
Do you still need this @rpetigny ?

**Comment by guillaume-chervet** [comment]
You can do that with the v4 version.  I close the issue, feel free to re open it if needed.
