### ISSUE TITLE
Does the prelogin page support English?

### ISSUE THREAD

**Issue by chinaq** [AxaGuilDEv/react-oidc#401]
The prelogin page show "Authentification en cours", how can we customize it to show other language like English, Chinese or Japanese etc.? Thanks.

**Comment by guillaumechervetaxa** [comment]
Hi @chinaq ,

sure you can by setting up overrided component => 
 notAuthenticated: PropTypes.elementType, // react component displayed during authentication
  notAuthorized: PropTypes.elementType, // react component displayed in case user is not Authorised
  authenticating: PropTypes.elementType, // react component displayed when about to redirect user to be authenticated
  callbackComponentOverride: PropTypes.elementType, // react component displayed when user is connected
  sessionLostComponent: PropTypes.elementType, // react component displayed when user loose authentication session
  configuration: PropTypes.shape({

Checkout the readme =>

https://github.com/AxaGuilDEv/react-oidc/tree/master/packages/context#readme.md

**Comment by chinaq** [comment]
Thanks @guillaume-chervet
