### ISSUE TITLE
How to redirect with a saved url after login

### ISSUE THREAD

**Issue by MickaelMuller** [AxaGuilDEv/react-oidc#402]
Hello everyone and thank you for your hard work.

I have an application that uses react oidc, if a user comes to my site with the url : mysite.com/books/12, he will be redirected to the login page and then come back to my site but will have lost this url and will arrive at the base on mysite.com.

Is there any way to keep this url with react oidc? 

Thank you, everyone.

### Versions
3.0.8

**Comment by guillaume-chervet** [comment]
Hi @MickaelMuller, do you have more detail like your provider and your configuration.

Are you using redux or context version?

I am using the context version and my url is still the samedi After login.

Does your provider Givenchy you back the context statue?

**Comment by MickaelMuller** [comment]
Thank you for your response @guillaume-chervet, and I'm sorry for the delay.

I use react-oidc-context version

Here is my configuration 

```
import { AuthenticationProvider } from '@axa-fr/react-oidc-context';
import React from 'react';
import ReactDOM from 'react-dom';

import { Authenticating, Callback, NotAuthenticated, NotAuthorized } from './components/Authentication';
import App from './App';
import configuration from './configurationOIDC';

const Start = (
  <AuthenticationProvider
    authenticating={Authenticating}
    callbackComponentOverride={Callback}
    configuration={configuration}
    notAuthenticated={NotAuthenticated}
    notAuthorized={NotAuthorized}
  >
    <App />
  </AuthenticationProvider>
);

ReactDOM.render(Start, document.getElementById('root'));
```

``` 
const configuration = {
  authority: 'https://a08cars001/identity',
  automaticSilentRenew: true,
  client_id: 'cars-front-client',
  loadUserInfo: true,
  post_logout_redirect_uri: 'http://localhost:3000/',
  redirect_uri: 'http://localhost:3000/authentication/callback',
  response_type: 'code',
  scope: 'openid cars-front-api',
  silent_redirect_uri: 'http://localhost:3000/authentication/silent_callback ',
  triggerAuthFlow: true,
};

export default configuration;
```

My contextProvider actually give me back ```state: {url: '/'}```

**Comment by MickaelMuller** [comment]
Solved it ! I just put my `<BrowserRouter>` before ` <AuthenticationProvider>` : 

```
<BrowserRouter>
    <AuthenticationProvider
      authenticating={Authenticating}
      callbackComponentOverride={Callback}
      configuration={configuration}
      notAuthenticated={NotAuthenticated}
      notAuthorized={NotAuthorized}
    >
      <App />
    </AuthenticationProvider>
  </BrowserRouter>
```

Now my provider gives me back the context state with the url.

But i got another problem now => I use [React-admin](https://github.com/marmelab/react-admin) for my application. React-admin manages urls internally and puts a # at the beginning of the url : mysite.com/#/books/12

So, when i type mysite.com/#/books/12 => i got '/' in my provider state and redirect at mysite.com/#/
when i type mysite.com/books/12 => i got '/books/12' in my provider state and redirect at mysite.com/books/12#/ 

I think it's a React-admin problem but i ask anyway if you have a solution with OIDC
