### ISSUE TITLE
How do I run your enhanced fetch on page load?

### ISSUE THREAD

**Issue by cstack89** [AxaGuilDEv/react-oidc#412]
### Issue and Steps to Reproduce

When my component loads I would like to run a few fetch calls to populate some initial data. I'm not very familiar with compose/recompose, and haven't been able to get it working. Using this as a guideline -  https://github.com/AxaGuilDEv/react-oidc/blob/master/examples/context/src/Pages/Home/Home.jsx I was able to get an example to work on button click.

### Versions

3.0.8

### Additional Details

- Installed packages:

**Comment by cstack89** [comment]
I got it working by adding an import: 

`import withAuthentication from '@axa-fr/react-oidc-context-fetch';`

and then wrapping my fetch calls

`withAuthentication(
	  		fetch("/test/me")
			.then(function(response) {
		         console.log(response.status);
		         console.log(response.statusText);
		         return response.text();
		 	})
		    .then(function(body) {
		       console.log( body); 
		    })
		    .catch(e => alert(e))
);`

**Comment by cstack89** [comment]
I was wrong, it ended up being a bug on my Resource Server side. I'm still having trouble trying to use the enhanced fetch on componentmount instead of on button click.

**Comment by Ediste** [comment]
I'm also having trouble to use the enhanced fetch after the component loaded. I'm working with react hooks and i can't get it to work after the component loaded (useEffect).  After a button click - like in the examples - its working.

**Comment by cstack89** [comment]
I've made a little bit of progress after converting my component to use hooks. I can now successfully send an authentication token like this

 ```
let myProps = {user: oidcUser};
 let myFetch = fetchToken(fetch)(myProps);
myFetch.fetch(...)
```

However once that token expires my program stops working again.  I'd like to use withAuthentication or equivalent, but think I'm fundamentally confused on how to use recompose without passing in an object.

**Comment by Ediste** [comment]
After hours of experimenting I found a way to do it:

```
import React, { useEffect, useState } from 'react'
import { withAuthentication } from '@axa-fr/react-oidc-context-fetch'
import { compose } from 'recompose'

const View = (props) => {
	const {fetch : authFetch } = props	

	const [isLoading, setIsLoading] = useState(false)
	const [items, setItems] = useState([])
	 
	useEffect(() => {
		setIsLoading(true)
		
		authFetch('yourapi')
			.then(response => response.json())
			.then(data => {
				setItems(data)
			})
			.catch((error) => {
				notificationDanger(error.message)
			}).finally(() => {
			  setIsLoading(false)
			})
		
	}, [authFetch]
}

const enhancer= compose(
  withAuthentication(fetch)
)


export default enhancer(View)
```

**Comment by cstack89** [comment]
Thanks for the help, that builds and works, but it seems like the silent refresh isn't working. After 15 minutes, I start to get 401 errors.

**Comment by Ediste** [comment]
I can't confirm that. With the above code i no longer got any 401 errors. After a while i also see the silent_callback request in the network tab.

**Comment by guillaumechervetaxa** [comment]
Do you have errors in console during the refresh of the tokens ?

You may have to check your silent callback url.

**Comment by guillaumechervetaxa** [comment]
From the previous code, you dont relly need to use recompose. withAuthentication is just an HOC https://fr.reactjs.org/docs/higher-order-components.html.

the HOCs return an enhanced version of fetch.

The aim is to be able to compose complee behaviors that fit your needs :
https://github.com/AxaGuilDEv/react-oidc/tree/master/packages/fetch-core/src 
https://github.com/AxaGuilDEv/react-oidc/tree/master/packages/context-fetch/src


import React, { useEffect, useState } from 'react'
import { withAuthentication } from '@axa-fr/react-oidc-context-fetch'

const View = (props) => {
	const {fetch : authFetch } = props	

	const [isLoading, setIsLoading] = useState(false)
	const [items, setItems] = useState([])
	 
	useEffect(() => {
		setIsLoading(true)
		
		authFetch('yourapi')
			.then(response => response.json())
			.then(data => {
				setItems(data)
			})
			.catch((error) => {
				console.log(error)
			}).finally(() => {
			  setIsLoading(false)
			})
		
	}, [authFetch]
}

export default withAuthentication(fetch)(View)

**Comment by cstack89** [comment]
I'm going to do some more code refactoring, but I think I might know what my problem is and at least a work around. I can see my silent authentication work. But my code is currently written inside a timer block, so I suspect that the HOC doesn't work until the whole component is re created? Here is what my component currently looks like:


```
const View = (props) => {
const {fetch : authFetch } = props

const [items, setItems] = useState([])
 
useEffect(() => {
           let interval = setInterval(() => testAPI(),10000);
           return function cleanup() {
	            clearInterval(interval);
           };
}, [authFetch]);

testAPI() {
           authFetch("yourapi")
		.then(response => response.json())
		.then(data => {
			setItems(data)
		})
		.catch((error) => {
			console.log(error)
		}).finally(() => {
		  setIsLoading(false)
		});
          }
}

export default withAuthentication(fetch)(View)
```

**Comment by cstack89** [comment]
I refactored my code, so it reloads my component periodically instead of periodically making a rest call. That fixed the issue. I did some googling and there is some weird interaction between hooks and setInterval that I didn't know about.
