### ISSUE TITLE
Proposal - Allowing hooking into the oidc-client events in the AuthenticationProvider

### ISSUE THREAD

**Issue by michael-wolfenden** [AxaGuilDEv/react-oidc#415]
# Scenario

I would like to hook into the events raised by `oidc-client` for logging and specifically the `userLoaded` and `userUnloaded` events for setting and clearing the default authorization header for all `axios` requests.

Although the `useReactOidc` hook exposes `events`, if you try the code below and login, the `addUserLoaded` event is never fired as it's too late in the lifecycle.

```js
<AuthenticationProvider
  configuration={oidcConfiguration}
  loggerLevel={oidcLog.DEBUG}
>
  <DebugEvents />
</AuthenticationProvider>

const DebugEvents = ({ children }) => {
  const { events } = useReactOidc()
  const addUserLoaded = () => console.log('===== userLoaded')

  React.useEffect(() => {
    events.addUserLoaded(addUserLoaded)

    return () => {
      events.removeUserLoaded(addUserLoaded)
    }
  })

  return children
}
```

# Proposal

My proposal is that `AuthenticationProvider` exposes a prop for each of the `oidc-client` events.

For example

```js
<AuthenticationProvider
  configuration={oidcConfiguration}
  loggerLevel={oidcLog.DEBUG}
  onUserLoaded={user => console.log(user)}
  onUserUnloaded={() => console.log('user unloaded')}
  onSilentRenewError={() => console.error('silent renew failed')}
>

</AuthenticationProvider>
```

If there is a way to achieve the above without modifying the library, I'd be happy to hear it.

**Comment by guillaumechervetaxa** [comment]
@michael-wolfenden thank you for your idea and feedback !

@youf-olivier, what do you think about it?
It seem to be a good idea.

**Comment by youf-olivier** [comment]
I have to make some tests.

**Comment by youf-olivier** [comment]
Ok. You're right. We received some events too late.

**Comment by Ediste** [comment]
Anyone found a workaround? I want to call a api to load extra information after each login. I have no idee how to achieve that with the current implementation.
