### ISSUE TITLE
lost history props

### ISSUE THREAD

**Issue by samuel-gomez-axa** [AxaGuilDEv/react-oidc#419]
### Issue and Steps to Reproduce
I'm using the HOC withOidcSecure on my routes and renderProps to pass router props.

![image](https://user-images.githubusercontent.com/43414022/77407054-dfd4e100-6db5-11ea-93df-dc91763c1453.png)

Since i updated to the **v3.0.9-alpha.0 from 2.0.8**

**i'm losing history prop on pages.** 

i tested to take of the HOC **withOidcSecure** and i retreive all router props on my pages.

### Screenshots

props received on my page **WITH withOidcSecure**

![image](https://user-images.githubusercontent.com/43414022/77407302-393d1000-6db6-11ea-8949-d13c73333935.png)

props received on my page **WITHOUT withOidcSecure**

![withoutHOC](https://user-images.githubusercontent.com/43414022/77406842-8bc9fc80-6db5-11ea-8956-10c8cb36e2c1.jpg)

### Additional Details

- Installed packages:

**Comment by youf-olivier** [comment]
Can you show me your global layout ? With your Router and your React oidc provider ?

**Comment by samuel-gomez-axa** [comment]
Here my App.js file with AuthenticationProvider

![image](https://user-images.githubusercontent.com/43414022/77408052-676f1f80-6db7-11ea-8a52-7b078ca6ce12.png)

Thanks for your help

**Comment by samuel-gomez-axa** [comment]
i tested to rollback to v2.0.8 and the bug doesn't exist anymore.
I also noticed that there was a redirection problem on the callback on my router, this may be related. if this problem persists after fixing this bug, I will do another issue

**Comment by youf-olivier** [comment]
Since few versions React Oidc is React Router Agnostic. Can you try to switch Router Provider and React OIdc line ? 

Like : 
```javascript
<authenticationProvider {...} >
   <router {...} >
   </router>
<authenticationProvider />
`
``

React oidc uses his own history object. He possibly override or hide the history props.

**Comment by samuel-gomez-axa** [comment]
ok thank you, i try it

**Comment by samuel-gomez-axa** [comment]
The switch doesn't fix the bug.
I think the bug comes from this file. : AuthenticationConsumers.js

` export const withOidcSecurewithRouter = WrappedComponent => ({  location,  history,   authenticateUser: authenticateUserInternal,
  getUserManager: getUserManagerInternal,
  ...otherProps
}) => {
  const { oidcUser, authenticating, isEnabled } = useOidcSecure(
    authenticateUserInternal,
    getUserManagerInternal,
    location,
    history
  );
  const requiredAuth =  useMemo(() => isRequireAuthentication(oidcUser, false) && isEnabled, [
    isEnabled,
    oidcUser,
  ]);

  const AuthenticatingComponent = authenticating || Authenticating;
  return requiredAuth ? <AuthenticatingComponent /> : <WrappedComponent {...otherProps} />;
};`

In this HOC, the location and history have been spread but not re-injected in WrappedComponent.

What do you think about this ?

**Comment by youf-olivier** [comment]
You're probably right

**Comment by guillaume-chervet** [comment]
I this this is fixed by v4. May i close the issue @samuel-gomez-axa ?
