### ISSUE TITLE
Cors problems with local asp.net backend

### ISSUE THREAD

**Issue by Sanchklyc** [AxaGuilDEv/react-oidc#420]
### Issue and Steps to Reproduce
I setup configuration in sample context project with mine. I'm sure this configuration works well in backend because I can generate & access token from Postman. My backend uses Steam auth.
But when I click login in the sample it throws an error.

> Access to XMLHttpRequest at 'https://localhost:44370/.well-known/openid-configuration' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Versions 
Latest version

### Screenshots
![image](https://user-images.githubusercontent.com/59770497/77994551-e83b9780-7332-11ea-8e1f-32be03c07c99.png)

- Installed packages:
 sample project context

**Comment by patriciadelima** [comment]
Hello, everyone!
I am trying to use the sample with WSO2 APIM and I had the same problem.
I've tried to use IP insteaf of localhost but it doesn't work.
Any thoughts?
Thanks!
