### ISSUE TITLE
Metadata does not contain property userinfo_endpoint ?

### ISSUE THREAD

**Issue by Sanchklyc** [AxaGuilDEv/react-oidc#421]
### Issue and Steps to Reproduce
I'm getting this error when i'm trying to authenticate with steam using my asp.net 3.1 backend api

### Versions
Latest version
### Screenshots
![image](https://user-images.githubusercontent.com/59770497/78007069-71a89500-7346-11ea-8069-cbf44a719ba8.png)

#### Expected
Authenticate successfully

- Installed packages:
None, I'm using example context project just editing configuration.js

**Comment by ghostd** [comment]
Hi,

Can you check your network panel? `oidc-client` makes a request to `http://your.backend.example.com/.well-known/openid-configuration` which should respond correctly according to the [specification](You can find the specification of this endpoint here : https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata)

For example, if you run the example (without modifications) you should see a request to https://demo.identityserver.io/.well-known/openid-configuration

If your backend [does not provide the metadata](https://github.com/IdentityModel/oidc-client-js/wiki#provider-settings-if-cors-not-supported-on-oidcoauth2-provider-metadata-endpoint), you can provide the required settings into the configuration object.

**Comment by guillaume-chervet** [comment]
I @ghostd and @Sanchklyc it is possible to provide metadata in latest v5.
Very sorry for the delay. I close the issue. Feel free to reopen it if needed.
