### ISSUE TITLE
After auth component doesn't render (withOidcSecure)

### ISSUE THREAD

**Issue by AntoninBeaufort** [AxaGuilDEv/react-oidc#422]
### Issue and Steps to Reproduce

After auth my component in withOidcSecure doesn't render, i need to refresh the page or swap to another. It is the same with OidcSecure component wrapper.

### Versions
@axa-fr/react-oidc-context 3.0.9-alpha.0

### Screenshots
Just blank page.

#### Expected
Render the component.

#### Actual
Doesn't render anything after auth.

### Additional Details

I am using React TypeScript with Ionic.

**Comment by youf-olivier** [comment]
We often this issue when you put React Oidc under React router (or equivalent)

If you switch them, you often resolve the problem :

```javascript
const App = () => (
  <div>
    <AuthenticationProvider {...}>
      <Router>
        <Header />
        <Routes />
      </Router>
    </AuthenticationProvider>
  </div>
```

Are you in this case ?

**Comment by AntoninBeaufort** [comment]
@youf-olivier Thank you it works now !
I've made a workaround using `window.location.reload()` in the withRouter file, but now I have the good solution.

I think it should be wrote in the docs, because in the "@axa-fr/react-oidc-context" docs the example shows the `AuthenticationProvider` under the `Router`.

**Comment by youf-olivier** [comment]
Yes, you're right

can you open an issue, or make an awesome PR ? :D

**Comment by chmieludaniel** [comment]
I have the same issue, and flipping the order doesn't help. The url changes in the browser correctly, back to the path, where it used to be before performing auth, but the router keeps `/authentication/callback` pathname as "current".

Also, I need to keep some public routes in my app.

As a workaround I applied `window.location.reload()` if I detect that router path is the same as oidc config `redirect_uri` path, but it would be nice to have it solved
