### ISSUE TITLE
Log out not working when on a protected page

### ISSUE THREAD

**Issue by damien7792** [AxaGuilDEv/react-oidc#427]
### The Log out function doesn't work when on a protected page

When I place a log out button in the navigation bar, it only works if I click on that button from an unprotected page. If I do it from a protected page, the api call to "endsession?id_token=..." gets canceled before even reaching identity server. Then the page reloads, and I'm still authenticated.

If the button is clicked from an unprotected page, it works fine.

### Versions
3.0.9-alpha.0
### Screenshots

Network calls:
![image](https://user-images.githubusercontent.com/40440777/78598150-6527af00-7814-11ea-8b59-077a203ff1f4.png)

My index.js
![image](https://user-images.githubusercontent.com/40440777/78598245-999b6b00-7814-11ea-8413-3e4edc51010a.png)

This component is displayed in the navigation bar
![image](https://user-images.githubusercontent.com/40440777/78598349-c780af80-7814-11ea-95bf-14f6fc16bb91.png)

Is there something I'm doing wrong?

#### Expected
I expect the log out button to trigger the endsession call successfully to get logged out no matter what page I'm on (protected vs unprotected)

#### Actual
The call is canceled and the page refreshed when the button is clicked form a protected page.

### Additional Details
I've noticed this ticket that has been closed. It suggests a workaround, but I was wondering if a long term solution was being worked on.
https://github.com/AxaGuilDEv/react-oidc/issues/208

Thank you

**Comment by damien7792** [comment]
Also, is there a Log Out function in the Redux package?
If not, what's the recommended way to log out?

**Comment by youf-olivier** [comment]
Close with #439
