### ISSUE TITLE
Transition component defined in "authenticating" not working with Redux package

### ISSUE THREAD

**Issue by damien7792** [AxaGuilDEv/react-oidc#429]
### Issue and Steps to Reproduce

I tried the context package with a test React project successfully. 
When I transitioned to my React-Redux project, using the Redux package, I noticed that the "authenticating" setting in the Oidc component doesn't seem to work.

I created a "WaitScreen" component like this

```
import * as React from 'react';
import { connect } from 'react-redux';

const WaitScreen = () => (
    <div>
        <h1>Please wait...</h1>
    </div>
);

export default connect()(WaitScreen);
```

And I set it up in the Oidc component like this:

```
ReactDOM.render(
    <Provider store={store}>
        <ConnectedRouter history={history}>
            <Oidc
                store={store}
                configuration={oidcConfiguration}
                isEnabled={true}
                authenticating={WaitScreen} // Transition page while redirecting to login page
            >
                <App />
            </Oidc>
        </ConnectedRouter>
    </Provider>,
    document.getElementById('root'));
```

When I'm navigating to a protected page, it's not the WaitScreen component which is displayed while I'm redirected, but the default "Authentification en cours" (see screenshot below)

Note that this was working with the React-only version and the context package.

Is there some settings I'm missing?
Thanks
Damien

### Versions

"@axa-fr/react-oidc-redux": "^3.0.9-alpha.0"

### Screenshots

![image](https://user-images.githubusercontent.com/40440777/78806952-00da2c00-7989-11ea-9f87-46b29e2e78b8.png)

#### Expected
I expect the "Please wait" message to be displayed while I'm redirected to the authentication page

#### Actual
The default "Authentication en cours" is displayed

**Comment by bbodensieck** [comment]
We discovered the same effect here. Also saw this issue #401 and tried out which is written in the readme [here](https://github.com/AxaGuilDEv/react-oidc/tree/master/packages/context#readme.md). When debugging it tries to render `/node_modules/@axa-fr/react-oidc-core/dist/default-component/Authenticating.component.js` @guillaume-chervet any ideas?

**Comment by guillaumechervetaxa** [comment]
I think that this PR #463 is going to fix it.

**Comment by bbodensieck** [comment]
It is fixed for me! Thank you. @damien7792 @guillaumechervetaxa

**Comment by damien7792** [comment]
Thank you @guillaume-chervet
