### ISSUE TITLE
Remove the use of oidc-client or split oidc-client in multiple packages

### ISSUE THREAD

**Issue by guillaume-chervet** [AxaGuilDEv/react-oidc#441]
Oidc-client is awesome but to big and we do not use half of the librairy capabilities.

Of course the base code should be agnostique of react. It does not seem to intricate to do.

**Comment by ghostd** [comment]
Hi,

Does it mean you consider to have your own oauth implementation?

Regards

**Comment by guillaumechervetaxa** [comment]
yes, but may be before we can discuss in order to make oidc-client beeing more modular

**Comment by youf-olivier** [comment]
Do you really think you can do it better than oidc client ?

**Comment by youf-olivier** [comment]
It think we have to keep it, for a simple reason : 

https://openid.net/developers/certified/

It is a OIDC certified library.

**Comment by ghostd** [comment]
We can create an oidc-client issue to start the discussion. It seems they plan a [2.0 milestone](https://github.com/IdentityModel/oidc-client-js/milestone/1), maybe it could be a part of this as that would be a breaking change.

(TBH i'm not very optimistic about a version 2.0 in a short delay, some issues marked as '2.0' are opened since 2017)

**Comment by guillaume-chervet** [comment]
I think that it is not so hard to be certified Olivier. We can contribue to the oidc client issue too.

**Comment by ghostd** [comment]
Do you already know what feature would be packaged and what feature would be not if you make your own impl?

Here is the "optional" Oidc features i use on my project:
* discovery request (fetch `.well-known/openid-configuration`)
* user info request
* checksession and logout

**Comment by DaleyKD** [comment]
If you don't use the OIDC Client library, then we can't use your library and that would be a shame.
