### ISSUE TITLE
Wrong version number in Changelog 

### ISSUE THREAD

**Issue by sgebhardt** [AxaGuilDEv/react-oidc#444]
### Issue and Steps to Reproduce

The last commit on master added the changes for release 3.0.9-alpha.0. But the version number mentioned in the changelog is v0.0.0.

### Versions
3.0.9-alpha.0

### Screenshots
![grafik](https://user-images.githubusercontent.com/661509/81055702-84743380-8ec9-11ea-9cdd-cfd5adf3862d.png)

#### Expected
The changelog should have the correct version number.

### Additional Details

- Installed packages:

**Comment by youf-olivier** [comment]
Closed with the last publication. Thanks for the repport :)
