### ISSUE TITLE
Missing content npm package v3.0.9-alpha.0

### ISSUE THREAD

**Issue by sgebhardt** [AxaGuilDEv/react-oidc#445]
### Issue and Steps to Reproduce
It looks like the last package publish is not complete. In the commit history there are two commits with the message " chore(release): publish v3.0.9-alpha.0 ***NO_CI*** ".
61c8884393c0df5ae37b0c8b113cb92a942602aa
ee811799c0ea5805bd9a56baca2742932dd98efd

The published npm package with version v3.0.9-alpha.0 does not contain all changes from the changelog.

For example, the typescript migration is missing.

I think the package only contains the code from commit ee811799c0ea5805bd9a56baca2742932dd98efd .

Also the branch "fix/session-lost" is not merged into master. This branch contains the first release-commit.
 
### Versions
v3.0.9-alpha.0

#### Expected
Changes listed in the changelog should be in the released package content.

#### Actual
Missing content in current released package.

### Additional Details

- Installed packages:

**Comment by sgebhardt** [comment]
I think npm ignored the last package publish, because the version number was the same as the release from commit ee811799c0ea5805bd9a56baca2742932dd98efd.

**Comment by youf-olivier** [comment]
Wow thanks.

**Comment by guillaumechervetaxa** [comment]
the version v3.1.0-alpha.0 seem to contain content :)

**Comment by youf-olivier** [comment]
I think we can close.
