### ISSUE TITLE
Silent signin causes rerender on component wrapped with OidcSecure

### ISSUE THREAD

**Issue by miszo** [AxaGuilDEv/react-oidc#450]
### Issue and Steps to Reproduce
I have a following structure of application:
App.jsx:
```jsx
import React from 'react';
import { AuthenticationProvider, InMemoryWebStorage, oidcLog } from '@axa-fr/react-oidc-context';

import Routes from 'src/Routes';
import {
  Authenticating,
  CallbackComponent,
  NotAuthenticated,
  NotAuthorized,
  SessionLostComponent,
} from 'src/components/Auth';
import oidcConfiguration from 'src/oidc-configuration';

function App() {
  return (
    <AuthenticationProvider
      authenticating={Authenticating}
      callbackComponentOverride={CallbackComponent}
      configuration={oidcConfiguration}
      isEnabled
      loggerLevel={oidcLog.DEBUG}
      notAuthenticated={NotAuthenticated}
      notAuthorized={NotAuthorized}
      sessionLostComponent={SessionLostComponent}
      UserStore={InMemoryWebStorage}
    >
      <Routes />
    </AuthenticationProvider>
  );
}

export default App;
```
oidc-configuration.js
```js
const oidcConfiguration = {
  acr_values: 'neededAcrValues',
  client_id: 'myClientId',
  redirect_uri: 'https://chat-app.example.com/auth',
  response_type: 'code',
  post_logout_redirect_uri: 'https://chat-app.example.com',
  scope: 'openid',
  authority: 'https://identity-provider.example.com',
  silent_redirect_uri: 'https://chat-app.example.com/silent-renew',
  automaticSilentRenew: true,
  loadUserInfo: true,
  monitorSession: true,
};

export default oidcConfiguration;
```

Routes.jsx
```jsx
import React from 'react';
import { BrowserRouter as Router, Switch, Route } from 'react-router-dom';
import { createBrowserHistory } from 'history';
import { OidcSecure } from '@axa-fr/react-oidc-context';

import Chat from 'src/components/Chat ';

const history = createBrowserHistory();

function Routes() {
  return (
    <OidcSecure>
      <Router history={history}>
        <Switch>
          <Route component={Chat} path="/" />
        </Switch>
      </Router>
    </OidcSecure>
  );
}

export default Routes;
```

And after every silent renew I get my chat component rerender which is frustrating because i loose my component state.
My `Chat` component have its own nested routing for selected conversation inside the chat.

### Versions
"@axa-fr/react-oidc-context": "3.1.0-alpha.0",

### Screenshots

![image](https://user-images.githubusercontent.com/3455863/82055629-13026500-96c1-11ea-907c-631891de9bda.png)

#### Expected

Just silent renew - no rerender should happen.

#### Actual

After every silent renew I get my chat component rerender which is frustrating because i loose my component state.

### Additional Details

I've tried to protect routing like this:
```
withOidcSecure(Dashboard)
import React from 'react';
import { BrowserRouter as Router, Switch, Route } from 'react-router-dom';
import { createBrowserHistory } from 'history';
import { OidcSecure } from '@axa-fr/react-oidc-context';

import Chat from 'src/components/Chat ';

const history = createBrowserHistory();

function Routes() {
  return (
    <OidcSecure>
      <Router history={history}>
        <Switch>
          <Route component={withOidcSecure(Chat)} path="/" />
        </Switch>
      </Router>
    </OidcSecure>
  );
}

export default Routes;
```
But it caused a rerender on every nested route change

- Installed packages:
"history": "4.10.1",
"oidc-client": "1.10.1",
"react": "16.13.1",
"react-dom": "16.13.1",
"react-router-dom": "5.1.2"

**Comment by guillaumechervetaxa** [comment]
You need to change

`<Route component={Chat} path="/" />`

by

`<Route  path="/">
<Chat/>
</Route>`

**Comment by miszo** [comment]
Hi,
I've just tried it and it causing the same behaviour.
Any other ideas? I have this problem since updating from 3.0.9-alpha.0

**Comment by miszo** [comment]
It seems like it is caused by this change:
https://github.com/AxaGuilDEv/react-oidc/pull/439/files#diff-462c9e930ccdc356bd080b7236f8e5bbR39

maybe there should be added another check like `isLoading`?

**Comment by guillaumechervetaxa** [comment]
I have 2 websites and aone of them have the same problem and not the other.

I will be able to check it next week.

**Comment by miszo** [comment]
OK, looking forward to hearing from you.
I'll try to fork your repo next week and try to debug it.

**Comment by guillaumechervetaxa** [comment]
It is a real re-gression @youf-olivier 

I have the bug on my 2 websites

**Comment by youf-olivier** [comment]
I will take that this week. Thanks for the issue

**Comment by youf-olivier** [comment]
There is an new release alpha 3.1.1-alpha.0

Can you test it and tell me if it resolve your issue ? 

Thanks.

**Comment by miszo** [comment]
Hi,

Locally it works fine - I've sent it yo our QA team just to doublechek.

Thanks a million

**Comment by miszo** [comment]
I've just got confirmation that it works, so thanks a million :)

BTW - when will you release not-alpha release? :)

**Comment by youf-olivier** [comment]
Glad to see that !! Not alpha could be released on monday I think.

And thank you very much to your contributions ! 🍻

**Comment by guillaumechervetaxa** [comment]
Strange, We seem to still have the bug in the version 3.1.1.

**Comment by guillaumechervetaxa** [comment]
I'am re-opening the issue, we still have the bug on our websites, I'am investigating

**Comment by guillaumechervetaxa** [comment]
It is working by using <OidcSecure> instead of the hoc withOidcSecure as a workaround. 

![image](https://user-images.githubusercontent.com/43414465/83620129-2ea8af00-a58d-11ea-9b46-25725966bcd7.png)
