### ISSUE TITLE
[FEAT] Add possibility to customize Authenticating component for oidc-redux as in oidc-context

### ISSUE THREAD

**Issue by vivo87** [AxaGuilDEv/react-oidc#452]
### Issue and Steps to Reproduce

Currently react-oidc-redux only allow to customize 4 components: 

  notAuthenticated: PropTypes.elementType,
  notAuthorized: PropTypes.elementType,
  callbackComponentOverride: PropTypes.elementType,
  sessionLostComponent: PropTypes.elementType,

and not Authenticating component as in oidc-context

### Versions 

Latest

#### Expected

Add `authenticating` props to Oidc or OidcSecure Component

### Additional Details

- Installed packages:

**Comment by vivo87** [comment]
I know it's not recommended to use redux for new project but for old one with redux i thinks it's a good idea to have the same feature

**Comment by drwaky** [comment]
The same happens to me, I need Authenticating component support to change the look and feel of that component in a Redux Project.

**Comment by vivo87** [comment]
it's relatively simple to add a prop to OidcSecure component. If the owner is ok i think i can make a PR after my holidays if no one is available in the meantime :P

**Comment by guillaumechervetaxa** [comment]
yes, go on :)

**Comment by vivo87** [comment]
[PR](https://github.com/AxaGuilDEv/react-oidc/pull/463) created

**Comment by vivo87** [comment]
Thank you for merging my PR, however there's an issues regarding core package dependencies after your release:

`npm ERR! code ETARGET
npm ERR! notarget No matching version found for @axa-fr/react-oidc-core@^3.1.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@axa-fr/react-oidc-redux'
`
Would you mind having a look at this issue because all my pipeline is blocked.

Thanks !

**Comment by guillaume-chervet** [comment]
thank you @vivo87 for you awesome pull request! It is working now.
