### ISSUE TITLE
Compatibility with redux-immutable

### ISSUE THREAD

**Issue by danpoq** [AxaGuilDEv/react-oidc#453]
### Issue and Steps to Reproduce

I'm migrating to react-oidc and finding it's more opinionated than using redux-oidc directly.

My app uses `combineReducers` from redux-immutable to create an immutable root reducer which means that the oidc state must be accessed like:

```js
state.get('oidc')
```

### Versions

```
"@axa-fr/react-oidc-redux": "^3.1.1-alpha.0"
```

### Expected

`<OidcSecure>` will connect to my redux state and display my components if the user has loaded.

### Actual

`<OidcSecure>` crashes with:

```
TypeError: Cannot read property 'isLoadingUser' of undefined
```

Because it's hardcoded to read from `state.oidc`.

### Solution

I suggest adding a new option in the configuration that defines how to read and write from the state. This would solve compatibility with redux-immutable and overall, it may be nice addition to be able to choose the name of the reducer for authentication. Right now, I have my user info in `auth` instead of `oidc`. e.g.

```js
const accessTokenForApiCalls = state.getIn(['auth', 'user', 'access_token']);
```

**Comment by guillaume-chervet** [comment]
Hi @danpoq, Sorry for the delay, we are quite busy.
Do you have time to make a pull request about it?
We are'nt using redux often and are not very familiar with redux-immutable.

It will require us some time before we can deeply reply to your needs.

**Comment by danpoq** [comment]
> Do you have time to make a pull request about it?

I don't sorry. I also remember looking through the source code when I opened this PR and didn't see a clear solution to this problem.

**Comment by guillaume-chervet** [comment]
Hi @danpoq , very sorry for the delay.
The new react-oidc is a complete rewrite. This version does not use any react context.
It is compatible with redux and react context.

I close the pull request. Thank you for the issue and very sorry for the delay.
If you need reopen it.
