### ISSUE TITLE
Not working with typescript [react-oidc-context]

### ISSUE THREAD

**Issue by Shashank-11** [AxaGuilDEv/react-oidc#472]
looks like all the builds has been broken with typescript for react-oidc-context.
None of the versions are working with typescript.
Versions: All
![Screen Shot 2020-06-16 at 12 51 32 pm](https://user-images.githubusercontent.com/28638340/84726458-3b3af780-afd0-11ea-845d-44d678bcca4b.png)

react-oidc-context has a dependency with react-oidc-core. is that version always pointing to the latest?
why are the previous builds failing?Is there a versioning miss-match with `react-oidc-context` and `react-oidc-core` ?

Is there a fall back version?

**Comment by bmaland** [comment]
Thanks for the fix, will you release a new version? Current version in npm doesn't work with typescript

**Comment by guillaume-chervet** [comment]
Sorry for the delay, we are quite busy. I just run a new minor version from master.
