### ISSUE TITLE
Login as Popup

### ISSUE THREAD

**Issue by Maxinger15** [AxaGuilDEv/react-oidc#482]
Is it possible to add a login method which shows a popup with the login of the auth-server instead of redirecting? 
I think this would save the state of the SPA and would enhance the user experience.

**Comment by Maxinger15** [comment]
Ok. Thank you for the information.

**Comment by darkowic** [comment]
In this case, @guillaume-chervet are there any recommendations on how to login if an app is an iframe and IDP blocks iframes?

**Comment by guillaume-chervet** [comment]
Hi @darkowic ,

You may create the popup from your application that will run react oidc authenticatio. Once authenticated If you are using service worker mode or localstorage mode your app will be authenticated.
