### ISSUE TITLE
Cannot login if using Simple OIDC provider qlik/simple-oidc-provider

### ISSUE THREAD

**Issue by regel** [AxaGuilDEv/react-oidc#491]
### Issue and Steps to Reproduce

I get error 400 when I try to use the source code in `examples/context` and Simple OIDC provider.

Steps to reproduce:

- Run [simple-oidc-provider](https://hub.docker.com/r/qlik/simple-oidc-provider/) in the background with default settings:
`
docker run --rm -p 9000:9000   -e "REDIRECTS=http://localhost:3000/authentication/callback"   qlik/simple-oidc-provider
`
- npm install
- Edit src/configuration.js using the settings below
- npm start
- Login with user `harley@qlik.example` and password `Password1!`

Edit the file `src/configuration.js` to use the simple OIDC provider running on port 9000:

```
const configuration = {
  client_id: 'foo',
  redirect_uri: 'http://localhost:3000/authentication/callback',
  response_type: 'code',
  post_logout_redirect_uri: 'http://localhost:3000/',
  scope: 'openid profile',
  authority: 'http://localhost:9000',
  silent_redirect_uri: 'http://localhost:3000/authentication/silent_callback',
  automaticSilentRenew: true,
  loadUserInfo: true,
};
```

### Versions

master

#### Expected

Successful login

#### Actual

Error 400. User not authenticated.

Server returns the following error to '/token' query:

`{"error":"invalid_request","error_description":"client_secret must be provided in the Authorization header"}
`
### Additional Details

Thanks for your help!

**Comment by regel** [comment]
So the question is how to configure the client to use "client_secret_basic" auth method?

**Comment by guillaume-chervet** [comment]
Hi @regel,

I think your oidc server must be configured to work with "Code Grant with pkce" Flow for client side. The client side do not have to store a secret.

**Comment by regel** [comment]
Hello Guillaume, thanks for the quick feedback. You're right. I added `"token_endpoint_auth_method": "none",` in simple-oidc-provider config file settings and now the login flow is successful and no longer requires client_secret from the client side.

Issue closed. 😄

**Comment by eghazal27** [comment]
@regel How were you able to edit the configuration.js file ? 
I didn't find it in the **src** directory. 
![image](https://user-images.githubusercontent.com/20153317/206230697-f68f14be-ecdd-47bb-97d3-69cc07f092f4.png)

**Comment by rushabh268** [comment]
Still getting this error - I tried passing the TOKEN_ENDPOINT_AUTH_METHOD = none via the Env for the container but it is not working and I don't see a configuration.js file so not sure how to get past the client secret required in header.
