### ISSUE TITLE
Get authenticated user in Public home page to redirect to private page

### ISSUE THREAD

**Issue by ysabih** [AxaGuilDEv/react-oidc#493]
Hello, first thanks for the library, easy to use and well documented. I would like to get if user is authenticated in the public home page to redirect them to the private page. Here's how I'm trying to do it:

In App.js:
`<Route exact path="/" component={Public} />`

Public.js
```
function Public() {

    const history = useHistory();

    return (
        <AuthenticationContext.Consumer>
            {authContextValue => {
                if(authContextValue.oidcUser == null){
                    return (
                        <h2>
                            Home
                        </h2>
                    );
                }
                else{
                    history.push('<private-home-page>');
                    return (
                        <></>
                    );
                }
            }}              
        </AuthenticationContext.Consumer>
    );
}
```

The problem is I can't access the oidcUser because the component is not wrapped in `<OidcSecure />`. I would like to know if there's a way to do that, and if there is not, whether it would be safe to access the user using the function `getUser()` in `oidc-client` directly.

**Comment by guillaume-chervet** [comment]
Hi @ysabih, I think it should work if you use the user hook or HOC.

**Comment by ysabih** [comment]
Thanks, I'll try again.
