### ISSUE TITLE
Enhancement Request: Allow `logout` to be passed arguments for `state`

### ISSUE THREAD

**Issue by anied** [AxaGuilDEv/react-oidc#503]
# Enhancement Request: Allow `logout` to be passed arguments for `state`

As near as I can tell, under the hood, `react-oidc` is calling into [`oidc-client-js`'s `UserManager`'s `signoutRedirect` instance method](https://github.com/IdentityModel/oidc-client-js/blob/98c6810f7e81dd7a4ffb779a7a7e89e4fe248ff1/src/UserManager.js#L428) in order to prompt a logout.  `signoutRedirect` accepts an `args` object, which can include a `state` property, which would be forwarded to any URL passed for `end_session_endpoint` as a query param.

It would be nice if the `logout` method made available via the various packages could be made to accept `args` (or possibly just `state`) so that it could be passed through to `react-oidc`'s `signoutRedirect`.  For instance, in the context variant, changing [`logoutCallback`](https://github.com/AxaGuilDEv/react-oidc/blob/b43b45dab5b2ae6f46cce62e3061e23ab388b61e/packages/context/src/oidcContext/AuthenticationContext.provider.tsx#L135) to something like this:

```typescript
  const logoutCallback = useCallback(async (args = {}) => {
    try {
      onLogout();
      await logoutUserInt(userManager, args);
      oidcLogInt.info('Logout successfull');
    } catch (error) {
      onError(error.message);
    }
  }, [logoutUserInt, oidcLogInt, onError, onLogout, userManager]);
```

and [`logoutUser` in `oidcServices.ts`](https://github.com/AxaGuilDEv/react-oidc/blob/master/packages/core/src/services/oidcServices.ts#L51) to something like this:

```typescript
export const logoutUser = async (userManager: UserManager, args) => {
  if (!userManager || !userManager.getUser) {
    return;
  }
  const oidcUser = await userManager.getUser();
  if (oidcUser) {
    oidcLog.info('Logout user...');
    await userManager.signoutRedirect(args);
  }
};
```

would enable leveraging of state.  That's obviously a rough, not very Typescripty example, but it is the sort of thing I am envisioning.

Being able to pass state through would allow us to take different actions on the way back into the application based on _how_ the user was logged out.  For example, we could opt to show a warning on the screen if they were logged out programmatically rather than by user action.

**Comment by guillaume-chervet** [comment]
Hi @anied, thank you for your issue,

We absolutely need to add this feature. @anied , do you have time to try a contribution?

**Comment by rahul-sharma-uipath** [comment]
@guillaume-chervet @youf-olivier do you mind if I open a PR for this?

**Comment by guillaume-chervet** [comment]
It would be very it would be very Nice :)

**Comment by rahul-sharma-uipath** [comment]
can you give me contributor permission? I want to open up a branch

**Comment by youf-olivier** [comment]
Hello. You just have to make a PR from a fork. We can't add you in the contributors because of internal Axa Policies. 

But don't worry it's very simple to contribute from a fork.
