### ISSUE TITLE
Context package: Get access_token from a function that is not a component

### ISSUE THREAD

**Issue by beckerpablo** [AxaGuilDEv/react-oidc#505]
Hi,
I'm using the context package.
I wan't to get the access_token from an async function that call an api. Using the redux package I'm doing something like store.getState().oidc.user.access_token but can't find the way to do this on context. 

This is my code where I want to add the access token:

```
export async function getList() {
  return fetch('https://run.mocky.io/v3/4b283449-3707-45a0-8571-729bbde89c38').then(response =>
    response.json(),
  )
}
```

Thank you very much in advance.

**Comment by guillaume-chervet** [comment]
Hi @beckerpablo ,

Thank you for your issue and using, the lib!

Below a link of an internal sample of how the lib redux-fetch retrieve the tokens :
https://github.com/AxaGuilDEv/react-oidc/blob/master/packages/redux-fetch/src/withFetchToken.ts

**Comment by guillaume-chervet** [comment]
You can also use directly that lib, that inject the tokens for you :
https://github.com/AxaGuilDEv/react-oidc/tree/master/packages/redux-fetch#readme.md

**Comment by guillaume-chervet** [comment]
Hi @beckerpablo , do you solve you problem?

**Comment by beckerpablo** [comment]
Hi Guillaume, how are you?

I solved it using oidc react redux without the fetch plugin. Do you know if
you are going to add the possibility to customize the redirect component
like you did in oidc context?

Thank you very much,

*Pablo Becker*
*3Pi Factory - Business Solutions*
Av. Corrientes 1386 piso 10 - C1043ABN - Buenos Aires - Argentina
t. +54 11 7078.0323 Ex.102
c. +54 9 11 5842.7777
*www.3pifactory.com* <http://www.3pifactory.com/>

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/07/20,
10:12:51 AM

**Comment by guillaume-chervet** [comment]
Yes we have add it. Do you need it soon?

**Comment by beckerpablo** [comment]
Great!, Before the end of year.

Thank you very much! you did a great job!

*Pablo Becker*
*3Pi Factory - Business Solutions*
Av. Corrientes 1386 piso 10 - C1043ABN - Buenos Aires - Argentina
t. +54 11 7078.0323 Ex.102
c. +54 9 11 5842.7777
*www.3pifactory.com* <http://www.3pifactory.com/>

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/08/20,
11:47:49 AM

**Comment by guillaume-chervet** [comment]
Hi @beckerpablo . I close the issue. It is out of date. Thank you very much for it.
