### ISSUE TITLE
On navigating between routes, entire app reloads

### ISSUE THREAD

**Issue by Ansalibrahim** [AxaGuilDEv/react-oidc#510]
### Issue and Steps to Reproduce
I have integrated `react-oidc` in on of my application. The authentication works good and after login I redirect the application to a home page, which is the only protected route (wrapped with `<OidcSecure>` or `withOidcSecure`, tried both). the home page has several other routes, like `home/accounts`, `home/questions`, etc.. Once I land on the home page if I try to change the route to `home/accounts` the app seems to be reloaded. 

App.ts
```
const App = (): ReactElement => (
  <StoreProvider>
    <ThemeProvider theme={theme}>
      <BrowserRouter>
        <AuthenticationProvider
          configuration={oidcConfiguration}
          loggerLevel={oidcLog.DEBUG}
          authenticating={AuthenticatingPage}
          callbackComponentOverride={AuthenticatingPage}
          notAuthenticated={AuthenticatingPage}
          notAuthorized={NotAutherizedPage}
        >
          <AppRouter />
        </AuthenticationProvider>
      </BrowserRouter>
    </ThemeProvider>
  </StoreProvider>
);
```
AppRouter.ts
```
const AppRouter = (): ReactElement => {
  const oidc = useReactOidc();
  const history = useHistory();
  useEffect(() => {
    if (oidc.oidcUser !== null) {
      console.log('HOME REDIRECTION');
      history.push('/home');
    } else {
      console.log('login REDIRECTION');
      oidc.login();
    }
  }, []);
  return (
    <Switch>
      <Route exact path="/">
        <Login />
      </Route>
      <Route path="/home">
        <OidcSecure>
          <Home />
        </OidcSecure>
      </Route>
    </Switch>
  );
};
```
Home.ts
```
export default function Home(): ReactElement {
  return (
    <>
      <Header />
      <HomeRouter />
      <Footer copyright="ProtoCall Services &copy; 2020" />
    </>
  );
}
```

### Versions
@axa-fr/react-oidc-context: ^3.1.4
oidc-client: ^1.10.1

#### Expected

Should not rerender the application when on local routes change.

#### Actual
It is re-rendering/reloading entire app when I navigating to `home/accounts` or `home/questions`

### Additional Details
It seems like when I do a `history.push('home/accounts')` the app is redirected to the identity server and came back to the `home/accounts` route

**Comment by guillaume-chervet** [comment]
Hi @Ansalibrahim,

I thing that you do not need that part of code

`const oidc = useReactOidc();
  const history = useHistory();
  useEffect(() => {
    if (oidc.oidcUser !== null) {
      console.log('HOME REDIRECTION');
      history.push('/home');
    } else {
      console.log('login REDIRECTION');
      oidc.login();
    }
  }, []);`

**Comment by guillaume-chervet** [comment]
Hi @Ansalibrahim, do you solve your problem.?

**Comment by Ansalibrahim** [comment]
@guillaume-chervet I am not sure. Maybe it was a misunderstanding of how things work. **But it now works perfectly**. I will close the issue. Thank you for your support and for the library.
