### ISSUE TITLE
Input looses focus after entering one char when wrapped in <OidcSecure>

### ISSUE THREAD

**Issue by Greg-Johns** [AxaGuilDEv/react-oidc#512]
When I wrap an input tag in a OidcSecure tag the input will loose focus after one character is entered. I can get around by wrapping only part of the page (without the input) in the OidcSecure tag but this is not expected behavior.

**Comment by guillaume-chervet** [comment]
Hi @Greg-Johns, sorry for the delay, do you have more code sample in order to help you? We do not have the problem with big html form. A code sample will help us to understand your problem.

**Comment by Greg-Johns** [comment]
Hi @guillaume-chervet Thanks for getting back. Here's the basics of the component
```
return (
    <div css={container}>
        <OidcSecure>
            <Input
                placeholder="Search..."
                onChange={(e) => setSearchValue(e.target.value)}
                value={searchValue}
            />
          <div>
              {/* content */}
          </div>
      </OidcSecure>
  </div>
);
```
This will cause the input to loose focus after one character input. If I move the <Input> out of the <OidcSecure> tag then input keeps focus and works as expected.

**Comment by guillaume-chervet** [comment]
Thank you for the informations.  We will have to look at this 👍

**Comment by drwaky** [comment]
hey, @guillaume-chervet any update on this? We are having the same error with <OidcSecure> and the inputs, which I think is related to the mount and unmount of the components, React does not follow the input like the previous one, and create a new input, so the focus is lost.

**Comment by guillaume-chervet** [comment]
This problem was too complexe and fixed in the v4.
https://black-rock-0dc6b0d03.1.azurestaticapps.net/

Do you still have it with the v4?

**Comment by guillaume-chervet** [comment]
I am very sorry for the delay. It was hard to fixed it with the previous version.

**Comment by Greg-Johns** [comment]
@guillaume-chervet I'm not working on that project anymore so will go ahead and close the issue.
