### ISSUE TITLE
IE 11 doesn't keep oidcUser

### ISSUE THREAD

**Issue by RichardHpa** [AxaGuilDEv/react-oidc#523]
An app I am updating still has a large amount of uses using IE 11.
I am having an issue with the react-oidc-context module where after I login using the demo identity server, it redirects back to my app alright and all the links you should see when logged in are there but then they disappear going back to the original apps state and you only see the login button. The Access token is still refreshing and ever so often it would flicker to show me the links but then again go back to the logged out state

I have created a very basic project to show the issue and have tried to follow the demo files provided as much as possible.
https://github.com/RichardHpa/react-oidc-ie11-issue

## Steps to Reproduce
Just open the app in IE11 and login. Once it has redirected back you should see the issue.

**Comment by guillaume-chervet** [comment]
Hi @RichardHpa , i will try it tomorrow. We does not have your problem in production.

**Comment by RichardHpa** [comment]
Just did 2 tests on two different machines, 1 had the same issue while the other worked perfectly fine

**Comment by guillaume-chervet** [comment]
Do you have more logs, or more informations about what happening?

**Comment by RichardHpa** [comment]
No console errors and nothing odd in the logs which makes it hard to figure out whats wrong
The only thing I can see the user doesnt get saved into oidcUser. When I do an if statement to check if there is a user it always returns false, even though the timer for the access token is still running

**Comment by guillaume-chervet** [comment]
It should come from internal policies applied to your browser (may be url size rules, etc.).

For debugging, you can redirect consol.log to a div.innerHtml in the page (it is what I do in worst cases).

**Comment by RichardHpa** [comment]
Nothing out of the ordinary pops up, but I have found out it has something to do with localhost. It works fine in production but when I run it in dev through localhost it doesnt. If I create an alias then it works.

**Comment by guillaume-chervet** [comment]
Hi @RichardHpa do you still need ie11 for version 4 of the library? https://www.npmjs.com/package/@axa-fr/react-oidc-context

I think it should work but I have no way to test it.

**Comment by RichardHpa** [comment]
I dont actually need it anymore but I can test it out for you.
Since microsoft has deprecated IE its probably not even worth trying to fix it anymore anyway

**Comment by guillaume-chervet** [comment]
Thank you for your feedback. It seems to work in v4. I close the issue.
