### ISSUE TITLE
Refresh Token causes rerender

### ISSUE THREAD

**Issue by rpetigny** [AxaGuilDEv/react-oidc#527]
### Issue and Steps to Reproduce

Access token is correctly refreshed when expired.
But if we have a context which expose an overrided version of fetch, the user inside is never update.

### Versions

All

#### Expected

Fetch should get access_token from UserManager, not from its props

#### Actual

Fetch gets access_token from props, which are provided by a contextProvider

**Comment by guillaume-chervet** [comment]
Hi @rpetigny , i do not understand your problem. Do you have sample of code?

**Comment by guillaume-chervet** [comment]
This is fixed in v4. https://www.npmjs.com/package/@axa-fr/react-oidc-context
Hooks have been splitted in order to solve that problem.
