### ISSUE TITLE
react-oidc-context and silent renew with refreshToken causes "page reset"

### ISSUE THREAD

**Issue by robinsmedberg** [AxaGuilDEv/react-oidc#540]
### Issue and Steps to Reproduce

When using a refreshToken and automatic silent renew the child tree below AuthenticationContext.provider is reset.

When using a refreshToken the oidc-client will not use an IFrame.
And my guess is core/src/routes/OidcRoutes uses the silentCallbackPath and the child tree is lost.

### Versions

"@axa-fr/react-oidc-context": "3.1.6"
"oidc-client": "1.10.1"

#### Expected

Real silent renew not affecting the child tree below the AuthenticationContext.provider

#### Actual

Page is reloaded

**Comment by robinsmedberg** [comment]
Now I saw https://github.com/AxaGuilDEv/react-oidc/issues/527

I'm still curious about my assumption about the combination of not updating the tokens in an IFrame and the OidcRoutes though...

**Comment by Ansalibrahim** [comment]
@robinsmedberg Did the issue resolved for you?
I think I have the same problem. Can you share anything that could solve the issue?

**Comment by engru** [comment]
we have the same problem,
but i solved by using   automaticSilentRenew = true
