### ISSUE TITLE
wrapping a component in OidcSecure causes component state to be reset when refreshing token

### ISSUE THREAD

**Issue by robinsmedberg** [AxaGuilDEv/react-oidc#541]
### Issue and Steps to Reproduce

I have wrapped secure components in OidcSecure and when silent renew refreshes token then something causes the component to unmount

### Versions
"@axa-fr/react-oidc-context": "3.1.6",
"oidc-client": "1.10.1",

**Comment by robinsmedberg** [comment]
What is the purpose of this line in OidcSecure?

const WrappedComponent = useMemo(() => () => <>{children}</>, [children]); 

Seems it will store the Original state of the children and on a refresh use that version.

**Comment by bohdanzhylavskyi** [comment]
@robinsmedberg Hi, did you find way to work around it?

**Comment by robinsmedberg** [comment]
@bohdanzhylavskyi Yes, I don't remember which lines... :) pasting the full code

import { AuthenticationContext } from "@axa-fr/react-oidc-context";
import {
  authenticateUser,
  Authenticating,
  getUserManager,
  isRequireAuthentication,
  oidcLog,
  ReactOidcHistory,
  withRouter,
} from "@axa-fr/react-oidc-core";
import React, {
  ComponentType,
  PropsWithChildren,
  useContext,
  useEffect,
  useMemo,
} from "react";

type OidcComponentProps = PropsWithChildren<{
  location: Location;
  history: ReactOidcHistory;
  authenticateUserInternal: typeof authenticateUser;
  getUserManagerInternal: typeof getUserManager;
  isRequireAuthenticationInternal: typeof isRequireAuthentication;
  AuthenticatingInternal: typeof Authenticating;
}>;

export const OidcSecureWithInjectedFunctions = ({
  children,
  location,
  history,
  authenticateUserInternal,
  getUserManagerInternal,
  isRequireAuthenticationInternal,
  AuthenticatingInternal,
}: OidcComponentProps) => {
  const { authenticating, isEnabled, oidcUser, isLoggingOut } = useContext(
    AuthenticationContext
  );
  const userManager = getUserManagerInternal();

  useEffect(() => {
    oidcLog.info("Protection : ", isEnabled);
    if (isEnabled && !isLoggingOut) {
      oidcLog.info("Protected component mounted");
      authenticateUserInternal(userManager, location, history)();
    }
    return () => {
      oidcLog.info("Protected component unmounted");
    };
  }, [
    isEnabled,
    authenticateUserInternal,
    userManager,
    location,
    history,
    isLoggingOut,
  ]);

  const requiredAuth = useMemo(
    () => isRequireAuthenticationInternal(oidcUser as any, false) && isEnabled,
    [isEnabled, isRequireAuthenticationInternal, oidcUser]
  );

  const AuthenticatingComponent = authenticating || AuthenticatingInternal;
  return requiredAuth ? <AuthenticatingComponent /> : children;
};

const withServices = (WrappedComponent: any, Services: any) => (props: any) => {
  return <WrappedComponent {...props} {...Services} />;
};

const OidcSecure = withRouter(
  withServices(OidcSecureWithInjectedFunctions, {
    AuthenticatingInternal: Authenticating,
    authenticateUserInternal: authenticateUser,
    getUserManagerInternal: getUserManager,
    isRequireAuthenticationInternal: isRequireAuthentication,
  })
);

export const withOidcSecure = (WrappedComponent: ComponentType) => (
  props: PropsWithChildren<any>
) => (
  <OidcSecure>
    <WrappedComponent {...props} />
  </OidcSecure>
);

export default OidcSecure;

**Comment by bohdanzhylavskyi** [comment]
@robinsmedberg Thanks)

**Comment by thewendigoot** [comment]
Hello,

We used with my team your amazing component. Help us very well :) but unfortunately, we have the same issue, do you know if there is any fix which come for the next release and when ?

Thx a lot

**Comment by guillaume-chervet** [comment]
Very sorry for the delay.

**Comment by guillaume-chervet** [comment]
I close the issue, feel free to reopen it if you need!
