### ISSUE TITLE
Investigate to find why OIDC has to be befor Router

### ISSUE THREAD

**Issue by youf-olivier** [AxaGuilDEv/react-oidc#548]
See PR #426 

IMO it is an issue.

**Comment by DaleyKD** [comment]
Please find a way to have it so that OIDC can utilize the BrowserRouter.  For example, you aren't taking into account me setting `basepath`, so I can't use **your** OIDC routes ('/authentication/not-authorized') when doing `history.push()`.

**Comment by guillaume-chervet** [comment]
This is fixed in v4  you can set it before or after it works!
