### ISSUE TITLE
How to refresh tokens, for example when user permissions changed?

### ISSUE THREAD

**Issue by bohdanzhylavskyi** [AxaGuilDEv/react-oidc#549]

**Comment by guillaume-chervet** [comment]
With v4 it is easy to add that fonctionnality. I amnonterrested to know For which use case do you need that kind of functionality?
Very sorry for the very long delay.

**Comment by guillaume-chervet** [comment]
https://black-rock-0dc6b0d03.1.azurestaticapps.net/

In v4 you can connect to multiple config in order to get more scope for example.

Is it what you need? Or is it something else?

**Comment by guillaume-chervet** [comment]
I think that Pullrequest answer to yout need https://github.com/AxaGuilDEv/react-oidc/pull/778

**Comment by guillaume-chervet** [comment]
Hi @bohdanzhylavskyi , it work now in very 6. I close the issue because it is quite old. Thank you very much.
