### ISSUE TITLE
[Documentation] add how to switch on memory storage for the tokens

### ISSUE THREAD

**Issue by guillaume-chervet** [AxaGuilDEv/react-oidc#551]
for OIDC Context add how to switch on memory storage for the tokens

**Comment by DaleyKD** [comment]
I'd also be curious how to use localStorage.

**Comment by youf-olivier** [comment]
Thanks for the issue, sorry we were a bit overwhelmed. I'll look all the issues soon

**Comment by DanCanCodeIt** [comment]
> for OIDC Context add how to switch on memory storage for the tokens

I wrapped `window.localstorage` in a class then passed into the AuthenticationProvider's UserStore param.
```
class LocalStorage {
  constructor() {
    return window.localStorage;
  }
}
 <AuthenticationProvider
          configuration={oidcConfiguration}
          loggerLevel={oidcLog.DEBUG}
          UserStore={LocalStorage}
/>
```

**Comment by linwilai918** [comment]
class localstorage {
  constructor() {
    return window.localstorage;
  }
}
 <authenticationprovider
          configuration={oidcconfiguration}
          loggerlevel={oidclog.debug}
          userstore={localstorage}
/>
lin

**Comment by guillaume-chervet** [comment]
Thank you all, I close the issue. The v5 documentation explain how to switch between local storage and service worker storage.
