### ISSUE TITLE
SilentCallback.component.tsx Bug: OIDC Client Error 'No state in response'

### ISSUE THREAD

**Issue by DaleyKD** [AxaGuilDEv/react-oidc#554]
### Issue and Steps to Reproduce
Trying to use the Silent Callback, and when I have the OIDC logger set to DEBUG, I see an error about "No state in response."

After looking through your code, I can't find a way to override the SilentCallback.component (that's an enhancement request) in order to test my theory, so I had to fully bypass the React control.

If we look at your code here: https://github.com/AxaGuilDEv/react-oidc/blob/06ca2dd66e06bcc485c8e8cd57cdcff2da6ab6a5/packages/core/src/callbacks/SilentCallback.component.tsx#L11, we see that you're instantiating up a `new UserManager` without the same configuration as what we use to send the request.

To test my theory, I used a plain .html with a script on it. 
```js
    <script src="https://cdnjs.cloudflare.com/ajax/libs/oidc-client/1.10.1/oidc-client.min.js" integrity="sha512-J+l1VucK7pEidJ+w1fYQfo0Yq4LGkTXwKQ3w9Y9/c4O2NoQe+DgiIwvh2ocNVv4ost5H6W4uhy1K2sw5tWO+ew==" crossorigin="anonymous"></script>
    <script>
        var configuration = Object.assign(window.myConfig.oidc, {
            userStore: new Oidc.WebStorageStateStore({ store: window.localStorage }),
            automaticSilentRenew: true,
            filterProtocolClaims: true,
            loadUserInfo: true
        });
        var mgr = new Oidc.UserManager(configuration);
        mgr.signinSilentCallback().then(user => {
            console.log("Success????!!");
        }).catch(reason => {
            debugger;
        });
    </script>
```
And this works perfectly.

### Versions
"@axa-fr/react-oidc-context": "^3.1.6",

### Additional Details

- Installed packages:

**Comment by DaleyKD** [comment]
Further investigation shows that it's not because it's a different configuration.  I've tried it with both:
`new Oidc.UserManager().signinSilentCallback();` and `new Oidc.UserManager({}).signinSilentCallback();` and they both work outside of the SilentCallback.component.tsx.  However, if I try to use your SilentCallback.componen.tsx, it errors out every time.

**Comment by youf-olivier** [comment]
Thanks for the issue, sorry we were a bit overwhelmed. I'll look all the issues soon

**Comment by DaleyKD** [comment]
I appreciate it, @youf-olivier .  I'm sorry that you've been overwhelmed.  It's the holidays, and I pray that you get to enjoy them!

We're trying to use your library for a product for use in Microsoft Teams, and for the most part, it works, but we've had to work around quite a few things to make it work for our needs.  I'd love to see it tighten up a bit more so these workarounds are as necessary.

Merry Christmas to you!

**Comment by tielushko** [comment]
Are there any updates for this issue?

**Comment by DaleyKD** [comment]
I honestly thought this project was dead. 💀  If I ever get back to my project that uses this, I may have to look elsewhere.

**Comment by tielushko** [comment]
Sadly, the entire oidc-client-js may soon be dead as well. The repo was recently archived.

**Comment by DaleyKD** [comment]
Not surprising.  The guys who did Identity Server have started a new profit company.  https://blog.duendesoftware.com/

**Comment by guillaume-chervet** [comment]
New v4 of react oidc use app auth js is simpler and solve this bug.

**Comment by guillaume-chervet** [comment]
Thank you for the issue. I close it. Feel free to reopen it if you have the bug with the version 4.
