### ISSUE TITLE
Redux package: access to login & logout functions

### ISSUE THREAD

**Issue by NicoLaval** [AxaGuilDEv/react-oidc#557]
We currently have not access to login & logout function into Redux package.
Does it make sens to expose react-oicd actions to do that? (it's already possible into Context package)

**Comment by NicoLaval** [comment]
`authenticating` props for OidcProvider is too exposed by context package but not by redux package.

Ta wrap it, is it possible to obtain:
- `authenticating` props into redux Oidc provider
- login & logout functions into Oidc entry of redux store
?

Thxs

**Comment by guillaume-chervet** [comment]
Thank you for the issue, yes it should be exposed. I do not have time to work on the project for the moment @oyouf ?

**Comment by honzahruby** [comment]
Any update on this? 🙏

**Comment by guillaume-chervet** [comment]
In v4 version you can switch to oidc context which in fact does not use any react context and is compatible with redux.

Login and logout are available.

**Comment by guillaume-chervet** [comment]
I close the issue. It is fixed in v4, feel free to reopen it if you need.
