### ISSUE TITLE
How to use with resource owner password flow?

### ISSUE THREAD

**Issue by Devwulf** [AxaGuilDEv/react-oidc#569]
Hello! I can use this perfectly fine with implicit flow, but how do I use this with the resource owner password flow (i.e sending the username and password details in the request body to the auth server)? Thanks!

Edit: I'm using the react-oidc-context, if it makes any difference.

**Comment by guillaume-chervet** [comment]
I @Devwulf, do you have detail on your use case? password flow on the client side does not seem to be very secure.

**Comment by Devwulf** [comment]
> I @Devwulf, do you have detail on your use case? password flow on the client side does not seem to be very secure.

I want to have one central auth server for my web apps, but I also want custom login pages for each of my web apps instead of using the auth server's login page. Apparently, I can use the password flow to take in the login details on the client web app and send it to the server. 

If there's a better alternative to password flow that would provide the same capabilities I mentioned, I would love to hear it!

**Comment by guillaume-chervet** [comment]
I think that using server like https://identityserver.io/ you should be able to bring a custom login page and keep a secure flow like code with pkce.

**Comment by youf-olivier** [comment]
This kind of flow is not supported by oidc client : https://github.com/IdentityModel/oidc-client-js/issues/1103

So we neither :)
