### ISSUE TITLE
User Cannot be Logged Out and Sign In Redirect

### ISSUE THREAD

**Issue by allidoisace** [AxaGuilDEv/react-oidc#584]
### Issue and Steps to Reproduce

Unfortunately, there is no configuration for `end_session_endpoint` for when an authority doesn't have a logout mechanism. Therefore, you can never logout due to an error thrown when the context's `logout()` is invoked. How can I make the user logout?

Another issue is that redirecting after a login cannot be configured to another page. If I specify a redirect within the component, the user is then authenticated again since the route they are being redirected to is protected. Any way to handle this?

**Comment by guillaume-chervet** [comment]
I @allidoisace, thank you for your issue. Your authority does not implement logout. What is the behavior you expect to have on the client side when you logout?

**Comment by guillaume-chervet** [comment]
Hi @allidoisace , i think you need is resolved  it. I close the issue. Feel free to reopen it if you need!
