### ISSUE TITLE
Handle issues when token is refreshed

### ISSUE THREAD

**Issue by NicoLaval** [AxaGuilDEv/react-oidc#589]
### Issue and Steps to Reproduce

After login, if a refresh token fail, for any reason, `authenticating` component (declared into `Provider` props) is indefinitely active while console expose the error below.

Is there a way, ideally at Provider level, to throw an Error component?

(I have already try with the `sessionLostComponent` props of `Provider` component, unsuccessfully)

### Versions

"@axa-fr/react-oidc-context": "^3.1.6"

### Screenshots

![oidc](https://user-images.githubusercontent.com/30119477/109261604-5701c900-7800-11eb-9f08-c68a2b1064f3.png)

**Comment by guillaume-chervet** [comment]
I think it is a bug . sessionLostComponent should be triggered. Are you able to reproduce the bug via team on monday?

**Comment by youf-olivier** [comment]
I'm on it. 

The problem is deeper than a simple bug. Oidc Client do nothing when a refreshToken request crashes. and it happens when the refresh token expires.

We have to make a signin when it happens.

**Comment by guillaume-chervet** [comment]
@youf-olivier, I have created sessionLostComponent for that use case, it is a very difficult case to test.

**Comment by youf-olivier** [comment]
You don't have it. It's an other problem.

**Comment by youf-olivier** [comment]
But I could use it for the current PR

**Comment by NicoLaval** [comment]
Sorry for the delay.

Thank you for taking the time to look and fix this bug.

I built the package from the `fix/refreshToken` branch and used the bundle in my client project: bug seems to be fixed.

Hope it will be released soon.

**Comment by VysockyStan** [comment]
Hi, any updates on this?
It causes me a lot of problems.
Would be great if it is fixed.
thank you

**Comment by VysockyStan** [comment]
I like this package very much and I really want to proceed with it, but I need to handle this case.
Is there a way to catch token refresh programatically?
If so I could implement a workaround for this case

**Comment by guillaume-chervet** [comment]
New v4 fix that problem !

**Comment by guillaume-chervet** [comment]
https://www.npmjs.com/package/@axa-fr/react-oidc-context

**Comment by guillaume-chervet** [comment]
I close the pullrequest. The v4 ans v5 version was rewritten is order to fix that kind of issue. The library is simpler ligther ans without that issue.

Thank you very much for your help. Feel free to reopen it if you need!
