### ISSUE TITLE
Using prompt:login within OIDC Authentication Request

### ISSUE THREAD

**Issue by cburkins** [AxaGuilDEv/react-oidc#595]
The OIDC 1.0 specification allows for the parameter "prompt", with possible values of "none", "login", or "consent".   It's rather handy when you want to request the OIDC authentication provider to force a login (e.g. prompt:login).  

For reference, the spec I'm reading is here: https://openid.net/specs/openid-connect-core-1_0.html

Search for "prompt", it's in section 3.1.2.1.  

Within this handy React framework, is there a way to communicate a desire into the oidc-client to pass through a prompt:login parameter during the authentication call ?

**Comment by cburkins** [comment]
The reason this is useful to me (and might be useful to others):  Feels like there are some bigger OIDC providers that don't provide an "end_session_enpoint" in their .well_known configuration, so you can't trigger a logout.   Without have a logout, it would be nice to be able to use a "prompt:login" to force real authentication.  This isn't urgent.

**Comment by guillaume-chervet** [comment]
Hi, i think it is possible to do thath is the last v5 version by using extra parameters.
