### ISSUE TITLE
Cannot read file tsconfig on fresh CRA with react-oidc-context

### ISSUE THREAD

**Issue by chr0m1ng** [AxaGuilDEv/react-oidc#597]
### Issue and Steps to Reproduce

I have created a brand new app with CRA (JS not TS) and just added the package with `npm install @axa-fr/react-oidc-context --save` and I'm getting the following issue:

`Cannot read file 'D:/source/repos/take/install-plugins-marketplace/node_modules/tsconfig.json'.`

My project is in JS but seems like `tsconfig.json` of `react-oidc-context` is trying to extend the `tsconfig.json` of the `node_modules` folder? 

### Versions

```json
{
    "@axa-fr/react-oidc-context": "^3.1.6",
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.5",
    "@testing-library/user-event": "^12.8.3",
    "core-js": "^3.9.1",
    "oidc-client": "^1.11.5",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.1.1"
  }
```

### Screenshots

![image](https://user-images.githubusercontent.com/11679657/111676157-aa15dd00-87fc-11eb-96d3-6efe4ebac730.png)

#### Expected
No errors in fresh projects
#### Actual
Package is trying to fetch a file that doesn't exists.

### Additional Details

- Installed packages: `@axa-fr/react-oidc-context`, `oidc-client`

**Comment by Mastanka** [comment]
I'm getting same error :-/ @chr0m1ng did you manage to solve it? Thanks a lot

**Comment by chr0m1ng** [comment]
> I'm getting same error :-/ @chr0m1ng did you manage to solve it? Thanks a lot

No, I didn’t. 👎

**Comment by guillaume-chervet** [comment]
Do you still have the problem with the v4 version ?

**Comment by guillaume-chervet** [comment]
Thank you very much for that issue. Very sorry for the delay.

**Comment by guillaume-chervet** [comment]
I close the issue feel free to reopen it if needed.
