### ISSUE TITLE
Example doesn't work on build

### ISSUE THREAD

**Issue by chr0m1ng** [AxaGuilDEv/react-oidc#599]
The `react-oidc-context` example just doesn't work when you build and serve the app, I'm getting 404 on the `/authentication/callback` url.

This works fine when using `npm start` but if you do `npm run build && serve -s build/` to serve your app in production the login always return 404 (not found) page, even in this example https://github.com/AxaGuilDEv/react-oidc/tree/master/examples/context

**Comment by guillaume-chervet** [comment]
Thank you very much for your issue. V4 is a lot more simple and demo is included in the library. It will be easier to maintain.

**Comment by guillaume-chervet** [comment]
In v4 the demo is deployed on each pull request and merge on master. Thab you very much for your feedback. 

Take a look https://black-rock-0dc6b0d03.1.azurestaticapps.net/

I close the pr feel free to reopen it.
