### ISSUE TITLE
(Build): Unable to NPM install master -- dns fails for afa-nrepo.azure-paas.intraxa in package-lock.json 

### ISSUE THREAD

**Issue by jafin** [AxaGuilDEv/react-oidc#605]
### Issue and Steps to Reproduce

Unable to git pull repo and build
error:
```
npm ERR! errno ENOTFOUND
npm ERR! network request to https://afa-nrepo.azure-paas.intraxa/repository/npmjs-group/jest-docblock/-/jest-docblock-21.2.0.tgz failed, reason: getaddrinfo ENOTFOUND afa-nrepo.azure-paas.intraxa
```

### Versions

- git master (#578 )
- NPM 7.8.0
- Windows

#### Expected

`NPM INSTALL` completes successfully

#### Actual

NPM Error, unresolved host.

### Additional Details

Deleting the `package-lock.json` and executing `npm i --legacy-peer-deps` works

**Comment by guillaume-chervet** [comment]
Thank you very much @jafin for your issue and this is fixed in v4. Very sorry for the delay!
