### ISSUE TITLE
English locale support

### ISSUE THREAD

**Issue by michaelsizonenko** [AxaGuilDEv/react-oidc#607]
### Issue and Steps to Reproduce

This library supports French texts only. 
What's the way to have English texts?
Monkey patch? Fork the repository?

### Versions
3.1.6.

### Screenshots
![image](https://user-images.githubusercontent.com/51369289/114849132-2396f000-9de8-11eb-811b-983a87f062ec.png)

### Additional Details

- Installed packages:

**Comment by johannes-darms** [comment]
You can pass custom Components to override the sample components with french text. The original are stored here `src/default-component/SessionLost.component.tsx`. All components except the `SessionLost` contain only layout and no logic. Hence, exchanging them is straight forward: 

```
<AuthenticationProvider
        configuration={oidcConfiguration}
        callbackComponentOverride={()=>{return(<h1>Callback</h1>)}}
        notAuthenticated={()=>{return(<h1>Not Authenticated</h1>)}}
        notAuthorized={()=>{return(<h1>Not Authorized</h1>)}}
        authenticating={()=>{return(<h1>Authentication in process</h1>)}} >
```

**Comment by michaelsizonenko** [comment]
Nope. I found another way. add replace-french.js script to build process. Got the minified .js file and replace French strings to needed English

**Comment by SamSeabourn** [comment]
@guillaume-chervet  @johannes-darms Thanks guys, works great.
