### ISSUE TITLE
Split layout and logic of the `SessionLost` component similar to the `CallBack` component.

### ISSUE THREAD

**Issue by johannes-darms** [AxaGuilDEv/react-oidc#610]
### Issue and Steps to Reproduce

I'd like to exchange the default `SessionLost` Component with a custom one. However, this is not as easy as with the other components as  this one contains logic and layout code. It would be great to split layout and logic of the `SessionLost` component similar to the `CallBack` component.

### Versions
master

**Comment by guillaume-chervet** [comment]
Thank you for the issue, we have to add this feature.

**Comment by guillaume-chervet** [comment]
Hi, thank you very much for your issue and very sorry for the delay. In v4 all components are customisable in the same way. I may traduce it in english.

**Comment by guillaume-chervet** [comment]
Hi, i close the issue, feel free to reopen it if you need.
