### ISSUE TITLE
How to Implement logout?

### ISSUE THREAD

**Issue by MadikMayCry** [AxaGuilDEv/react-oidc#611]
Can you show how to implement logout in redux

config.js

    config: {
        client_id: "client_id",
        redirect_uri: "http://localhost:3000/login_complete",
        response_type: "id_token token",
        post_logout_redirect_uri: "http://localhost:3000/logout",
        scope: "openid profile bpmnapi frontapi account_information roles email",
        authority: "https://localhost:5002",
        silent_redirect_uri: 'http://localhost:3000/login_complete"',
        response_mode: "fragment",
        userStore: new Oidc.WebStorageStateStore({
          store: window.localStorage,
        }),
      },

index.js

    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <BrowserRouter>
          <Oidc
            store={store}
            configuration={authenticationConfig.config}
            isEnabled={isEnabled}
            callbackComponentOverride={ComponentOverride}
          >
            <App />
            <Toaster />
          </Oidc>
        </BrowserRouter>
      </PersistGate>
    </Provider>

App.js

    const Protected = ({ children, ...props }) => (
      <OidcSecure isEnabled={configuration.isEnabled} authenticating={AuthRedirectComponent} {...props}>
        {children}
      </OidcSecure>
    );

Do i have to create userManager?

**Comment by MadikMayCry** [comment]
It also recreates user in localstorage on every page refresh.

![Снимок экрана от 2021-04-25 15-29-59](https://user-images.githubusercontent.com/34336498/115988374-3de87f00-a5db-11eb-8af9-07e93643f51b.png)

**Comment by Buried-Love** [comment]
How did you solve it

**Comment by MEnenko** [comment]
Is there a solution to this problem? I have a similar situation. Help me solve it
