### ISSUE TITLE
Not working properly with redux when switching on localstorage

### ISSUE THREAD

**Issue by MadikMayCry** [AxaGuilDEv/react-oidc#612]
### Issue and Steps to Reproduce
By default it saves auth response to sessionstorage, but when you open in new tab, user is null in redux

### Screenshots
![Снимок экрана от 2021-04-26 05-07-24](https://user-images.githubusercontent.com/34336498/116012639-77f26900-a64d-11eb-9612-41e7de7a21d2.png)

#### Expected
Save to Localstorage once

#### Actual
Saving non-stop after token expires

- Installed packages:
- "@axa-fr/react-oidc-redux": "^3.1.6",
- "@axa-fr/react-oidc-redux-fetch": "^3.1.6",
- "oidc-client": "^1.11.5",
- "redux-oidc": "^4.0.0-beta1",

**Comment by nenjamin2405** [comment]
I'm facing the same issue in my project when I start to switch to Local Storage. Have you resolved it @MadikMayCry ? Hi @guillaume-chervet, do we have a solution for this bug?

**Comment by guillaume-chervet** [comment]
I cannot reproduce it. Do you have specific rules on your browser? Which Browser are you using?

**Comment by guillaume-chervet** [comment]
In v4 we removed the redux version.
We use @axa-fr/react-oidc-context with redux that does not use any data context in fact and is simpler to use.

**Comment by guillaume-chervet** [comment]
By default it use sessionStorage or serviceWorker storage for more security. local storage is not used any more.

**Comment by guillaume-chervet** [comment]
Hi, i close the pull request. React context v5 is fully compatible with redux and does not use any context. It fix the issue. Feel free to reopen the pullrequest if you need.
