### ISSUE TITLE
Callback URL not removed from history. Error if user goes back

### ISSUE THREAD

**Issue by smariano88** [AxaGuilDEv/react-oidc#627]
### Issue and Steps to Reproduce
**Summary**
After logging in, `/authentication/callback?code...` url is not removed from history. This allows users to go back and a not-authenticated page is shown.

**Steps**
1. Git clone, npm install and start this demo: https://github.com/AxaGuilDEv/react-oidc/tree/master/examples/context
2. Login
3. Click back button

### Versions
    "@axa-fr/react-oidc-context": "^3.1.6",
    "@axa-fr/react-oidc-context-fetch": "^3.1.6",
    "oidc-client": "^1.10.1",

### Screenshots
History right after logging in (but without pressing the back button)
![image](https://user-images.githubusercontent.com/62569627/119191155-a993ff80-ba54-11eb-8985-91f112cc0f82.png)
![image](https://user-images.githubusercontent.com/62569627/119191258-c3354700-ba54-11eb-8db4-88f269517075.png)

#### Expected
History without callback entry

#### Actual
History with callback entry

### Additional Details
After taking a look at the source code I found this line:
https://github.com/AxaGuilDEv/react-oidc/blob/c785f2d6cd92d9380c0c3ec99e01bb61f7ec2fcd/packages/core/src/routes/withRouter.tsx#L54
Changing it to
`windowInternal.history.replaceState({ key, state }, null, url);`
seems to do the trick, but I'm not sure about the implications of making this change to other parts of the app

### Installed packages:
Same posted above

**Comment by guillaume-chervet** [comment]
Yes I'am looking at this one. I'am trying to find a solution that work on every use case.
It is a bit tricky because, some oicd provider use internaly many callback in order to authenticate.

**Comment by smariano88** [comment]
What about providing a way of overriding this callback function? 
https://github.com/AxaGuilDEv/react-oidc/blob/c785f2d6cd92d9380c0c3ec99e01bb61f7ec2fcd/packages/context/src/Callback/Callback.container.tsx#L6

But keeping the default behaviour if no callback is provided. That way every consumer could implement whatever they want

**Comment by guillaume-chervet** [comment]
Yes it is a good idea

**Comment by guillaume-chervet** [comment]
This issues is fixed in the comming v4 =>  https://www.npmjs.com/package/@axa-fr/react-oidc-context

**Comment by guillaume-chervet** [comment]
You can give à v4 try here https://black-rock-0dc6b0d03.1.azurestaticapps.net/

**Comment by guillaume-chervet** [comment]
Do you still have the issue with v4? May we close the issu3?

**Comment by guillaume-chervet** [comment]
I close the issue, feel free to reopen it. It sould work fine in v4.
https://black-rock-0dc6b0d03.1.azurestaticapps.net/
Thank you very much for your feeback and help.

**Comment by smariano88** [comment]
Apologies for the delayed response. Unfortunately I left the place where we were implementing this, so I no longer have access to that code.

**Comment by emmanuel-jln-cds** [comment]
Hello @guillaume-chervet , I think that this issue is still there in the latest react-oidc demo.
We use it in our code but even in the demo if you run it locally in Chrome, you'll still be able to navigate back to http://localhost:5173/authentication/callback?...
The issue we ran into with our production code is that Chrome considers it to be a navigated to URL and when autocompleting the url in the navbar, this one is shown. If the user clicks on it then they will automatically have an error page.
I hope my message was clear and you'll receive it well, have a nice day.
