### ISSUE TITLE
withAuthentication HOC triggers too many rerender of wrapped component

### ISSUE THREAD

**Issue by JLou** [AxaGuilDEv/react-oidc#643]
### Issue and Steps to Reproduce

When using `withAuthentication` from `@axa-fr/react-oidc-context-fetch`, the component wrapped will rerender too many times.

In 3.1.6 with my reproduction code I get "toto 2", and in "3.1.7" I get "toto 6"

3.1.6:
![image](https://user-images.githubusercontent.com/183460/123611379-d7155b00-d801-11eb-9c6d-26cee39c93b3.png)

3.1.7:
![image](https://user-images.githubusercontent.com/183460/123611420-e09ec300-d801-11eb-8726-89a3827a4258.png)

```
git clone https://github.com/JLou/repro-bug-react-oidc.git
cd repro-bug-react-oidc
npm i
npm start
```

### Versions
3.1.7 & below

### Screenshots

![image](https://user-images.githubusercontent.com/183460/123611087-84d43a00-d801-11eb-8c40-30ad7d7a268f.png)

#### Expected

fetch should not change during the lifespan of the app, and should definitely not trigger a rerender of my wrapped component

#### Actual

it does

### Additional Details

- Installed packages: 
"@axa-fr/react-oidc-context": "3.1.7",
"@axa-fr/react-oidc-context-fetch": "3.1.7",
"@axa-fr/react-oidc-core": "3.1.7",
"@axa-fr/react-oidc-fetch-core": "3.1.7",

**Comment by guillaume-chervet** [comment]
The rerender problem is fixed in v4 by sliting  hooks and by removing data duplication inside react.

**Comment by guillaume-chervet** [comment]
I close the issue, thank you for it. The v4 fixe it. Feel free to re-open an issue if you need it.
