### ISSUE TITLE
`openid-configuration` Repeat request

### ISSUE THREAD

**Issue by Buried-Love** [AxaGuilDEv/react-oidc#644]
When I log in, I log in successfully for the first time,But the VM requests again`openid-configuration`. Cause me to report an error :
ResponseValidator._processSigninParams: Response was error login_required
`openid-configuration`  The first request was made by `oidc-client.main.js`  issue.  The second request was made by VM.

please help me...  thank you!

**Comment by guillaume-chervet** [comment]
Sorry, we have a bug in version 3.1.7, you may retrograde to 3.1.6. It should work better.

**Comment by Buried-Love** [comment]
> Sorry, we have a bug in version 3.1.7, you may retrograde to 3.1.6. It should work better.

Thank you for your reply !  It's the same problem after switching versions.

**Comment by Buried-Love** [comment]
Strangely enough: After success It will be requested again `openid`.  It should not have asked

**Comment by Buried-Love** [comment]
![1625564072(1)](https://user-images.githubusercontent.com/52312490/124578206-94e2be00-de80-11eb-8660-50c0c812c1cb.jpg)

**Comment by guillaume-chervet** [comment]
Do you have the problem with exemples on that repo?

**Comment by Ansalibrahim** [comment]
I am using v3.1.6. It occurs in the `incognito` mode of chrome. And it happens in example too (context).

**Comment by Ansalibrahim** [comment]
I can confirm that this happens in all versions` @3.1.+`.

**Comment by Ansalibrahim** [comment]
The error is occurring inside the dependency `oidc-client` and it is deprecated 🤦‍♂️

**Comment by jafin** [comment]
@Ansalibrahim  yes refer to #641  re deprecation

**Comment by Ansalibrahim** [comment]
@jafin Have you found any workarounds or anything of that sort?

**Comment by Ansalibrahim** [comment]
<img width="820" alt="Screenshot 2021-09-15 at 9 34 53 AM" src="https://user-images.githubusercontent.com/13623687/133368886-7c17b8c6-3f5f-47ad-a88f-7f0a0b162bbe.png">
Here is the available log... just before this log, I signed in and 2 seconds later I got signed out.

**Comment by Ansalibrahim** [comment]
@Buried-Love Have you found any solutions? 

@guillaume-chervet Could you help to workaround the issue?

**Comment by robertmadril** [comment]
Hello,

This issue was encountered while utilizing the HOC implementation of OidcSecure in react-oidc-context. The same logging output as described in previous posts were encountered while on version 3.1.6 and 3.1.7.

In order to bypass this, custom auth logic was implemented in the application which calls for the user via userManager.getUser() and determines the authentication route utilizing the login() functionality exposed by the useReactOidc hook exposed from the library.

However, please inform if anyone else has found an effective solution without having to use custom logic in the application code.

**Comment by allemas** [comment]
Hello @robertmadril  :) 

Could you share an example?  I'm afraid to do this wrong.

**Comment by guillaume-chervet** [comment]
The coming v4 will fix this.

**Comment by allemas** [comment]
How can we help you to do it?  Did you open a milestone?

**Comment by guillaume-chervet** [comment]
Thank you for your answer. I do not know what is a Milestone. If you Watt you can cockpit this branch https://github.com/AxaGuilDEv/react-oidc/tree/feature/v4
I have more test ans documentation to do. Some feedback would be great. There are required breaking change.

**Comment by TeckTn** [comment]
Is there any plan to upgrade redux package to v4 also?

**Comment by guillaume-chervet** [comment]
Unfortunately i am not using redux any more in my current projects. I think that the vanilla oidc behind v4 is quite simple to use with redux. It would be great if someone could have the time to write a small redux wrapper.

**Comment by guillaume-chervet** [comment]
v4 context version does not really use context (I will remove it).
It may be already redux compatible.
https://www.npmjs.com/package/@axa-fr/react-oidc-context/v/4.0.0-beta.9

**Comment by guillaume-chervet** [comment]
I close the pull request. Feel free to reopen it if you need it.
Thank you very much. I think the v5 is simpler ans resolve that problem and is full compatible with a react redux architecture.
