### ISSUE TITLE
How to call the oidc provider without the login button

### ISSUE THREAD

**Issue by MTL2000** [AxaGuilDEv/react-oidc#653]
I am running the latest version of context provider example. I am wondering how I can redirect to the oidc provider directly without click on the login button. any example code will be appreciated.

**Comment by guillaume-chervet** [comment]
You just have to display a secured component in order to trigger a login.

**Comment by guillaume-chervet** [comment]
Let me Known if you really need a sample

**Comment by MTL2000** [comment]
I think that I got the idea, Thank you for the help.

**Comment by guillaume-chervet** [comment]
I think we can close this issue.
