### ISSUE TITLE
Blocking/looping script

### ISSUE THREAD

**Issue by ctron** [AxaGuilDEv/react-oidc#665]
### Issue and Steps to Reproduce

Every now and then, I run into a situation where the script blocks, and continuously loops.

Within seconds, I can see `UserManager.getUser` called thousand times:

![image](https://user-images.githubusercontent.com/202474/136922970-c95f3141-6ab1-4fa4-9c1e-859f3ccbde11.png)

### Versions

3.1.7

### Screenshots

See above

#### Expected

Should neither loop nor block.

#### Actual

Blocks/loops.

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Hi @ctron, Which browser are you using?

**Comment by ctron** [comment]
I had issues with both Firefox and Chrome.

**Comment by guillaume-chervet** [comment]
This sould be fixed in the futur v4 soon.

**Comment by allemas** [comment]
Hello !

I have the same kind of issue. In my case, we see the /authorization API endpoint call in a loop.
What is strange is that the behavior seems random depending on the user.

Maybe the browser or the InMemoryStorage are having difficulties.

**Comment by guillaume-chervet** [comment]
Do you still have the problem in v4? 

v4 is pretty stable now
https://www.npmjs.com/package/@axa-fr/react-oidc-context/v/4.0.0-beta.9

**Comment by guillaume-chervet** [comment]
Here you will find a v4 demo https://black-rock-0dc6b0d03.1.azurestaticapps.net/

**Comment by allemas** [comment]
Thanks! 

When I look at it here https://www.npmjs.com/package/@axa-fr/react-oidc-context 
I see v4 ! Is version 4 merged into master and now stable in use?

**Comment by guillaume-chervet** [comment]
It is still young. It works better than v3 in our applications.
And the surface api is very small, it will be essieu to maintain.

**Comment by guillaume-chervet** [comment]
I think it is pretty stable right now.

**Comment by guillaume-chervet** [comment]
I close the issue. Thank you for the issue. Feel free to reopen it.
