### ISSUE TITLE
Pressing back button after success login cause "You are not authenticated" message.

### ISSUE THREAD

**Issue by bumbuledin** [AxaGuilDEv/react-oidc#666]
#### Summary
After success logging in, user is allowed to press back button and then he got message "No matching state found in storage", but as u can see on screenshot user is saved in storage.
I saw this problem is reported in multiple issues, so is there any fix to this ?

### Versions
3.1.7

### Screenshots
![oidc-2](https://user-images.githubusercontent.com/86159204/136932006-4287c86e-a303-455b-bc9f-9ee6ce964459.png)

#### Expected
The user should not have the option to return to the callback page if he is logged successfully. As u can see on screenshot I have user in storage, but I still getting this message after back button.

### Additional Details
```
"dependencies": {
   "@axa-fr/react-oidc-context": "^3.1.7",
   "oidc-client": "^1.11.5",
   "react": "^17.0.2",
},
```

**Comment by piotrkolodziej** [comment]
We're having the same issue!

**Comment by naxis18** [comment]
Hi, 
Any update on that? We are having the same issue.

**Comment by guillaume-chervet** [comment]
This will be fixed soon in thz futur v4

**Comment by guillaume-chervet** [comment]
You can give a try here =>  https://www.npmjs.com/package/@axa-fr/react-oidc-context (there are some breaking change)

**Comment by guillaume-chervet** [comment]
Here you will find a demo https://black-rock-0dc6b0d03.1.azurestaticapps.net/

**Comment by guillaume-chervet** [comment]
I close the pull request. Feel free to reopen it if needed. Thank you very much for that issue fixed in v4.
