### ISSUE TITLE
Session Expired Component Only in French

### ISSUE THREAD

**Issue by jamesmart77** [AxaGuilDEv/react-oidc#689]
### Issue and Steps to Reproduce
Once application has been successfully configured, when the session expires the component rendered is only in French. It would be great to be able to pass in a custom component for this - is there already a way?

### Versions
3.1.7

### Screenshots

![image](https://user-images.githubusercontent.com/29242164/152791177-235fa5c0-3cf0-4c0e-8fb5-c524c56d70d7.png)

**Comment by jamesmart77** [comment]
Thanks so much @guillaume-chervet! Do you know how to simulate a "session lost" instance without having to wait for a session to actually expire? Also, are there props that get passed down to the `sessionLostComponent` parameter? Wondering if there is a `refresh` prop already available that's being passed in or if I have to explicitly call from the custom button...

**Comment by guillaume-chervet** [comment]
It hard to simulate, it is easier with the comming v4 version => https://www.npmjs.com/package/@axa-fr/react-oidc-context

code here => https://github.com/AxaGuilDEv/react-oidc/pull/687
