### ISSUE TITLE
TypeError: Object(...) is not a function when calling useReactOidc method

### ISSUE THREAD

**Issue by chowdhury-najir** [AxaGuilDEv/react-oidc#695]
### Issue and Steps to Reproduce

import { useReactOidc } from '@axa-fr/react-oidc-context';
export const  Header =()=> {
 
  const { isEnabled, login, logout, signinSilent, oidcUser } = useReactOidc();
 
return(
<h1>test </h1>
)

}

I got Type error when importing useReactOidc 

### Additional Details

- Installed packages:
- react-oidc-context

**Comment by guillaume-chervet** [comment]
Hi @chowdhury-najir , thank you for your issue.

You may switch to the new v4 version and new api. It will work better.

**Comment by guillaume-chervet** [comment]
I close the issue, thank you for it. The v4 fixe it. Feel free to re-open an issue if you need it.
