### ISSUE TITLE
fetchWithToken not exported by the lib

### ISSUE THREAD

**Issue by ddecrulle** [AxaGuilDEv/react-oidc#710]
### Is any reason that `fetchWithToken` is not exported by the lib ?

The lib only expose the wrapper `withOidcFetch`. I know that in case of ServiceWorker use, the methode `fetchWithToken` isn't necessary to be exposed. 

But with Firefox it could be usefull. I tried to make my own and to pass token myself but I observe a request sent without token because it's `null` (not yet updated by the lib). 

In the lib code source, I see `export const fetchWithToken` I suspect an export oversight in the index. If there is a raison I'm intrusting to discuss about :)

### Versions
4.0.X

#### Expected

`fetchWithToken` exported 

#### Actual

`fetchWithToken` not exported

**Comment by Mastanka** [comment]
@ddecrulle Did you successfully used **fetchWithToken** in your code? Could you please paste some code example as inspiration for others? 

Thanks a lot!

**Comment by guillaume-chervet** [comment]
Hi @Mastanka, I use it like this =>

I build another HOC with my specific needs for my application.
https://github.com/AxaGuilDEv/ml-cli/blob/master/src/Ml.Cli.WebApp/ClientApp/src/Server/withCustomFetch.js

And I use it when I need it to inject my custom fetch to my componentw.
https://github.com/AxaGuilDEv/ml-cli/blob/168235bd34dc55831f214bd40f302d8ec774dacb/src/Ml.Cli.WebApp/ClientApp/src/Server/Project/Add/New/New.container.js#L228

I think i will add a hook inside react-oidc to return the same fetch.
