### ISSUE TITLE
Redirect path in logout

### ISSUE THREAD

**Issue by tiphaineruy** [AxaGuilDEv/react-oidc#713]
### Issue and Steps to Reproduce

logout doesn't expose a callback uri option:

```js
export declare const useOidc: (configurationName?: string) => {
    login: (callbackPath?: any) => any;
    logout: () => any;
    isLogged: boolean;
};
export declare const useOidcAccessToken: (configurationName?: string) => any;
export declare const useOidcIdToken: (configurationName?: string) => any;
//# sourceMappingURL=ReactOidc.d.ts.map
```

### Versions

4.2.3

#### Expected

```js
    login: (callbackPath?: any) => any;
    logout: (callbackPath?: string) => any;
```

Is there something else than appending the callbackPath to the logout endpoint that i'm missing ?

---
in oidc.ts
line 434

```js
    async logoutAsync() { <--- HERE
        const oidcServerConfiguration = await this.initAsync(this.configuration.authority);
        // TODO implement real logout
        await this.destroyAsync();  
        window.location.href = oidcServerConfiguration.endSessionEndpoint; <-- Add redirect
    }
```

### Additional Details

I can open a PR for that If you want.

- Installed packages:

**Comment by guillaume-chervet** [comment]
Yes, there is a pr on appauth js about logout.
I was waiting for a merge from it. I will investigate next monday on it. If you have time, a pr would be very cool.

Thank you very much for your feeback.

**Comment by guillaume-chervet** [comment]
This Pull Request merge would be nice => https://github.com/openid/AppAuth-JS/pull/198

**Comment by bonnetb** [comment]
Hi,
I forked react-oidc and fitted it to a "merged" AppAuth (https://github.com/arssly/AppAuth-JS).
Logout seems to work fine with react-oidc sample app.

**Comment by bonnetb** [comment]
Here is my feature branch : https://github.com/bonnetb/react-oidc/tree/feat/logout
(not to be merged before https://github.com/openid/AppAuth-JS/pull/198 is merged)

**Comment by guillaume-chervet** [comment]
Awesome @bonnetb thank you,

May you set a message on https://github.com/openid/AppAuth-JS/pull/198, it would be cool a merge from them :)

**Comment by ddecrulle** [comment]
Do you have any news about this ?

 I'm really concerned with and the lib AppAuth-JS sems to be off ...

**Comment by guillaume-chervet** [comment]
Me too, may be we will need to implement it here.

**Comment by tielushko** [comment]
Seems like AppAuth-JS hasn't been updated in a year. I wonder if it has become dead?

**Comment by guillaume-chervet** [comment]
Yearh, I will try to email the team.
I am thinking to take the owership of it and ask openid team to certify their own library.

For example: 
axa-fr/appauthjs

**Comment by guillaume-chervet** [comment]
I'am waiting for any news from them => https://github.com/openid/AppAuth-JS/issues/209

If no news, I will fork it and ask openid team to certify the fork :/

**Comment by guillaume-chervet** [comment]
I made https://github.com/AxaGuilDEv/react-oidc/pull/761
But It does seem to work with the identityServer demo.

**Comment by tedoham** [comment]
> 

Is there any solution for the Identity Server? To redirect on logout?

**Comment by guillaume-chervet** [comment]
I will investigate
