### ISSUE TITLE
The script has an unsupported MIME type ('text/html'). DOMException: Failed to register a ServiceWorker

### ISSUE THREAD

**Issue by Mastanka** [AxaGuilDEv/react-oidc#717]
### Issue and Steps to Reproduce

When loading framework libraries "The script has an unsupported MIME type ('text/html')." is written to console.

When accessing <OidcSecure> protected React component error happen. And page is displayed: 
"Authentification erreur
Une erreur est survenu lors de l'authentification"

This happens only if I'm using:
```
  service_worker_relative_url:'/helpers/authentication/OidcServiceWorker.js',
  service_worker_only:true
```
in oidcConfiguration. Without ServiceWorker everything is fine.

I want to use service worker as a event entry point after login/silentLogin to update user context with name of logged user. (i dont want to create authentication/callback page and do it there)

### Versions
4.2.8

### Screenshots
<img width="1512" alt="Screenshot 2022-03-06 at 18 50 38" src="https://user-images.githubusercontent.com/13008057/156936528-fe1dbfde-1994-48d0-85cc-b132eeebe68c.png">

#### Expected
Redirect to oidc authentication endpoint.

#### Actual
Error is displayed.

### Additional Details
Has anyone run into this issue since migration v3 -> v4? 
I've done all steps according to the manual. And I'm getting this error. 
- Installed packages:
    "@axa-fr/react-oidc-context": "^4.2.8",
    "react": "17.0.2",
    "react-dom": "17.0.2"

**Comment by Mastanka** [comment]
And by any chance, does anyone know why "callbackSuccessComponent" is not initiated after login?
 ` <OidcProvider configuration={oidcConfiguration} callbackSuccessComponent={Callback} authenticating={Callback}>`

I'm trying to implement update of UserName after user is authenticated, but I when I set component to the OidcProvider, the component is never called. Not even when I set it as "authenticating" component... 

Thanks a lot!

**Comment by guillaume-chervet** [comment]
For your second message,

If I were your I would use a custom hooks or pure functions that will map to a UserA to a new UserB.

You Won't be able to modify user information given by the library.

What do you think?

**Comment by Mastanka** [comment]
Thanks a lot for you response! For the first issue, you're absolutely right. It seems to be the CORS problem in my code.

Regarding the updating UserInfo: I only need to read UserInfo, not modify it. This will happen in my custom function. The thing is that I need event, that will trigger when the user is authenticated either from normal or silent callback. Just as a trigger for my functions to update context. :) 

Once again, thanks a lot!

**Comment by guillaume-chervet** [comment]
May we close that issue?

**Comment by guillaume-chervet** [comment]
it was merge on main branch => https://github.com/AxaGuilDEv/ml-cli/blob/master/src/Ml.Cli.WebApp/ClientApp/public/web.config

:)

**Comment by TeckTn** [comment]
I have the same issue regarding triggring authentication success event.
Any possible fix?

**Comment by guillaume-chervet** [comment]
Do you have any error in the console? Do you have more information about your configuration. I have fixed today a bug like this on the very first connection with service worker.

**Comment by TeckTn** [comment]
My package version is 4.2.13.

I have a simple Provider using a success Callback Component. Every thing is working fine but the AuthSuccess Component is not called after a successfull login.

My Provider : 
```
 <OidcProvider
          configuration={props.configuration.auth.authOpenId}
          callbackSuccessComponent={() => <AuthSuccess />}
        > ...
```

My AuthSuccess Component : 

```
import { useEffect } from 'react';

export const AuthSuccess = () => {
  useEffect(() => {
    console.log('I am authenticated');
  }, []);

  return <span> I am conneted</span>;
};
```

**Comment by guillaume-chervet** [comment]
Thank you very much again for the feedback. The last version fix that.

**Comment by guillaume-chervet** [comment]
May we close that issue?

**Comment by Mastanka** [comment]
Yes please :) And thanks a lot

**Comment by guillaume-chervet** [comment]
Thank you @Mastanka for your help.
