### ISSUE TITLE
id_token_hint not provided when logging out

### ISSUE THREAD

**Issue by bonnetb** [AxaGuilDEv/react-oidc#720]
### Issue and Steps to Reproduce

Log-in, then log-out. Log-out will open OIDC Auth Server logout URL without passing id_token_hint as a URL parameter
### Versions
4.2.9

#### Expected
id_token_hint in logout URL request
#### Actual
logout URL requested with no parameter

### Additional Details

- Installed packages:

**Comment by bonnetb** [comment]
https://github.com/AxaGuilDEv/react-oidc/blob/6c146e85a4ac492693095478991883623e406729/packages/context/src/oidc/vanilla/oidc.ts#L438 should be replaced with a more sophisticated call to logout URL

**Comment by guillaume-chervet** [comment]
Thank you very much for your feedback. It is a must that have quicky to be done.

The issue duplicate #713

**Comment by guillaume-chervet** [comment]
This Pull Request merge would be nice => https://github.com/openid/AppAuth-JS/pull/198

**Comment by guillaume-chervet** [comment]
I'am waiting for any news from them => https://github.com/openid/AppAuth-JS/issues/209

**Comment by guillaume-chervet** [comment]
I have the answer from the issue  we will have to implment it here.

**Comment by abhilashlr7** [comment]
This happens for us now. when we simply invoke `logout()` from `useOidc()` hook. Perhaps, the issue is not reproducible often, and has come back up post keycloak 19 version that's deployed on our server.
