### ISSUE TITLE
Warning messages with react-script 5.0.0 and webpack v5

### ISSUE THREAD

**Issue by samuel-gomez** [AxaGuilDEv/react-oidc#723]
### Issue and Steps to Reproduce

Some warning messages appears with webpack 5 when run "npm start" 

To reproduce : node v16.x and npm 7.x
- clone and install https://github.com/samuel-gomez/react-starter-toolkit/tree/feature/react-script-v5
- run "npm start"

### Screenshots
![image](https://user-images.githubusercontent.com/16844565/157327764-7e1e294f-8b5b-47ec-bdb9-e361995bfe01.png)

#### Expected
 "npm start"  without warning messages

### Additional Details

- Installed packages: react-script 5.0.0
- https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md

**Comment by samuel-gomez** [comment]
@guillaume-chervet

**Comment by guillaume-chervet** [comment]
Thank you for the issue samuel ^^
It is bizarre, We have the same configuration on our projet and not the error.

We are proding our project tonight :)

I make the test

**Comment by guillaume-chervet** [comment]
I can reproduce it with your sample thank you :)

**Comment by samuel-gomez** [comment]
it's seem to be a issue on react-script, here a PR : https://github.com/facebook/create-react-app/pull/11752
We can temporarily add 
```json
"start": "GENERATE_SOURCEMAP=false react-scripts start",
```
stackoverflow : https://stackoverflow.com/questions/63195843/webpack-module-warning-failed-to-parse-source-map-from-data-url

**Comment by guillaume-chervet** [comment]
Thank you @samuel-gomez

**Comment by bdely-tu** [comment]
I also have the same issue with a lot of warnings about the source map missing.

There is no src folder in the `react-oidc-context` package (version 5.0.8), if the src folder is missing from the package how would it be `react-scripts`?

**Comment by guillaume-chervet** [comment]
It should be fixed by the last version published yesterday !

**Comment by bdely-tu** [comment]
> It should be fixed by the last version published yesterday !

Thank you. it is fixed for me.

**Comment by guillaume-chervet** [comment]
I close the PullRequest @samuel-gomez  , feel free to reopen it if you need it.
Thank you very much !

**Comment by AndrejGajdos** [comment]
@guillaume-chervet was this fixed in 5.0.1? It's the latest version and I still have this issue.

**Comment by guillaume-chervet** [comment]
Hi @AndrejGajdos thabk you for the feedback. Are you sure it is the same error message? Now src directory is published to nom with the dist directory.

**Comment by AndrejGajdos** [comment]
Yes, it's the same error message coming apollo library :/

<img width="871" alt="Screenshot 2022-05-01 at 11 37 56" src="https://user-images.githubusercontent.com/1593758/166235385-87a0a649-449b-4897-87dc-faaf9b52b009.png">

**Comment by guillaume-chervet** [comment]
@AndrejGajdos apollo library does not have link to react-oidc.
It should have a similar issue.

Do you use react-oidc inside your project?

**Comment by guillaume-chervet** [comment]
Hi @AndrejGajdos , thank you for the information. You may add an issue to apollo-link-token-refresh github in order to help them to fix the issue.

**Comment by guillaume-chervet** [comment]
I close the issue, feel free to reopen it if require.
