### ISSUE TITLE
v.4. cant set acl_values/pass "extras" to AppAuth. Disappeared since v3.

### ISSUE THREAD

**Issue by oyvindma** [AxaGuilDEv/react-oidc#725]
### Issue and Steps to Reproduce
In order to specify which login mechanism to use, we need to have acl_values sento to the server. We can't find a way to do it with v4, and the code doesn't seem to support it.

### Expected
In version 3 it was possible to set acl_values on the configuration (which was based on UserManagerSettings in the underlying library), and it got forwarded to the server.

### Actual
In version 4 we can't find a way to send acl_values to the server, as the Configuration in vanilla doesn̈́'t have that value.  https://github.com/AxaGuilDEv/react-oidc/blob/v4.2.12/packages/context/src/oidc/vanilla/oidc.ts#L302

### Versions
Old version that worked: v.3.1.7
New version with the potential bug: v.4.2.12

### Potential fix
AppAuth-library doesn't seem to have a field for acl_values, but it has the concept of "extras" which gets passed through to the server as you can see here:
https://github.com/openid/AppAuth-JS/blob/cf6bb68dfe630c5d5f415bdcc76ea2581f041d8f/built/authorization_request_handler.js#L68

Potential fix:
add "extras? : StringMap" to [configuration](https://github.com/AxaGuilDEv/react-oidc/blob/v4.2.12/packages/context/src/oidc/vanilla/oidc.ts#L45), and pass the value on to AuthorizationRequest here https://github.com/AxaGuilDEv/react-oidc/blob/v4.2.12/packages/context/src/oidc/vanilla/oidc.ts#L302

**Comment by guillaume-chervet** [comment]
hi @oyvindma, 
Thank you for your feebacks!

I think it it possible to add this.

**Comment by matemajoros** [comment]
Hi!
We faced with similar issues while migrating from v3 to v4. We didn't manage to set the `client_secret` that was part of the `UserManagerSettings` (the `OidcClientSettings` to be exact) before, but now it is not.

We would also appreciate the `extras?: StringMap` property in the `Configuration` or any other hint to manage to set the `client_secret`.

**Comment by guillaume-chervet** [comment]
I will try to make a PullRequest today, it is not so hard to add this.

**Comment by oyvindma** [comment]
That's great news! We're ready to test. Just let us know and we'll test it.
And thank you for building this great library!

**Comment by guillaume-chervet** [comment]
I have published => 4.2.14-alpha.0
from that PullRequest => https://github.com/AxaGuilDEv/react-oidc/pull/726/files

It was eaier that i expected :)

I'am waiting for your feedback.

**Comment by oyvindma** [comment]
It works:-) Thank you for the quick response.

**Comment by matemajoros** [comment]
Sorry for the late feedback.
Yesterday I managed to test it and it did work!
Thank you for the quick and great maintenance.

One small suggestion:
Can you please update with the next release the [migration guide](https://github.com/AxaGuilDEv/react-oidc/blob/master/MIGRATION_GUIDE_V3_TO_V4.md) doc's proptypes part to contain the new `extras` so others who want to migrate will see that they have the chance to pass extra props?
It should be added under [this](https://github.com/AxaGuilDEv/react-oidc/blob/676d5709191aa5896e66785c5a87d31c2570c238/MIGRATION_GUIDE_V3_TO_V4.md?plain=1#L91) line.

Thanks again! :)
