### ISSUE TITLE
redirect_uri set to / fails when handling redirect during login

### ISSUE THREAD

**Issue by oyvindma** [AxaGuilDEv/react-oidc#727]
### Issue and Steps to Reproduce
Due to various infrastructure related things redirecting to /authentication/callback won't work. In our situation we need to set configuration.redirect_url to root ( e.g. "http://localhost:3000"). When doing this, the switch i CallRoutes here https://github.com/AxaGuilDEv/react-oidc/blob/0f395412cfdda4259fea4c21bfcf0da25206e37b/packages/context/src/oidc/core/routes/OidcRoutes.tsx#L46 misses and the CallbackComponent never gets rendered.

When we explicitly set the trailing "/" in the redirect_uri  e.g. "http://localhost:3000/") the code failes here:
https://github.com/AxaGuilDEv/react-oidc/blob/0f395412cfdda4259fea4c21bfcf0da25206e37b/packages/context/src/oidc/vanilla/initSession.ts#L9

### Versions
4.14.2-alpha.0

#### Expected
Expected the CallbackComponent to be rendered and the handling of the login during redirect to be completed.

**Comment by guillaume-chervet** [comment]
Hi @oyvindma , thank you for your issue.

I have a question, do you use that route for something else or that route will be only for the callback ? (it is a very strange route :p)

**Comment by oyvindma** [comment]
Hi @guillaume-chervet, 
It's indeed a strange route. It's used for the single page react app as also. We haven't made it work yet (obviously) but trying to.

The reason is two infrastructure challanges:
1. The SPA is served a docker container with Apache Httpd. The docker image is not managed by/available to us, and we thereby don't have access to setting up wildcard matching of paths in httpd. Because of that, the redirect to /authentication/callback never hits our react app and react-oidc.
2. One option would have been to use hash-routing, but the OIDC-server we're communicating with doesn't allow redirecting to URI with #. 

At the moment we try to construct a workaround by having the react app check if the path contains "code=", and if it does we try to replicate what would have been done by your awesome library when the redirect hits /authentication/callback. Then we realized we maybe could set redirect_url to <host>/ and got the issue.

Some alternatives going forward:
1. Is it possible to fix the bug, and will it then be possible to use / ?
2. Are there any other/propper ways to solve our issue with react-oidc?
3. Or do you have any suggestions to improving our workaround.

Cheers!

**Comment by guillaume-chervet** [comment]
Yes sure i will try to make it works with / as callback. 
Thank you for your explanation. I think that you will not be the only one to need that case.

**Comment by guillaume-chervet** [comment]
With the following configuration:

```
export const configurationIdentityServer = {
    client_id: 'interactive.public.short', //  interactive.public.short
    redirect_uri: window.location.origin+'/', // http://localhost:4200/authentication/callback
    scope: 'openid profile email api offline_access',
    authority: 'https://demo.identityserver.io',
    refresh_time_before_tokens_expiration_in_second: 70,
    service_worker_relative_url:'/OidcServiceWorker.js',
    service_worker_only: false,
  };

```

It seem to work. 

![react_oidc](https://user-images.githubusercontent.com/52236059/157970622-963a5dd0-be0a-418a-8180-560077ad404e.gif)

Do you have more information or a sample ?
