### ISSUE TITLE
missing return types

### ISSUE THREAD

**Issue by Snazzie** [AxaGuilDEv/react-oidc#729]
### Issue and Steps to Reproduce

`useOidcIdToken` and  `useOidcAccessToken` has return type of any.

### Versions
@axa-fr/react-oidc-context 4.3.2

#### Expected
return value to be typed.

#### Actual
has return type of any
### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Yes definitively, it must be added.

**Comment by guillaume-chervet** [comment]
Thank you for the feedback :)

**Comment by guillaume-chervet** [comment]
Hi @Snazzie, I think the last version resolve the types issues.
Have you tried it?

**Comment by guillaume-chervet** [comment]
Hi @Snazzie , i close the issue. Thank you very much for thz pullrequest. Feel free to reopen it if anything is missing.
