### ISSUE TITLE
proper clean up

### ISSUE THREAD

**Issue by pinggi** [AxaGuilDEv/react-oidc#740]
### Issue and Steps to Reproduce

Shouldn't be [oidc.removeEventSubscription(subscriptionId);](https://github.com/AxaGuilDEv/react-oidc/blob/62f6cd6a7d395aaa41ea06d4582e5e3a06caf198/packages/context/src/oidc/OidcProvider.tsx#L85) called in useEffect cleanup function [here](https://github.com/AxaGuilDEv/react-oidc/blob/62f6cd6a7d395aaa41ea06d4582e5e3a06caf198/packages/context/src/oidc/OidcProvider.tsx#L109
)?

### Versions.

"@axa-fr/react-oidc-context": "^4.5.8"

**Comment by guillaume-chervet** [comment]
Thank you for your issue @pinggi, you are right this is an issue thank you very much.

**Comment by pinggi** [comment]
@guillaume-chervet that's great you fixed it. I think you could have deleted also [this](https://github.com/AxaGuilDEv/react-oidc/blob/62f6cd6a7d395aaa41ea06d4582e5e3a06caf198/packages/context/src/oidc/OidcProvider.tsx#L84) code:

```
        if(subscriptionId){
            oidc.removeEventSubscription(subscriptionId);
        }
```

1. when a component is mounted, `useEffect` function is called and the `cleanup` function returned from it registered
2. when the `useEffect` dependencies are changed (in this case `configuration` or `configurationName`), the cleanup function is called first and then the `useEffect` function

I also think the `if(isMounted) {` [check](https://github.com/AxaGuilDEv/react-oidc/blob/62f6cd6a7d395aaa41ea06d4582e5e3a06caf198/packages/context/src/oidc/OidcProvider.tsx#L103) is also useless since it's not an async code that would run when the component is unmounted - it's indented like it would be part of the `oidc.subscriveEvents` function but in fact it isn't.
