### ISSUE TITLE
source maps

### ISSUE THREAD

**Issue by pinggi** [AxaGuilDEv/react-oidc#741]
### Issue and Steps to Reproduce

The source maps are enabled, but Typescript files are missing in the `node_modules/@axa-fr/react-oidc-context/dist` folder. The browser is unable to load the file when debugging an error/exception.

### Versions

"@axa-fr/react-oidc-context": "^4.5.8" (4.5.8 in yarn.lock)

#### Expected

The Typescript files are there or source maps are disabled.

**Comment by guillaume-chervet** [comment]
hi @pinggi ,

Thank you for your issue. WIth version of create-react-app are you using?
I have some source map available in my dist folder when I build the library:

![image](https://user-images.githubusercontent.com/52236059/160934366-4008527a-515e-46d5-bbf3-c74d5b56988f.png)

**Comment by pinggi** [comment]
I use version 5.0.0.

1. I installed the package: `yarn add @axa-fr/react-oidc-context`
2. I noticed there are missing *.ts files because the browser I use for debugging couldn't load the *.ts files

If I open `node_modules/@axa-fr/react-oidc-context/dist/vanilla/oidc.d.ts.map` file for example, I can see the source path leads to `../../src/oidc/vanilla/oidc.ts` which resolves to `node_modules/@axa-fr/react-oidc-context/src/oidc/vanilla/oidc.ts` - I don't have the file there (the `src` folder is missing there).

**Comment by guillaume-chervet** [comment]
Hi, i understand the problem. I will investigate.

**Comment by guillaume-chervet** [comment]
I just push a fix to include src folder to npm publish.
Thank you very much for your issue !

**Comment by guillaume-chervet** [comment]
I close the PullRequest @pinggi , feel free to reopen it if you need it.
Thank you very much for your help !
