### ISSUE TITLE
post_logout_redirect_uri is missing from the configuration.

### ISSUE THREAD

**Issue by tielushko** [AxaGuilDEv/react-oidc#746]
### Versions
https://www.npmjs.com/package/@axa-fr/react-oidc-context/v/5.0.2

### Screenshots
![image](https://user-images.githubusercontent.com/46033508/161618664-ceb5be1d-0ad7-4fb8-8b6e-0113b862c995.png)

 vs 

![image](https://user-images.githubusercontent.com/46033508/161618717-f547fc06-c362-4f5b-9acf-e949ff85bdce.png)

#### Expected
in v3 I could specify to redirect from the authentication provider back to my home page "/" after the user logs out. 

#### Actual
in v4 and v5, the options to insert the post_logout_redirect_uri is missing. I was wondering if there's still possibility for adding this configuration, as it's important for our stakeholders.

### Additional Details

- Installed packages:

**Comment by tielushko** [comment]
Never mind, I went browsing through issues a bit more, and noticed the PR for AuthJS for implementing the logout. I will be waiting for updates then. Thank you!

**Comment by guillaume-chervet** [comment]
I'am waiting for any news from them => https://github.com/openid/AppAuth-JS/issues/209

**Comment by guillaume-chervet** [comment]
I close the issue, it is done and followed by #775 

Thank yoi for the issue and feel free to reopen it if needed.

**Comment by tielushko** [comment]
I monitored the solution closely, @guillaume-chervet! Thank you so much for your help!
