### ISSUE TITLE
Default component overriding

### ISSUE THREAD

**Issue by tiphaineruy** [AxaGuilDEv/react-oidc#750]
### Issue and Steps to Reproduce

Is There a quick guide / best practice on how to override "default component" ? Like adding a spinner or redirect on expired session ? 
Currently on session expired You get the blank page:
```
Session expirée
Votre session est expirée. Veuillez vous ré-authentifier.
```

### Versions

4.5-alpha.0 ( up to date to master, so I Assume i'm on version 5.0.9, I seems the package.json version isn't updated.

**Comment by guillaume-chervet** [comment]
Hi @tiphaineruy, Thank you very much for you issue.

Definilty we need to add sample inside the demo and inside the readme :
https://github.com/AxaGuilDEv/react-oidc/blob/e72ac9f74dfa333dc8c358724521de0c2e6980dd/packages/context/src/oidc/OidcProvider.tsx#L63

You can override all componenents like below :

```
var Override = () => <p>Override</p>


 <OidcProvider configuration={configurationIdentityServer}
callbackSuccessComponent={CallBackSuccess}
                                                                             callbackErrorComponent={Override}
                                                                             authenticatingComponent={Override}
                                                                             loadingComponent={Override}
                                                                             serviceWorkerNotSupportedComponent={Override}
                                                                             authenticatingErrorComponent={Override}

>
      <p>you content</p>
    </OidcProvider>
  );


```

We need to keep synchonise the package.json version too.

**Comment by guillaume-chervet** [comment]
The package.json version is now synchronised automaticaly.  I will update the documentation soon for the components override.

**Comment by guillaume-chervet** [comment]
I have update the documentation and the demo.
https://github.com/AxaGuilDEv/react-oidc/tree/master/packages/context

The multi auth page now use it => https://black-rock-0dc6b0d03.1.azurestaticapps.net/multi-auth

You can use the children property too.

Does it help you ?
