### ISSUE TITLE
Grant type issue

### ISSUE THREAD

**Issue by veloki** [AxaGuilDEv/react-oidc#751]
Hi,

I'm trying to use this library but i need to configure the grant type as "implicit".

Is it possible or only with Authorization-code?

I'm getting this error on identity:
Invalid grant type for client: authorization_code

Thanks

**Comment by guillaume-chervet** [comment]
Hi @, thank you very much for your issue.
Unfortunately, we do not support implicit flow which is too less secure. Authorization code grant with PKCE is like implicit but more secure for the authentication phase. If you can please use it.

**Comment by guillaume-chervet** [comment]
Hi @veloki . I close the issue. Thank you very much for your question. Feel free to open a new one if needed.
