### ISSUE TITLE
Passing extra params with login method

### ISSUE THREAD

**Issue by mrcarl79** [AxaGuilDEv/react-oidc#752]
Hi,

I have just moved from a different react oidc package to this one, going great so far. I wondered if there was a requirement to be able to pass extra params at login also? it's a requirement I'm looking at currently as used it previously. Like how you can via the configuration, but more dynamic so it can be changed per user. I have checked the following:

/packages/context/src/oidc/vanilla)/oidc.ts

and it would look something like this:

async loginAsync(callbackPath:string=undefined, extras?:StringMap, installServiceWorker=true) {

Then combined this StringMap with the one from the config and then pass to the authRequest.

Is this something you would be able to add? otherwise I might try to implement it myself and see if I can request it be pulled into the source code. But I'm not sure if there is anything else of concern I should consider first.

Thanks Carl

**Comment by guillaume-chervet** [comment]
Hi @mrcarl79 , thank you for your issue. It seems to me to be definitly a very nice feature too add !

**Comment by mrcarl79** [comment]
> Hi @mrcarl79 , thank you for your issue. It seems to me to be definitly a very nice feature too add !

Great, I have managed to add this feature locally and tested and got it to work for my requirements. However I'm not sure if what I have coded could affect other areas. I have not contributed to this project yet, but happy to submit a PR of what I changed so you can see. It's fairly simple, if you want to implement what I have tried you are welcome or change it if there was a better way. Thanks Carl

**Comment by guillaume-chervet** [comment]
will #753 respond to your need?

**Comment by mrcarl79** [comment]
> will #753 respond to your need?

@guillaume-chervet Yes that looks great, looking forward to testing the new feature :) thanks

**Comment by guillaume-chervet** [comment]
@mrcarl79 ,

I have published it. does it respond to your need?

**Comment by guillaume-chervet** [comment]
I close the issue, I think it is ok !
Thank you very much for the issue. Feel free to re-open it if you need.
