### ISSUE TITLE
Not sending client secret

### ISSUE THREAD

**Issue by bdely-tu** [AxaGuilDEv/react-oidc#755]
The OIDC configuration `client_secret` is being set in the code but when it is sent to the auth server it is not sending the secret only the client id. I know the PCKE flow does not need the `client_secret` it is just our current auth server requires it and to change it too not is too much work and our auth team is in the process of upgrading to a new OAuth server. 

Is there a way to make it send the `client_secret` with the PCKE flow?

Version 5.3.1
It was sending it previously with 3.1.7

**Comment by guillaume-chervet** [comment]
Hi @bdely-tu , it is already working if you follow the Google configuration in that file

https://github.com/AxaGuilDEv/react-oidc/blob/master/packages/context/src/configurations.ts

**Comment by bdely-tu** [comment]
@guillaume-chervet Thanks that works
