### ISSUE TITLE
[context-oidc] Issue when token Expire and SilentRenewFail

### ISSUE THREAD

**Issue by oyouf** [AxaGuilDEv/react-oidc#77]
When a silent renew faile, the token expire and it is no renewed. So we stuck with a expired token with no posssibility to renew it automatiquely. We have to force logout and login again

**Comment by oyouf** [comment]
IMO we have to manage user_expired event.

**Comment by guillaumechervetaxa** [comment]
Are you talking about "@axa-fr/react-oidc-context" ?

**Comment by youf-olivier** [comment]
Yep. Title updated
