### ISSUE TITLE
Url Redirect on logout

### ISSUE THREAD

**Issue by tiphaineruy** [AxaGuilDEv/react-oidc#775]
### Issue and Steps to Reproduce

With the newest release of Keycloak18 I realised that the "redirect_uri" in #713 isn't part of the OpenID implementation
The new implementation for keycloak seems to be based on the oidc ref:
https://openid.net/specs/openid-connect-rpinitiated-1_0.html
( see: https://www.keycloak.org/2022/04/keycloak-1800-released at post_logout_redirect_uri )

using the following url params added to the logout endpoint
post_logout_redirect_uri
id_token_hint

However id_token_hint requires to know the token which isn't a solution when using the webworker actually. I'm not quite sure how to implement that currently appart from manually adding the id_token_hint in the webworker with a regexp to detect logout url ?

Using:

#### Expected

I would like to be able to insert the url params to the logout request
post_logout_redirect_uri
id_token_hint

### Additional Details

And anyways, Currently the fix #767 errors because encodeURI() should be encodeURIComponent(), And  redirect_uri seems to be specific to keycloak, when post_logout_redirect_uri is the openidconnect implementation.

- Installed packages:

**Comment by guillaume-chervet** [comment]
Thank you very @tiphaineruy, i think i understood what to do https://openid.net/specs/openid-connect-rpinitiated-1_0.html

Fortunately id token is not hidden by th service worker (only access token ans refresh token for the moment).
I will give a try 😀

**Comment by guillaume-chervet** [comment]
It seems to work https://github.com/AxaGuilDEv/react-oidc/commit/b5a314fe2f79e6b08a8f0dce625d890f088b2aa4 :)

**Comment by tiphaineruy** [comment]
That's awsome Thanks !

**Comment by Leopoldo-Rangel** [comment]
Hi, just tested this and works great, thank you. Only detail is that currently post logout url is not allowed to be empty: 
 logout("") , in case return Url was root of the site.

Thanks again.

**Comment by guillaume-chervet** [comment]
What behavior would you expect?
may be null does not set the callback url at all. what do yout think?

**Comment by Leopoldo-Rangel** [comment]
Would it be possible that logout("") sets the callback url to window.location.origin? Currently this line on /packages/react/src/oidc/vanilla/oidc.ts:

` const path = callbackPath || location.pathname + (location.search || '') + (location.hash || '');`

will set path to  location.pathname when callbackPath = ""

Thanks!
