### ISSUE TITLE
How to use in a context without routing?

### ISSUE THREAD

**Issue by xanderfehsenfelddelhivery** [AxaGuilDEv/react-oidc#777]
### Issue and Steps to Reproduce

I'd like to use this library without routing. How can I do this? All the 'redirect uris' are the same `window.location.href` value.

```typescript
const currentLocation = window.location.origin + window.location.pathname;

const configuration: OidcConfiguration = {
  client_id: process.env.REACT_APP_CLIENT_ID as string,
  redirect_uri: currentLocation,
  silent_redirect_uri: : currentLocation,
  scope: 'openid profile email',
  authority: process.env.REACT_APP_AUTHORITY as string,
  service_worker_only: false,
};

```

### Versions

`"@axa-fr/react-oidc": "^5.7.3-alpha0",`

#### Expected

Library handles authentication. 

#### Actual

Infinite redirect loop between the client and the sign in page. This makes sense with the current implementation because the library differentiates the auth state via the uri. So it expects callbacks like `/silent-redirect` or `/redirect`.

**Comment by guillaume-chervet** [comment]
Hi @xanderfehsenfelddelhivery , thank you very much for your issue 
Does it work by using some #
Like
#redirect
#slilent-redirect

I will make some tests and look about what it isnpossible to do.

**Comment by guillaume-chervet** [comment]
hi @xanderfehsenfelddelhivery ,

I will add a pullRequest soon to authorise configuration like that:


`
export const configurationIdentityServer = {
    client_id: 'interactive.public.short', 
    redirect_uri: window.location.origin+'#/authentication/callback', 
    silent_redirect_uri: window.location.origin+'#/authentication/silent-callback',
    scope: 'openid profile email api offline_access',
    authority: 'https://demo.duendesoftware.com',
    refresh_time_before_tokens_expiration_in_second: 70,
    service_worker_relative_url:'/OidcServiceWorker.js',
    service_worker_only: false,
  };
`

Will it answer to your need?
