### ISSUE TITLE
AccessTokenPayload is null

### ISSUE THREAD

**Issue by another1aa** [AxaGuilDEv/react-oidc#786]
AccessTokenPayload is null after successful authentication.

I see that access token and id token are retrieved successfully but accesstokenpayload is null.

I noticed extractAccessTokenPayload method will return null if token contains 2 dots. Valid JWT tokens actually must contain 2 dots in order to be valid header.body.signature. Is this a bug or intentional?

```
const extractAccessTokenPayload = tokens => {
    if(tokens.accessTokenPayload)
    {
        return tokens.accessTokenPayload;
    }
    const accessToken = tokens.accessToken;
    try{
        if (!accessToken || countLetter(accessToken,'.') === 2) {
            return null;
        }
        return JSON.parse(atob(accessToken.split('.')[1]));
    } catch (e) {
        console.warn(e);
    }
    return null;
};
```
Also useOidcUser() hook says that user is not authenticated. Is this because of the same issue?

Version I am using is 5.4.2

Thank you

**Comment by guillaume-chervet** [comment]
Hi @another1aa , thank you very much for your issue.
AccessTolenPayload is null is a normal behaviour because in your case your access token is not a JWT token.
But useOidcUser should return authenticated user.

May you update to the latest version? This bug may have already fixed.

**Comment by another1aa** [comment]
@guillaume-chervet thank you for the prompt response.
My token is a valid JWT token. I can decode it using the debugger in jwt.io as well as using the following code in react:
```
  const accessToken = JSON.parse(
    atob(useOidcAccessToken().accessToken.split(".")[1])
  );
```
I have also updated the package to version 5.7.7 and issue with useOidcUser still persists.

**Comment by guillaume-chervet** [comment]
Thank you with your code i understand the problem.

Which oidc provider are you using? It seems the access token is somewhere inside the accesstoken field and not directly the accesstoken.

**Comment by guillaume-chervet** [comment]
I have to search if it is a normal oidc use case behaviour and how to automate it.

**Comment by another1aa** [comment]
I am using Keycloak as identity provider. Keycloak returns access token in standard format "header.body.signature". For example:

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```

**Comment by guillaume-chervet** [comment]
Thank you, this is strange, it should work with your token format.
I will fix it next week. I cannot this week.

**Comment by guillaume-chervet** [comment]
I may need more information because your token format is the same as in the working demo.
Do you have a sample of a full response from authentication? With refresh token idtoken and accesstoken?

**Comment by guillaume-chervet** [comment]
Hi [another1aa](https://github.com/another1aa)

I cannot reproduce any problem on fetch of userinformation when service worker is not active.

Do you have more information ?

**Comment by another1aa** [comment]
Hi @guillaume-chervet I checked again with the latest version and the issue is not reproducible any more. Thank you very much for your help!

**Comment by another1aa** [comment]
Thanks!

**Comment by guillaume-chervet** [comment]
Thank you for the feedback. I close the pullrequest.
