### ISSUE TITLE
Add State Param in Configuration

### ISSUE THREAD

**Issue by zhien95** [AxaGuilDEv/react-oidc#787]
Hi, I am migrating from react-oidc-context v3 to react-oidc v5.
The default value of state is undefined in v5 but our authentication service using Ory Hydra requires an valid state value.
I have tried adding state in extras prop but it is not working.
Could we get an option to set our own state value in the configuration provided to OidcProvider?

**Comment by zhien95** [comment]
We first hit the route (http://localhost:3000) of our component wrapped in withOidcSecure
WrappedComponent:
![image](https://user-images.githubusercontent.com/37785503/170411995-24effb6e-bf5e-496e-9f58-18606f68b9c4.png)

Route:
![image](https://user-images.githubusercontent.com/37785503/170412037-5cb32149-511e-48e5-8213-b695c27ae9e6.png)

As the user is not authenticated, it makes an auth request to our hydra auth server
v3 Auth Request:
https://spe-ms-hydra.apps.ocpsit.uat.dbs.com/oauth2/auth?client_id=1b39cecf-9d50-4ec0-8c8b-02ba58a4bc1f&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauthentication%2Fcallback&response_type=code&scope=openid%20offline_access%20http%3A%2F%2Flocalhost%3A8082%20DRTS_SG_TRADER%20DRTS_SG_ENQUIRY%20DRTS_SGD_ACS_TRADER%20DRTS_SGD_SGMM_TRADER&state=f7fac9dd7bbd4f0dbf726ce4a3c6b488&code_challenge=pRv0Wr-0Zx_Zz71X8lw5lwoB9Ldt_h_tL76xUJ7LIrk&code_challenge_method=S256&response_mode=query

![image](https://user-images.githubusercontent.com/37785503/170412746-d7ed6277-5432-43b3-a65e-1ef217fe090b.png)

v5 Auth Request:
https://spe-ms-hydra.apps.ocpsit.uat.dbs.com/oauth2/auth?redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauthentication%2Fcallback&client_id=1b39cecf-9d50-4ec0-8c8b-02ba58a4bc1f&response_type=code&state=%2F&scope=openid%20offline_access%20http%3A%2F%2Flocalhost%3A8082%20DRTS_SG_TRADER%20DRTS_SG_ENQUIRY%20DRTS_SGD_ACS_TRADER%20DRTS_SGD_SGMM_TRADER&code_challenge=G6W9zkezTft7QrxFJ55JakSNTH8syfscAYEBckaVGg0&code_challenge_method=S256

![image](https://user-images.githubusercontent.com/37785503/170412964-ed3c4b33-7ddc-448b-a749-964ce8c1e5ab.png)

As the auth request does not meet the state value requirement of 8 characters length, it throws back an invalid_state error
![image](https://user-images.githubusercontent.com/37785503/170413071-cd98b8b6-e89c-498b-a39d-aaac31b70b0f.png)

We can work around the state value by passing a callback path param in withOidcSecure but it's not elegant as we will need to change the routing of our components
![image](https://user-images.githubusercontent.com/37785503/170413255-6a012aa3-bcb8-4605-8e7d-af5a6da64030.png)

**Comment by guillaume-chervet** [comment]
Thank you @zhien95 , i will try to make you à pull request on monday. I will add state value to paramaters that you will be able to set.

**Comment by zhien95** [comment]
Thank you kind Sir @guillaume-chervet

**Comment by guillaume-chervet** [comment]
I think the version 5.7.8 I just published may fix your issue.

**Comment by zhien95** [comment]
Thanks @guillaume-chervet, it fits our use case.
