### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by Lukejkw** [AxaGuilDEv/react-oidc#795]
### Issue and Steps to Reproduce

Type errors when using hooks

### Versions

Latest

### Screenshots

![image](https://user-images.githubusercontent.com/13328460/172671204-de0d3c92-30fa-4148-9b94-c132fe8667f4.png)

#### Expected

Types automatically included

#### Actual

Any values returned

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Hi @Lukejkw thank you very much for the issue.
It is definitly something to type as it is possible to do.

**Comment by Lukejkw** [comment]
It would be fairly easy to allow the user to specify their user type as a generic argument to the hook, otherwise to fallback to `any`.

In strictly typed applications, not having a typed user entity makes the hooks quite difficult to use.

Would you accept a PRs to add in some better typing?

**Comment by jcrawl3y** [comment]
@guillaume-chervet is there any progress on this?  What @Lukejkw is proposing sounds like a great solution?

**Comment by guillaume-chervet** [comment]
Yes, i think i can do this quickly I am working on an internal refactoring and I am playing to add better typing

**Comment by guillaume-chervet** [comment]
It would be awesome to have a pullrrquest from @Lukejkw
