### ISSUE TITLE
isAuthenticated always false

### ISSUE THREAD

**Issue by ulduc** [AxaGuilDEv/react-oidc#798]
Hello,

i'm a bit new to React and i think i just got the OIDC philosophy and i'm trying to integrate it to our new website.

I'm having trouble because i feel like it's too simple to put in place and here is what i have :

App content surrounded by OpenidProvider with the config file that seems to work (i can connect, redirect and all works)
then i have my User class surrounded by OidcSecure mark and this component is included in my header.
As soon as i arrive on my website i have the redirection done.

The problem is that isAuthenticated never seems to be true.
without any test, the oidcSecure mark should know the user is connected and stop redirecting right ?

I set the OidcServiceWorker and the OidcTrustedDomains as it's said in the readme

It's a SPA, quite simple for now.

Do you have any idea of what i'm missing to make this work ?

Thank you

**Comment by guillaume-chervet** [comment]
Hi @ulduc  thank you for your interrest and your issue.

Which version are you using?

Did you look a the demo code. There is a working sample.

Do you have a sample of your code in oder to help you?

**Comment by ulduc** [comment]
hi, thank you for your answer,

i'm using the last version 5.10.7 "@axa-fr/react-oidc": "^5.10.7"

I followed the demo in github, i even read your article on the openid protocol, very interesting (btw i read in french)

i have my app that is called in index.js and looks like this
`<ThemeProvider theme={theme}>
      <OidcProvider configuration={configurationIdentityServer}>
        <div className={classes.root}>
          <BrowserRouter>
            <CssBaseline />
                <Navigator PaperProps={{ style: { width: drawerWidth } }} />
            <div className={classes.app}>
              <Header onDrawerToggle={handleDrawerToggle} />
              <main className={classes.main}>
                <Content />
              </main>
              <footer className={classes.footer}>
                <Copyright />
              </footer>
            </div>
          </BrowserRouter>
        </div>
      </OidcProvider>
    </ThemeProvider>`

with the config looking simple like this and working !

`export const configurationIdentityServer = {
  client_id: "APP-XXX",
  redirect_uri: window.location.origin,
  silent_redirect_uri: window.location.origin,
  scope: "openid email",
  authority: "https://xxx.fr",
  refresh_time_before_tokens_expiration_in_second: 70,
  service_worker_relative_url: "/OidcServiceWorker.js",
  service_worker_only: false,
};`

and then my user that is called in the Header that is itself called in the App

`const UserBase = () => {
  const dispatch = useDispatch();
  //   const { nom, status, error } = useSelector((state) => state.user);
  const { login, logout, isAuthenticated } = useOidc();
  const { oidcUser, oidcUserLoadingState } = useOidcUser();

  switch (oidcUserLoadingState) {
    case OidcUserStatus.Loading:
      return <p>User Information are loading</p>;
    case OidcUserStatus.Unauthenticated:
      return <p>you are not authenticated</p>;
    case OidcUserStatus.LoadingError:
      return <p>Fail to load user information</p>;
    default:
      return (
        <div>
          <div>
            <h5>User information</h5>
            <p>{JSON.stringify(oidcUser)}</p>
          </div>
        </div>
      );
  }
};

export const User = () => {
  return (
    <OidcSecure>
       <UserBase />
    </OidcSecure>
  );
};`

in this configuration, the redirection is done, the authentication works fine and the return_url seems good but once i'm back on the website from the authentication server, the context is not updated and the isAuthenticated variable stays false, the "oidcUserLoadingState" is always "OidcUserStatus.Unauthenticated"

i didn't see anywhere to update my redux state and i thought your package would handle this with having me to do it.

What do you think ? what did i do wrong ?

Merci !

Nicolas

**Comment by ulduc** [comment]
I just realised that i wasn't using the URL /authentication/callback because we declared our website to the OIDC server as the simple URL.
does it bother ? Do we have to declare URL/authentication/callback as the URL of the website ?

**Comment by guillaume-chervet** [comment]
Yes your configuration should declare a route like 
redirect_uri: window.location.origin/callback
That should be declared in your oidc server.
React oidc library will autamticaly catch that route and use it.

**Comment by ulduc** [comment]
Good morning Guillaume,

no sadly, we still have problems. Our config is now window.local.href + "/callback"
we are redirected and we come back cleanly but it doesn't seem that the serviceWorker does his job. We just have a return URL at /callback and it searches for a route.

I see in your test also that in my console never ever do i see the logs that are in the serviceWorker. Is it normal behavior ? am i not looking at the right spot ?

Thank you for your concern !

**Comment by guillaume-chervet** [comment]
Hi @ulduc ,

Does yous server redirect you route to your index.html page? It look like it is a server configuration problem.

Did you try to comment service worker configuration line in order to disable it? Service worker is not necessarry to make it works first.

**Comment by ulduc** [comment]
I tried to commment the serviceworker lines in the config

i have a very small app just to understand everything

App.js 

```
import { User } from "./components/user/User";
import { OidcProvider } from "@axa-fr/react-oidc";
import { configurationIdentityServer } from "./app/configOIDC";

function App() {
  return (
    <OidcProvider configuration={configurationIdentityServer}>
      <div className="App">
        <p>Salut</p>
        <User />
      </div>
    </OidcProvider>
  );
}
```
with the conf 
```
export const configurationIdentityServer = {
  client_id: "APP-XXX-PREPROD",
  redirect_uri: window.location.origin + "/callback",
  silent_redirect_uri: window.location.origin + "/callback",
  scope: "openid email",
  authority: "https://authentification.XXX.fr",
  refresh_time_before_tokens_expiration_in_second: 70,
  // service_worker_relative_url: "/OidcServiceWorker.js",
  // service_worker_only: false,
};
```
then the User
```
import React, { useEffect, useState } from "react";
import { useOidcUser, OidcUserStatus, useOidc } from "@axa-fr/react-oidc";

function UserBase() {
  const { login, logout, isAuthenticated } = useOidc();
  const { oidcUser, oidcUserLoadingState } = useOidcUser();

  switch (oidcUserLoadingState) {
    case OidcUserStatus.Loading:
      return <p>User Information are loading</p>;
    case OidcUserStatus.Unauthenticated:
      return (
        <p>
          you are not authenticated, click{" "}
          <button onClick={() => login("/")}>here</button> to connect
        </p>
      );
    case OidcUserStatus.LoadingError:
      return <p>Fail to load user information</p>;
    default:
      return (
        <div>
          <div>
            <h5>User information</h5>
            <p>{JSON.stringify(oidcUser)}</p>
          </div>
        </div>
      );
  }
}

export default UserBase;
```

This behaves weirdly as once i asked for connection, i get redirected, i come back to /callback and the session is instantly refreshed.

**Comment by ulduc** [comment]
Ok ! the circle has been broken !  thank you !
Now what i have after the authentication worked, the silent refresh returns an error (and yes ofc, it's a bad URL error as we didn't declare this one to the server handler)
Could it come from our server configuration that should return at least 2 URLs (/callback and /silent-callback) and does it need to have the root URL somehow or everytime it will be either /callback or /silent-callbak that will ask for the authentication ?

Thank you !

Nicolas

**Comment by guillaume-chervet** [comment]
Hi @ulduc the silent route is not required. You can comment it for testing.
It a way to retrieve lost session in background via oidc server cookies via iframe and to increase authentification lifetime.

You do not need to declare it in your oidc server. It is only javascript front side

**Comment by guillaume-chervet** [comment]
Hi @ulduc , may we close the issue?

**Comment by ulduc** [comment]
Hi Guillaume, we did many tests and it occured everything works if the serveur allows public client on our account. So yes the issue is no longer a issue, thank you for your time and explanations.
