### ISSUE TITLE
race condition in serviceworker on firefox

### ISSUE THREAD

**Issue by torvalde** [AxaGuilDEv/react-oidc#800]
### Issue and Steps to Reproduce

I use Keycloak to authenticate and it redirects back to my server. This works fine in Chrome but in Firefox it fails on this line:

registration.active.postMessage(data2, [messageChannel.port2]);

with this error:

Uncaught (in promise) TypeError: registration.active is null

This seems to be some kind of race condition, if I set a breakpoint it starts working....

I will try to debug further, just posting for now in case someone else have a quick solution.

I use the latest version of Chrome and Firefox, I am on mac but we have seen the same error on firefox on linux

**Comment by guillaume-chervet** [comment]
hi @torvalde , thank you for the issue :)

Which version of firefox are you using?
I cannot reproduce it with the demo and firefox 

https://black-rock-0dc6b0d03.1.azurestaticapps.net

![image](https://user-images.githubusercontent.com/52236059/174665820-212cd65e-3349-453d-bfff-467b5b3f9837.png)

**Comment by torvalde** [comment]
I am using Firefox 101.0.1 (64-bit)

**Comment by guillaume-chervet** [comment]
I am on windows, that may be the différence.

**Comment by torvalde** [comment]
I asked a colleague to test on windows, we get the same error there.

**Comment by torvalde** [comment]
I debugged the issue and When I removed some old CRA generated code for a default serviceworker the bug went away.

Sorry for the extra noice.

**Comment by oussamaAbdelwahed** [comment]
@torvalde can you please describe the steps  you followed on firefox to remove the old CRA generated code for a default serviceworker !!?
