### ISSUE TITLE
OidcServiceWorker.js: Failed to execute 'clone' on 'Request': Request body is already used

### ISSUE THREAD

**Issue by amarmechai** [AxaGuilDEv/react-oidc#809]
### Issue and Steps to Reproduce
Configuration: 
```javascript
{
    client_id: 'myapp',
    redirect_uri: window.location.origin + '/authentication/callback',  
    post_logout_redirect_uri: window.location.origin + '/authentication/logout-callback',
    scope: 'openid profile email roles offline_access',
    authority: window.location.origin,
    service_worker_relative_url: '/OidcServiceWorker.js',
    service_worker_only:false,
}
```
### Versions
5.13.1
### Screenshots
![image](https://user-images.githubusercontent.com/4630877/177920006-6e5b91c5-c048-4419-bd05-0629da907cea.png)

**Comment by guillaume-chervet** [comment]
I @amarmechai , do you have more information about the fetch behind?
I remembert someone who had the problem it was a server thing or like that.

**Comment by guillaume-chervet** [comment]
@amarmechai which browser do you use?

**Comment by amarmechai** [comment]
> @amarmechai which browser do you use?

Goolgle Chrome

**Comment by guillaume-chervet** [comment]
Try to Remove the use of service worker via the configuration. You should see the real error behind.

**Comment by amarmechai** [comment]
@guillaume-chervet  without service worker, it work fine, but when I activate ServiceWorker I have this error with opendiddict 

![image](https://user-images.githubusercontent.com/4630877/178249545-1a8e38f4-ea01-47b1-929a-c0e72388623e.png)

**Comment by guillaume-chervet** [comment]
Does your service worker is up to date?

**Comment by amarmechai** [comment]
Yes, I have the lastest version

**Comment by guillaume-chervet** [comment]
Hi did not know about openiddict. It looks very cool.
Do you have a git sample where i can reproduce the error ?

Does your https certificate is trusted by your browser?

**Comment by amarmechai** [comment]
I will try to prepare an example for you as soon as possible.

**Comment by guillaume-chervet** [comment]
I found the bug by hazard !

You can try the 6.0.0-alpha2 pretty stable (I have just to finish documentation) and it fix it.

https://github.com/AxaGuilDEv/react-oidc/blob/295776fbfeabde78f6d39ae5326f3a7da5050a11/MIGRATION_GUIDE_V5_TO_V6.md

**Comment by amarmechai** [comment]
Thank you, I confirm that it is fixed.
