### ISSUE TITLE
Storing tokens on localStorage?

### ISSUE THREAD

**Issue by lisandro52** [AxaGuilDEv/react-oidc#814]
Hi,

I've been looking around the other issues and the documentation, but I couldn't find anything about how to store the token/s on localStorage. From what I've read, if I don't want to use sessionStorage, I have to use the service worker implementation.

This isn't possible in my use case because:
- The service worker implementation might not work on some of our users, because they could be using foutdated browser's versions (and we can't force them to update).
- The sessionStorage strategy gives bad UX, as it "flickers" while authenticating when you open a new tab. I'm already using oidc-react and they told me to fix that because "it looked bad" (and away I went with localStorage).

I *know* it's a **possible** security risk to have the token stored on LS, because we might get hit with a XSS attack, but at that point and in that situation, there will be more important problems to solve than where we store our tokens. Also, we have extra security measures on our backend and auth provider to mitigate a possible token leak.

Thanks

**Comment by guillaume-chervet** [comment]
Hi @lisandro52 , i understand your need.
It does require many code.
I may add it by using a property like useLocalStorageEventIfIKnowItIsLessSecureAndMayBeForbiddenBySecurityTeam.

**Comment by guillaume-chervet** [comment]
Last publish version 5.14.0 add a way to inject your own storage.

configuration = {storage:localStorage, ...};

let me know if it does the job for you :)

**Comment by lisandro52** [comment]
>I may add it by using a property like useLocalStorageEventIfIKnowItIsLessSecureAndMayBeForbiddenBySecurityTeam.

I'm sorry about reopening the issue, but I just remembered - I once read on the `react-router` docs (I think) that they exposed some of their inner components with the prefix `UNSAFE_`. That way, some users can 'move around' the implementation for some obscure edge scenario but it was made explicit that using that wasn't right. Maybe that's something we can add to the `storage` prop?
