### ISSUE TITLE
callbackErrorComponent property stopped working

### ISSUE THREAD

**Issue by pinggi** [AxaGuilDEv/react-oidc#816]
My code sets `CustomCallbackErrorComponent` to `callbackErrorComponent` property of `OidcProvider` like this:

```
<OidcProvider callbackErrorComponent={() => <CustomCallbackErrorComponent />} ...
```

The passed `CustomCallbackErrorComponent`  component is not rendered anymore after upgrading from V4 to V5.

The breaking change came with this [commit](https://github.com/AxaGuilDEv/react-oidc/commit/2b35abc0b58cfaa91b91036b81b4cd6e9656d8a7#diff-31d49ab1cf19e16eb1a39d6eeb160915474499a0526ad40212d65f48715055d4R157).

And there is nothing mentioned in the [migration guide](https://github.com/AxaGuilDEv/react-oidc/blob/master/MIGRATION_GUIDE_V4_TO_V5.md) :-(

**Comment by pinggi** [comment]
1. remove the property from the type if not used anymore
```
export type OidcProviderProps = {
   callbackErrorComponent?: ComponentType<any>;
```

2. update the migration guide with the breaking change
People needs to replace `callbackErrorComponent` with `authenticatingErrorComponent`.

**Comment by guillaume-chervet** [comment]
Thank you @pinggi you are right.
Very sorry and thank you very much for the quality of issue!

**Comment by guillaume-chervet** [comment]
Thank you @pinggi, I have removed type and publish a fixed version 2 days ago. I will do that kind of change more carefully now.

**Comment by guillaume-chervet** [comment]
I close the issue @pinggi , thank you very much again for your help. Feel free to reopen it if you need.
