### ISSUE TITLE
is there any way to use this library with pkce disabled?

### ISSUE THREAD

**Issue by TempleOfTemplar** [AxaGuilDEv/react-oidc#818]
I have implicit flow implemented on my backend without pkce( is there any way to use it with this library?

**Comment by guillaume-chervet** [comment]
Hi @TempleOfTemplar, thank yoi for your issue.
I have to make a test, but I am not sure appauthjs implement implicit mode.

**Comment by guillaume-chervet** [comment]
Hi @TempleOfTemplar , i close the issue. Thank you for it.
Imicit mode is a kind of deprecated because it not very secure.
