### ISSUE TITLE
Token endpoint POST request

### ISSUE THREAD

**Issue by hagenderouen** [AxaGuilDEv/react-oidc#821]
### Issue and Steps to Reproduce

I'm using a proxy due to our organizations CORS policy on the authority configuration token endpoint and it is sending a POST request to the endpoint.

### Versions
node v14.19.3
@axa-fr/react-oidc: 5.14.0

### Screenshots
![Screenshot 2022-07-18 172117](https://user-images.githubusercontent.com/15806513/179627421-0ed3f956-0c67-46eb-b2ba-d37af3701489.png)

#### Expected
The token endpoint request to be a GET request. 

#### Actual
The token endpoint request is a POST request.

### Additional Details

- Installed packages: @axa-fr/react-oidc: 5.14.0

Authority configuration snippet:
```
const AUTH_CONFIG: AuthorityConfiguration = {
  authorization_endpoint: `${CONFIG.OIDC_URL}/oauth2/authorize/`,
  token_endpoint: `./proxy/proxy.ashx?${CONFIG.OIDC_URL}/oauth2/token/`,
  userinfo_endpoint: `./proxy/proxy.ashx?${CONFIG.OIDC_URL}/userinfo`,
  end_session_endpoint: `${CONFIG.OIDC_URL}/oauth2/Logout`,
  revocation_endpoint: 'notimplented'
}
```

**Comment by guillaume-chervet** [comment]
Hi @hagenderouen , thank you for your issue.

May your try the last 6.0.0-alpha1? I am not sure but, I think it may work with that version.

**Comment by guillaume-chervet** [comment]
Here a quick migration guide https://github.com/AxaGuilDEv/react-oidc/blob/295776fbfeabde78f6d39ae5326f3a7da5050a11/MIGRATION_GUIDE_V5_TO_V6.md

**Comment by hagenderouen** [comment]
@guillaume-chervet That  worked but, now I'm now receiving a new error on the userinfo endpoint request. 

Bearer error="invalid_token", error_description="MSIS9921: Received invalid UserInfo request. Audience 'microsoft:identityserver:83afd125-770b-4aad-9e15-df407db5b42f' in the access token is not same as the identifier of the UserInfo relying party trust 'urn:microsoft:userinfo'."

**Comment by hagenderouen** [comment]
@guillaume-chervet 
![Screenshot 2022-07-19 104459](https://user-images.githubusercontent.com/15806513/179792994-212293f4-d060-4573-9d47-07252dfce0f4.png)

**Comment by guillaume-chervet** [comment]
It seems good. Are you sure your proxy resend the authorisation header?

**Comment by hagenderouen** [comment]
Not sure how to check this if it's on the request header.

**Comment by hagenderouen** [comment]
Moved to new issue #823 since op was resolved.
