### ISSUE TITLE
Is there a way to stay logged after refreshing a page without refresh token?

### ISSUE THREAD

**Issue by zhien95** [AxaGuilDEv/react-oidc#822]
I'm using 5.14.0 react-oic with OidcServiceWorker. 
Our authentication server does not provide us with a refresh_token, so every time we refresh a page, we are directed to login page again. Is there a way to keep to user signed in after refreshing a page without refresh token?

**Comment by guillaume-chervet** [comment]
Hi @zhien95 ,

If you set up silent signin url and if you oidc provider use cookies correctly. The library will retrieve new accessToken via silent signin method.

You can also test version 6.0.0-alpha1, which manage silentsignin better.

**Comment by guillaume-chervet** [comment]
Here a quick migration guide https://github.com/AxaGuilDEv/react-oidc/blob/295776fbfeabde78f6d39ae5326f3a7da5050a11/MIGRATION_GUIDE_V5_TO_V6.md

**Comment by guillaume-chervet** [comment]
Hi @zhien95 , do you have previous working version ? Which OIDC server are you using? Silent login is a kind of standard.

**Comment by zhien95** [comment]
I don't have a previously working version and the auth server did not set up silent login. Is it possible to prevent OIDC serviceworker from refreshing token when refreshing a page?

**Comment by guillaume-chervet** [comment]
in version 6.0.0-beta1 it does not refresh token when you refresh the page.

https://github.com/AxaGuilDEv/react-oidc/blob/751ff143323031aac376ca63839c8f4dc83e8bc6/MIGRATION_GUIDE_V5_TO_V6.md

**Comment by zhien95** [comment]
hi @guillaume-chervet

I tested 6.0.0-beta1, it's good for our use case but I encountered a small issue have to do an inelegant workaround.

The issue:
Our auth server's 'openid-configuration' doesn't allow Authorization Header and it will response with cors error

The workaround:
Conditionally set Authorization Header by checking if request url includes 'openid-configuration'

It would be more maintainable if there's an domain configuration to exclude Authorization Header. What do you suggest?

**Comment by guillaume-chervet** [comment]
Hi @zhien95 , thank you very much for the feedback. I will inclure the workaround to beta2 version.

**Comment by guillaume-chervet** [comment]
Hi @zhien95 , did you try last version 6? 
It should work for your case.

**Comment by guillaume-chervet** [comment]
I have discover a bug in the previous fixed version that will resolve your case

**Comment by zhien95** [comment]
I'm using v6.0.12 and it fits our use case. Thanks!
