### ISSUE TITLE
[React] OidcTrustedDomains is not copied after installation

### ISSUE THREAD

**Issue by atomicbrainman** [AxaGuilDEv/react-oidc#832]
https://github.com/AxaGuilDEv/react-oidc/blob/020c18bcb13478dff0d54001e0034a22a674957e/packages/react/bin/copy.js#L20

Quickfix:  
`fs.copyFileSync(path.join(__dirname, "..", "dist", trustedDomainsFilename), trustedDomainsDestinationPath);`

**Comment by guillaume-chervet** [comment]
Thank you very much @atomicbrainman , I just push a fix. version will update in a few minutes.

**Comment by atomicbrainman** [comment]
Nice, thank you! 👍
