### ISSUE TITLE
Demo does not work on Firefox 

### ISSUE THREAD

**Issue by olivierlemasle** [AxaGuilDEv/react-oidc#833]
### Issue and Steps to Reproduce

With recent versions of Firefox, the redirection to the application fails with 

```
Impossible de charger « https://demo.duendesoftware.com/connect/token ». Un service worker a communiqué un objet « promise » à FetchEvent.respondWith() qui a été rejeté avec la raison « TypeError: WorkerGlobalScope.fetch: Body has already been consumed. ».
Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://demo.duendesoftware.com/connect/token. Raison : échec de la requête CORS. Code d’état : (null).
```

Very similar to #762; however, the issue is reproduced when using the unmodified react-oidc demo, either [online](https://black-rock-0dc6b0d03.1.azurestaticapps.net/) or locally (`cd react-oidc/packages/react && npm install && npm start`).

### Versions

Reproduced with react-oidc demo on `master` branch (020c18b) and with the online demo https://black-rock-0dc6b0d03.1.azurestaticapps.net/

With **Firefox 103.0.2** (both on Fedora 36 and Windows 10)

### Screenshots

![image](https://user-images.githubusercontent.com/628140/184868025-0a4ace6c-e271-48d6-b717-a1af798ce66f.png)

then redirected to:

![image](https://user-images.githubusercontent.com/628140/184868644-921203c2-90e2-4bfd-96a6-6c8065c8040c.png)

#### Expected

Successful redirection to the application, like when using Chrome

#### Actual

No redirection + error message in console, then redirection to error message (see screenshots)

### Additional Details
No issue with Chrome.

**Comment by guillaume-chervet** [comment]
hi @olivierlemasle , I just fix it, demo will update in few minutes with new version.
Thank you very much and very sorry for this regression.

**Comment by olivierlemasle** [comment]
Thanks @guillaume-chervet 
I confirm that this issue is solved.
