### ISSUE TITLE
Can we omit the post_logout_redirect_uri query param on logout?

### ISSUE THREAD

**Issue by elliotgonzalez-lk** [AxaGuilDEv/react-oidc#834]
### Issue and Steps to Reproduce

Migrating from v3 to v6, and everything is working except the logout flow.  In development we use a custom node oidc provider to mock the production IDP.  Upon logging out, the post_logout_redirect_uri query param is now appended to the URL.  This is causing issues where the mock IDP is complaining that it's not a registered param.  In v3 of react-oidc, omitting this value in the provider config kept it from appearing in the logout URL.  Is there any way to do this in v6?  Thank you in advance.

### Versions
6.0.13

**Comment by guillaume-chervet** [comment]
Hi @elliotgonzalez-lk, thank you very much for your issue.
I can do it and publish it quickly when i will be back from holiday, next week.

**Comment by elliotgonzalez-lk** [comment]
@guillaume-chervet Awesome.  Thank you so much!

**Comment by guillaume-chervet** [comment]
The new version 6.1.0 allow you to set logout(null) and will not set post_logout_redirect_uri query param.

Does it resolve your use case?

**Comment by elliotgonzalez-lk** [comment]
@guillaume-chervet Thank you for making this change.  I've upgraded to 6.1.0 and tried passing `null` to the `logout()`, however, typescript is throwing an error that `null` cannot be passed.

<img width="906" alt="Screen Shot 2022-08-22 at 11 00 03 AM" src="https://user-images.githubusercontent.com/63010253/185953522-f42aff82-ef1c-477e-b415-2296d961bbc6.png">

**Comment by guillaume-chervet** [comment]
hi @elliotgonzalez-lk , thank you for your quick feedback, I pushed a fix version 6.3.1

**Comment by elliotgonzalez-lk** [comment]
@guillaume-chervet. Great, thanks.  Everything working as expected, thanks again.

**Comment by guillaume-chervet** [comment]
Thank you again for your issue. It help us to build a better library. May we close the issue ?

**Comment by elliotgonzalez-lk** [comment]
Yes, you may close the issue.
