### ISSUE TITLE
Logout user when session is removed from provider

### ISSUE THREAD

**Issue by hugo1707** [AxaGuilDEv/react-oidc#844]
Hello,

If I manually remove the user session from the auth provider (Keycloak), the user remains logged in the app (See images).

Images:
![When the user is logged in](https://user-images.githubusercontent.com/33438344/187047189-0134b27c-a968-48fb-a8f1-33cbd67d2ebf.png)

![After session is removed](https://user-images.githubusercontent.com/33438344/187047224-daa59d7a-3459-44b0-b0f1-d9000abaff72.png)

As you see, the username is not showing anymore (because cannot get user data from provider anymore).

Also, this error is thrown: 
![Web console](https://user-images.githubusercontent.com/33438344/187047266-12e535ae-31ef-4783-8e0b-a7d8f1ca7d52.png)

How can I catch the error and logout the user?

Thanks.

**Comment by guillaume-chervet** [comment]
Hi @hugo1707 , thank you for your issue.

What you need is called singleLogout. You can activate it by setting property monitorSession to true. You will find more information  here https://github.com/AxaGuilDEv/react-oidc/blob/master/MIGRATION_GUIDE_V5_TO_V6.md.

The drawbak is it will work on safari only if your oidc server share the save domain than you client application. This because of cookies tier blocked.

For example:
Https://app.axa.fr
Https://oidc.axa.fr
This will make it work on safari

**Comment by olivierlemasle** [comment]
@guillaume-chervet BTW, please note that in https://github.com/AxaGuilDEv/react-oidc/blob/master/MIGRATION_GUIDE_V5_TO_V6.md, `monitor_session` is still documented to have `true` as its default value (in c609c1c929, you updated `packages/react/README.md` but not that file)

**Comment by guillaume-chervet** [comment]
Thank youh @olivierlemasle for the feedback. I will fix this. I have started to write more documentation about this.

**Comment by hugo1707** [comment]
Sorry for the delay.

I can't check the monitor session feature **right now**, but I will check it tomorrow.

Thank you.

**Comment by hugo1707** [comment]
Did not work.

Here is my configuration if it helps:

```javascript
const configuration: OidcConfiguration = {
  authority: "http://localhost:8080/realms/test-realm",
  client_id: "test-client",
  scope: "openid profile email",
  redirect_uri: "http://localhost:3000/authentication/callback", // now this callback must be declared to your OIDC server, manage callback information after login
  monitor_session: true,
};

```

**Comment by guillaume-chervet** [comment]
Hi @hugo1707 , monitor session use     silent_redirect_uri: window.location.origin+'/authentication/silent-callback',
Behind the s'en
You need to configure it to make it works.

I may add a warning message for your case.

**Comment by guillaume-chervet** [comment]
Hi @hugo1707 , monitor session use     silent_redirect_uri: window.location.origin+'/authentication/silent-callback',
Behind the seen. 
You need to configure it to make it works.

I may add a warning message for your case.

**Comment by guillaume-chervet** [comment]
Hi @hugo1707 , does it work for you with silent signin?
