### ISSUE TITLE
Get API using useOidcAccessToken and Axios is unauthorized

### ISSUE THREAD

**Issue by dwprstyo** [AxaGuilDEv/react-oidc#846]
Issue and Steps to Reproduce

i'm trying to GET data from an API that should be authorized,
so i used useOidcAccessToken to get access token but i didn't get that access token

Versions
5.10.1

Screenshots
![access token oidc](https://user-images.githubusercontent.com/97303733/187416241-47392f5d-089c-49bc-987e-6ac2bba41d8f.png)

Expected
-I can be authorized
-I get access token

Actual
-unauthorized
-I got this "ACCESS_TOKEN_SECURED_BY_OIDC_SERVICE_WORKER_default"

**Comment by guillaume-chervet** [comment]
Hi @dwprstyo , thank you for your issue.
If you can you may update to v6. You won't encounter breaking change.

Did you set up the trustedDomains.js file? The service worker use it to know which url it can inject the accessToken.

**Comment by dwprstyo** [comment]
@guillaume-chervet , thank you for the reply

it's updated, and also i did set up the trustedDomain.js before
and still got "ACCESS_TOKEN_SECURED_BY_OIDC_SERVICE_WORKER_default"

**Comment by guillaume-chervet** [comment]
Hi @dwprstyo , may you try all test desbribe in that issue ? 
#843

What does look like your configuration? What is you oidc provider?

**Comment by dwprstyo** [comment]
![accest token 3](https://user-images.githubusercontent.com/97303733/187619972-18216dbc-2987-4a3b-8f69-e27cc1cc5909.png)
![accest token 4](https://user-images.githubusercontent.com/97303733/187620025-0e73b7d6-a546-45b2-b9d0-5b1608173040.png)
 
these are my configuration and my set up in oidcTrustDomain.js

**Comment by guillaume-chervet** [comment]
Hi @dwprstyo ,
Thank you for your informations.
Did you try to remove the service worker like explain in #843 ?

**Comment by dwprstyo** [comment]
Hi @guillaume-chervet 

I just tried to remove the service worker and it worked
i got the access token and it's authorized
thank youu 👍
