### ISSUE TITLE
Error fetching OidcKeepAliveServiceWorker.json 

### ISSUE THREAD

**Issue by beanovar** [AxaGuilDEv/react-oidc#851]
If you keep the demo website (https://black-rock-0dc6b0d03.1.azurestaticapps.net/profile) open for long enough (around 5 minutes), then the console will eventually print the following errors: 

![image](https://user-images.githubusercontent.com/113195580/189384633-1882eb0c-92b6-4b40-9913-cbdaa19dfb2a.png)

Even if these errors don't cause any real issue, can this be improved at all?

**Comment by guillaume-chervet** [comment]
Hi @beanovar , thank you for the issue.
It may be improve. This error do not cause any problem. The aim of this fetch is to keep the ServiceWorker alive the more longer as possible. It is a trick that i think that it can be improved. I have tested some techniques but i think some to find may be better.
