### ISSUE TITLE
npm package must not be shipped with TypeScript source code

### ISSUE THREAD

**Issue by ryanelian** [AxaGuilDEv/react-oidc#854]
### Issue and Steps to Reproduce

npm package **MUST NOT** be shipped with TypeScript source code and instead ship a bundled JS file and TypeScript definition files instead (`.d.ts` files)

This is important because importing the module from the package causes the TypeScript compiler to link against the source code inside the npm package, which is not desirable:

```ts
import { OidcProvider } from '@axa-fr/react-oidc';
```

![image](https://user-images.githubusercontent.com/8892187/189811875-33234235-ecce-45f1-887e-fefadb50351a.png)

Which causes the project to pick up errors from transitive dependency: 

![image](https://user-images.githubusercontent.com/8892187/189814329-f10f288d-f5bb-4a24-885e-886d07fcd115.png)

Notice that the TypeScript compile errors came from the `@openid/appauth` project, not the `react-oidc` code itself.

### Versions

6.5.5

### Screenshots

Provided above

#### Expected

Importing from `react-oidc` project resolves to the TypeScript definition files (`.d.ts`) not the `.ts` source code themselves

#### Actual

Importing from `react-oidc` project resolves to the  `.ts` source code of the project itself, which is not desirable

### Additional Details

> A library author might have a faulty import or might only provide typescript files for his library and not transpiled code.

> libraries shouldn't publish *.ts files,

https://github.com/microsoft/TypeScript/issues/40426

- Installed packages:

TypeScript 4.8.3

**Comment by guillaume-chervet** [comment]
Thank you very much @ryanelian for these rich issue and bringing all that information.

I have to study a little bit how to resolve this.

**Comment by ryanelian** [comment]
> Thank you very much @ryanelian for these rich issue and bringing all that information.

You're welcome! Thanks for developing such a nice library.

Our company is integrating this library into [our Next.js new project template](https://github.com/accelist/nextjs-starter) so we'll probably find more issues down the line.

> I have to study a little bit how to resolve this.

- Doesn't just running `tsc` already generate the much-needed files? For example:

![image](https://user-images.githubusercontent.com/8892187/189976894-08674550-7f63-4f05-9ad8-19badec68d69.png)

![image](https://user-images.githubusercontent.com/8892187/189977855-281ca017-660c-42a8-aa53-a8e6169149ab.png)

- And then modify the `package.json` to point the `types` to the `dist/index.d.ts` file:

> Reference: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

- And then modify the files included in the package itself:

![image](https://user-images.githubusercontent.com/8892187/189979499-55749883-3f8e-4bc4-a83f-687e17202f7d.png)

Then the package should be created without TypeScript source code and purely just JS and declaration files.

Sample package created:

[axa-fr-react-oidc-6.5.5.tgz.zip](https://github.com/AxaGuilDEv/react-oidc/files/9559778/axa-fr-react-oidc-6.5.5.tgz.zip)

**Comment by ryanelian** [comment]
Also, something kind of related to producing JS output for the package...

![image](https://user-images.githubusercontent.com/8892187/189981812-b5022dd9-a6c7-4f85-b72b-3cba87c1b8ed.png)

If you do this, the package would be optimized for build systems (since almost everyone are writing React codes using Babel / Next.js / webpack / build tools) anyway.

ES2015 output will reduce the package size. Babel / etc. usually consume them to produce ES5 codes if needed anyway.

ESNext module will ensure that bundlers such as webpack / etc. can perform tree-shaking optimization (removing codes that aren't really used).

**Comment by guillaume-chervet** [comment]
hi @ryanelian, it seems too work pretty well thank you very much :)

**Comment by ryanelian** [comment]
> hi @ryanelian, it seems too work pretty well thank you very much :)

Hi again. Before I get mass-lynched by the other users of the library, I think I need to apologize 😅 

The part of changes where you don't ship the TypeScript code works brilliantly. So there's one problem out of the way.  👍 

----

However... The part of the changes where the TypeScript target and module are changed from `ES5` and `CommonJS` to `ES2015` and `ESNext`...

✅ Does not show error in VS Code / `tsc`
✅ Does not show error when the Next.js is being run
✅ Does not show error when the OIDC component was loaded on browser-side only (when using Next.js dynamic ssr=false)
☢️☠❗ Explodes magnificently when the OIDC component is loaded on the server-side (SSR)

```sh
[dev:nextjs] Error [ERR_REQUIRE_ESM]: require() of ES Module D:\VS\accelist-nextjs-starter\node_modules\@axa-fr\react-oidc\dist\index.js from D:\VS\accelist-nextjs-starter\.next\server\pages\_app.js not supported.
[dev:nextjs] Instead change the require of index.js in D:\VS\accelist-nextjs-starter\.next\server\pages\_app.js to a dynamic import() which is available in all CommonJS modules.
[dev:nextjs]     at Object.@axa-fr/react-oidc (D:\VS\accelist-nextjs-starter\.next\server\pages\_app.js:140:18)
[dev:nextjs]     at __webpack_require__ (D:\VS\accelist-nextjs-starter\.next\server\webpack-runtime.js:33:42)
[dev:nextjs]     at eval (webpack-internal:///./components/NextJsOidcProvider.tsx:9:76)
[dev:nextjs]     at Object../components/NextJsOidcProvider.tsx (D:\VS\accelist-nextjs-starter\.next\server\pages\_app.js:65:1)
[dev:nextjs]     at __webpack_require__ (D:\VS\accelist-nextjs-starter\.next\server\webpack-runtime.js:33:42)
[dev:nextjs]     at eval (webpack-internal:///./pages/_app.tsx:18:88)
[dev:nextjs]     at Function.__webpack_require__.a (D:\VS\accelist-nextjs-starter\.next\server\webpack-runtime.js:97:13)
[dev:nextjs]     at eval (webpack-internal:///./pages/_app.tsx:1:21)
[dev:nextjs]     at Object../pages/_app.tsx (D:\VS\accelist-nextjs-starter\.next\server\pages\_app.js:109:1)
[dev:nextjs]     at __webpack_require__ (D:\VS\accelist-nextjs-starter\.next\server\webpack-runtime.js:33:42)
[dev:nextjs]     at __webpack_exec__ (D:\VS\accelist-nextjs-starter\.next\server\pages\_app.js:238:39)
[dev:nextjs]     at D:\VS\accelist-nextjs-starter\.next\server\pages\_app.js:239:28
[dev:nextjs]     at Object.<anonymous> (D:\VS\accelist-nextjs-starter\.next\server\pages\_app.js:242:3)
[dev:nextjs]     at Object.requirePage (D:\VS\accelist-nextjs-starter\node_modules\next\dist\server\require.js:58:12)
[dev:nextjs]     at D:\VS\accelist-nextjs-starter\node_modules\next\dist\server\load-components.js:57:54
[dev:nextjs]     at runMicrotasks (<anonymous>)
[dev:nextjs]     at async Promise.all (index 1)
[dev:nextjs]     at async Object.loadComponents (D:\VS\accelist-nextjs-starter\node_modules\next\dist\server\load-components.js:55:33)
[dev:nextjs]     at async DevServer.findPageComponents (D:\VS\accelist-nextjs-starter\node_modules\next\dist\server\next-server.js:545:36) {
[dev:nextjs]   code: 'ERR_REQUIRE_ESM'
[dev:nextjs] }
```

So you should probably revert the part where you modified the `tsconfig.json` back to `ES5` and `CommonJS`

Apparently the server-side of the Next.js still imports using `require` unlike the browser-side which supports ESM.

I apologize for not testing the change I suggested thoroughly and I have no excuse. 🙏

**Comment by guillaume-chervet** [comment]
Thank you again @ryanelian for your awesome feedback. I have revert to CommonJS and published a fixed version.
