### ISSUE TITLE
if using service worker, b64 decode of token in extractTokenPayload of oidcserviceworker.js fails for some tokens

### ISSUE THREAD

**Issue by fffan64** [AxaGuilDEv/react-oidc#863]
### Issue and Steps to Reproduce
if using token like following one :
```
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtleXN0b3JlLUNIQU5HRS1NRSJ9.eyJzdWIiOiJ0ZXN0RXh0ZXJuYWwiLCJmYW1pbHlfbmFtZSI6IuOCouOCr-OCtSIsImdpdmVuX25hbWUiOiLlpKrpg44iLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1aWQiOiJ0ZXN0RXh0ZXJuYWwiLCJ1c2VyX3R5cGUiOiJleHRlcm5hbCIsImF1dGhfdGltZSI6MTY2MzIyMTczOCwibm9uY2UiOiJtbTRsRzNUNU5jbzAiLCJhdF9oYXNoIjoieGlfemNwYlMwZFY5MG45OUhPa21ldyIsImF1ZCI6ImZvbyIsImV4cCI6MTY2MzIyNTQwMSwiaWF0IjoxNjYzMjIxODAxLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDIifQ.xQa9pfcfqO14BaEIF6UZQxe3i7mzqo0D4HxXnXgTMBAJEe2Q5424_nW5TIiGzcrD_yWG6yusv6hDauFkcRDBNjmHiyyqR3yESfCN3SXwTQvi7wIPiVvn92rynbU09EpPQcff9_5QCIFx9h7K-W91J-1WPnI3sxL6AwLfb-KIjoS_5UV1szW4IL6MeMXypbgUpAZksvlKkQM78qPgmC64KqdxKhYDxt8kFZjyg4jyFf_oIGp7FLDQyGA8u9B21gndrJEtRkKXB8Z3A2s5Ujv3cDpyV_gQa3OL1i42Ev7rU86OXCFFJsO71kL3PDKF9vg3n9m9DvClQhLTUIAwRGJ7hg
```

the decode of token in extractTokenPayload function of oidcserviceworker.js file fails in atob function call saying it is not encoded properly.

### Versions

latest

### Screenshots

-

#### Expected

decode of token should work

#### Actual

Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### Additional Details

A Solution would be: 

It is a unicode problem cf here https://stackoverflow.com/a/30106551/5277071
the 8th solution from this post: https://www.anycodings.com/1questions/145912/how-to-decode-jwt-token-in-javascript-without-using-a-library is good to solve the issue.

Following code solve the issue:
```javascript
const b64DecodeUnicode = (str) =>
  decodeURIComponent(Array.prototype.map.call(atob(str), (c) => '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2)).join(''));
const parseJwt = (token) => JSON.parse(b64DecodeUnicode(token.split('.')[1].replace('-', '+').replace('_', '/')));
const extractTokenPayload = (accessToken) => {
  try {
    return parseJwt(accessToken);
  } catch (e) {
    console.warn(e);
  }
  return null;
};
```

**Comment by fffan64** [comment]
while this fix the parsing of token correctly, i now see following in console logs:

<img width="967" alt="image" src="https://user-images.githubusercontent.com/35838907/191143772-81c7f3e4-bf72-4dc6-99b4-80ca09e9c61e.png">

it seems str is not a `string` in function `countLetter` ?

**Comment by fffan64** [comment]
en fait le prob est dans `packages/react/src/oidc/vanilla/parseTokens.ts` (je testais sans le service worker)
<img width="471" alt="image" src="https://user-images.githubusercontent.com/35838907/191149541-0bc73a31-a327-40b0-9890-99f16c2cf4b5.png">

**Comment by guillaume-chervet** [comment]
Do you have an imput sample of that function just before the crash? I would be able to set up à unit test on it.

Thank you again @fffan64 ^^ I hope your going well in Japan 😜

**Comment by fffan64** [comment]
@guillaume-chervet , problem is linked with my other problem https://github.com/AxaGuilDEv/react-oidc/issues/867, i can't debug properly :D

**Comment by fffan64** [comment]
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/35838907/191180855-2e512973-8e05-4241-91b2-9ad368fcd9da.png">
it is called 2 times, one of which str is an object and not a string :D

**Comment by fffan64** [comment]
Error is here : https://github.com/AxaGuilDEv/react-oidc/blob/7250657ef33326115d265cbd60c28063c8a3bf81/packages/react/src/oidc/vanilla/parseTokens.ts#L44

passing the whole object instead of token (.accessToken i believe) only

**Comment by guillaume-chervet** [comment]
Thank you very much @fffan64 , the version 6.6.3 fixed it !

**Comment by guillaume-chervet** [comment]
Does the bug fixed for yoy @fffan64 ?
Thank you very much.
May we close the issues?

**Comment by fffan64** [comment]
sure, works fine ! thanks again
