### ISSUE TITLE
add source maps to pkg

### ISSUE THREAD

**Issue by fffan64** [AxaGuilDEv/react-oidc#867]
### Issue and Steps to Reproduce

when using react script > 5 and starting react local dev server, following warnings occurs:

```shell
[dev:react        ] Starting the development server...
[dev:react        ] 
[dev:react        ] Compiled with warnings.
[dev:react        ] 
[dev:react        ] Failed to parse source map from '/Users/jonathan.vacherat/Documents/CODING/nodejs/agpo-cloud-web/node_modules/@axa-fr/react-oidc/src/oidc/FetchToken.tsx' file: Error: ENOENT: no such file or directory, open '/Users/jonathan.vacherat/Documents/CODING/nodejs/agpo-cloud-web/node_modules/@axa-fr/react-oidc/src/oidc/FetchToken.tsx'
[dev:react        ] 
[dev:react        ] Failed to parse source map from '/Users/jonathan.vacherat/Documents/CODING/nodejs/agpo-cloud-web/node_modules/@axa-fr/react-oidc/src/oidc/OidcProvider.tsx' file: Error: ENOENT: no such file or directory, open '/Users/jonathan.vacherat/Documents/CODING/nodejs/agpo-cloud-web/node_modules/@axa-fr/react-oidc/src/oidc/OidcProvider.tsx'

and so with all files of the pkg
```

it seems the source are not included in pkg so loading of source map fails.

### Versions
latest

#### Expected
No warning and proper debug with source maps

#### Actual
Warnings, cant debug non minified code

### Additional Details
similar issue on random other pkg online : https://github.com/mebjas/html5-qrcode/issues/396

**Comment by guillaume-chervet** [comment]
I think the last version fixed it @fffan64 . Thank you again for your issue.

**Comment by fffan64** [comment]
i'm using an old version of react-script, v 4.0.3
the issue is still there but i believe if using 5.0.1 it will be resolved.

if it works for you with latest react-script, then it is ok, you can mark as closed, thanks !

**Comment by guillaume-chervet** [comment]
Thank you @fffan64
