### ISSUE TITLE
revoke token on logout

### ISSUE THREAD

**Issue by fffan64** [AxaGuilDEv/react-oidc#869]
it is on the enhancement wishlist :D

can we have the revoke token on logout back like in v3 ? it was quite convenient actually.

thanks !

**Comment by guillaume-chervet** [comment]
Hi @fffan64 , thank you again for your issue.
Definitely yes, it is a very Nice thing to add !

**Comment by fffan64** [comment]
Hello @guillaume-chervet, i don't want to be annoying, but my current project needs it (as it was part of v3, before i migrate) so can i ask you a rough ETA for this feature ? again, thank you :) 🙏

**Comment by guillaume-chervet** [comment]
Hi @fffan64 , i will try to implement it quickly. It will be a Nice feature.

**Comment by guillaume-chervet** [comment]
Hi @fffan64 , i published version 6.6.9-alpha0 for you :)

**Comment by fffan64** [comment]
thank you !
