### ISSUE TITLE
allow to choose which token lifetime to base the timer for renew token on 

### ISSUE THREAD

**Issue by fffan64** [AxaGuilDEv/react-oidc#877]
if for example, access token is valid for 1h and id token is valid for 5 minutes, then the timer to renew token automatically is based on 5 minutes, thus, renewing access token every <5min even though access token is still valid for 55minutes, resulting in multiple refresh token queries to oidc server.

=> allow to choose wich token lifetime base the timer on

BUT this will probably raise another problem, specifically during logout, because logout use id token to be able to logout and as it will be expired, not sure what will happen ?

**Comment by fffan64** [comment]
got an interesting interaction about what needs to be done:

> For logout to work with a post_logout_redirect_uri, MAAM needs to know which client_id initiates the logout request. Otherwise it cannot obtain which redirect_uris are whitelisted, so it cannot safely redirect there.
> 
>To know which client_id initiates the request, MAAM accepts either:
an “id_token_hint” which has previously been obtained by that client, so with the client_id as “audience” (as standardized by OIDC)
or directly a “client_id” parameter (was non-standardised in the draft spec at the time I implemented it, but it is now standardized in the final spec!)
https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout
> 
>So here they use id_token_hint. But the ID Token doesn’t need to valid (as “not yet expired”) for it to work. MAAM indeed gives back short living tokens (5 minutes), but there is no reason for the app to use that lifetime as reference for the user session. Quote from the spec:
> 
>When an id_token_hint parameter is present, the OP MUST validate that it was the issuer of the ID Token. The OP SHOULD accept ID Tokens when the RP identified by the ID Token's aud claim and/or sid claim has a current session or had a recent session at the OP, even when the exp time has passed.

**Comment by guillaume-chervet** [comment]
Done  by https://github.com/AxaGuilDEv/react-oidc/commit/aa68e04537b083978b350931120bc7a99217f696

It work well on my app :)

**Comment by guillaume-chervet** [comment]
But I have exactly the same "exp" date on access_token and id_token

**Comment by fffan64** [comment]
i confirm it is working as expected ! thank you so much :)
