### ISSUE TITLE
Testing silent login

### ISSUE THREAD

**Issue by beanovar** [AxaGuilDEv/react-oidc#880]
Hi - I am not sure my silent login is working. My understanding is that this happens if the service worker is killed by the browser? 

Is there a way to simulate this happening? I have tried stopping and unregistering the service worker from dev tools but the library seems to just fetch a new token via silent refresh / refresh token flow (successfully), rather than do a silent login which is what I need to test?

Thanks

**Comment by guillaume-chervet** [comment]
Hi @beanovar Thank you for the issue :)
Silent login trigger in fact a silent signin. It the same.

**Comment by guillaume-chervet** [comment]
When you kill the service worker, the silent signin/login use cookies via an iframe to retrieve again new tokens.
Your test is passing. The drawback of silent login is taht now you need to be on the same domain than oidc server on safari because cross domain cookies are blocked by default.

**Comment by beanovar** [comment]
Thanks ! Confirmed.
