### ISSUE TITLE
404 error on /authentication/callback after npm run build

### ISSUE THREAD

**Issue by stevemarsbar** [AxaGuilDEv/react-oidc#884]
### Issue and Steps to Reproduce

I've cloned the latest repo
run npm run buid under /react-oidc/packages/react/*
hosted the /build folder 

### Versions

commit 5b05383ba9f0718e266009df85aaf73a307827d9
Author: GitHub <github-action@bot.com>
Date:   Fri Oct 14 14:48:19 2022 +0000

### Screenshots

![404](https://user-images.githubusercontent.com/16427712/196630181-1b0dce18-151f-4919-b7dd-93c87a2b6085.png)

#### Expected

User profile page?

#### Actual

404 Error

### Additional Details

- Installed packages:

**Comment by stevemarsbar** [comment]
Can someone help please? Looks like https://github.com/AxaGuilDEv/react-oidc/issues/599

**Comment by Alanm63** [comment]
Hi. I am not familiar with Apache but I had the same problem you describe in IIS. I solved it by adding a URL rewrite rule that redirects to /index.html. Then it worked as expected.

**Comment by stevemarsbar** [comment]
Thanks both, added a rewrite rule in apache
