### ISSUE TITLE
infinite loop when use  "/" as callback url

### ISSUE THREAD

**Issue by ezhuca** [AxaGuilDEv/react-oidc#885]
### Issue and Steps to Reproduce

When I use "/" as call back uri,  it failed to detect the "code" and ended up infinite loop.
Please advise how to make this work or we have to add a dedicated call back uri

### Versions
6.9.1
### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
hi @ezhuca , thank you for your issue.

You may want use the hash configuration.

Like in the exemple below:

`
export const configurationIdentityServerWithHash = {
    client_id: 'interactive.public.short',
    redirect_uri: window.location.origin+'#authentication-callback',
    silent_redirect_uri: window.location.origin+'#authentication-silent-callback',
    silent_login_uri: window.location.origin+'#authentication-silent-login',
    scope: 'openid profile email api offline_access',
    authority: 'https://demo.duendesoftware.com',
    refresh_time_before_tokens_expiration_in_second: 10,
    service_worker_relative_url:'/OidcServiceWorker.js',
    service_worker_only: false,
};
`

**Comment by ezhuca** [comment]
@guillaume-chervet Thanks for advice. will give it a try.
