### ISSUE TITLE
After user validation, the redirection doesn't always work on cellphones.

### ISSUE THREAD

**Issue by felipesmedeiros** [AxaGuilDEv/react-oidc#888]
> If you make your access using iOS with safari or even Chrome, after the login it goes to the Authentication Complete screen and doesn't go forward. If you refresh the page there, it return Error Authentication, even on the example project given. I got this behavior using cellphones in general. The error is loginCallbackAsync_error(). Any idea?

**Comment by guillaume-chervet** [comment]
Hi @, thank you very much for the your issue. 

Are you using the service worker mode?

**Comment by felipesmedeiros** [comment]
My configuration doesn't force it, but yes it's using it. Like I said the example url given on your documentation has the same issue, I believe it's using it as well.

**Comment by guillaume-chervet** [comment]
I have to find an iPhone.
I can set up a workaround but it will be a litle less secure.
I need to find a way to improve service worker lifetime on iPhone.

**Comment by felipesmedeiros** [comment]
Being sincere, for my usage not being on service worker is not a problem. Before I was using the oidc-js, not even react, it's already an improvement. Thank you a lot for this library actually. Is there another communication channel that's not necessarily for issues?

**Comment by guillaume-chervet** [comment]
Thank you @felipesmedeiros. If you do not necessary need service worker.

You can just disable it, like that :

```javascript
const configuration = {
  client_id: 'interactive.public.short',
  redirect_uri: window.location.origin + '/authentication/callback',
  silent_redirect_uri: window.location.origin + '/authentication/silent-callback', 
  scope: 'openid profile email api offline_access',
  authority: 'https://demo.duendesoftware.com'
};

```

I'am pretty sure, it will work on iphone whithout the ServiceWorker.

It would be very cool to help me to test :)

I have to create a slack or a discord :]

**Comment by felipesmedeiros** [comment]
I'll try on Monday with the silent signin, I'm pretty sure I tried and it didn't work...but let's see. About the tests, setup a discord where we can chat easier, so we can see how we do it. I'd be happy to help.

**Comment by felipesmedeiros** [comment]
Hello there, this is my configuration: 
` client_id: process.env.REACT_APP_CLIENT_ID ?? '',
  redirect_uri: `${process.env.REACT_APP_BASE_URL}/${process.env.REACT_APP_SIGNIN_URL}`,
  silent_redirect_uri: `${process.env.REACT_APP_BASE_URL}/${process.env.REACT_APP_SILENT_SIGNIN_URL}`,
  scope: process.env.REACT_APP_SCOPE ?? '',
  authority: process.env.REACT_APP_AUTHORITY_URL ?? '',
  request_type: 'code',
  refresh_time_before_tokens_expiration_in_second: 10,
  post_logout_redirect_uri: `${process.env.REACT_APP_BASE_URL}/${process.env.REACT_APP_SIGNOUT_URL}`,
  service_worker_relative_url: '/OidcServiceWorker.js',
  service_worker_only: false,
  monitor_session: false,`

Without the last 3 lines it straight up doesn't work same behavior as on iphone. Get stuck on this page 
![image](https://user-images.githubusercontent.com/22086915/197535269-8f6d743b-d463-4261-b346-21c9c5634dd2.png)
or error one.

**Comment by felipesmedeiros** [comment]
Apparently it work, I removed the ServiceWorker.js and changed the configuration. Thank you a lot, if it has any other issue regarding this I'll let you know. And, again, if you need help testing on iOS, just let me know.

**Comment by guillaume-chervet** [comment]
Thank you @felipesmedeiros for your feedback :)

**Comment by guillaume-chervet** [comment]
Hi @felipesmedeiros , may you help me?

Does this version work on iPhone ? 
https://black-rock-0dc6b0d03-897.westeurope.1.azurestaticapps.net/

**Comment by felipesmedeiros** [comment]
Hey @guillaume-chervet  I was able to login, when I went of the site and came back on the profile it didn't login by itself, I needed to go back to the login screen and click on Login. Doing that it logged me in autmatically, and was not able to refresh the token with the silent sign-ín. I don't know if I was clear enough, you can ask for more information. See you! I'm using a iPhone 7 with the latest iOS.

**Comment by guillaume-chervet** [comment]
Hi @felipesmedeiros , thank you very much for your feedback!
I published the version. Silent signin on safari does not work on different domain because of cookie tier blocked by safari.

**Comment by guillaume-chervet** [comment]
Hi @felipesmedeiros,
I published the version. The demo work with iphone => https://black-rock-0dc6b0d03.1.azurestaticapps.net/
with short session because on safari silentsignin work only with oidc server on the same domain than the web application.

**Comment by felipesmedeiros** [comment]
Thank you so much, for the time. I'm using the library without any ServiceWorker, and it's working perfectly fine. I'll keep using like that. Do you need me to do any test?

**Comment by guillaume-chervet** [comment]
Hi @felipesmedeiros thank you for you feedbacks. I close the issue but feel free to reopen it.
