### ISSUE TITLE
configurationIdentityServerWithoutDiscovery with PKCE

### ISSUE THREAD

**Issue by stevemarsbar** [AxaGuilDEv/react-oidc#896]
### Issue and Steps to Reproduce

Hi,

I'm really struggling to get PKCE working. Is there a way to turn it on when using configurationIdentityServerWithoutDiscovery?

I can't get the "authorize" request to send the code_challenge_method and code_challenge values.

Thanks

Steve

**Comment by stevemarsbar** [comment]
When it calls authorize:
![request](https://user-images.githubusercontent.com/16427712/198615359-6e502924-3447-4228-944c-a3e10fc678d7.png)

Response on the Callback URL:
![response](https://user-images.githubusercontent.com/16427712/198615845-e1a6c1d0-3c7a-43c6-9564-d62591007014.png)

**Comment by guillaume-chervet** [comment]
Hi @stevemarsbar , thank you for the issue. 
What does look like your configuration ? 
What is your oidc provider ?

I am in holiday whithout computer for 1 week.

It may be a configuration issue because i have seen this works recently.

**Comment by stevemarsbar** [comment]
Hi @guillaume-chervet,

Enjoy your week off!

I'm using Hashicorp Vault as the OIDC provider with this configuration:

`export const configurationIdentityServerWithoutDiscovery = {
    client_id: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    redirect_uri: window.location.origin+'/authentication/callback',
    silent_redirect_uri: window.location.origin+'/authentication/silent-callback',
    scope: 'openid',
    authority: 'http://10.1.125.1/v1/identity/oidc/provider/provider-oidc',
    authority_configuration: {
        authorization_endpoint: 'http://10.1.125.1/ui/vault/identity/oidc/provider/provider-oidc/authorize',
        token_endpoint: 'http://10.1.125.1/v1/identity/oidc/provider/provider-oidc/connect/token',
        userinfo_endpoint: 'http://10.1.125.1/v1/identity/oidc/provider/provider-oidc/connect/userinfo',
        end_session_endpoint: 'http://10.1.125.1/v1/identity/oidc/provider/provider-oidc/connect/endsession',
        revocation_endpoint: 'http://10.1.125.1/v1/identity/oidc/provider/provider-oidc/connect/revocation',
        check_session_iframe: 'http://10.1.125.1/v1/identity/oidc/provider/provider-oidc/connect/checksession',
        issuer: ''
    },
    refresh_time_before_tokens_expiration_in_second: 10,
    service_worker_relative_url:'/OidcServiceWorker.js',
    service_worker_only: false,
};`

**Comment by guillaume-chervet** [comment]
Thank you @stevemarsbar . I'am not sure but i think you need to set up more than empty string for the issuer

**Comment by stevemarsbar** [comment]
Hi, @guillaume-chervet 

I added issuer in. I've also added HTTPS certs but still get the same behaviour.

Steve

**Comment by stevemarsbar** [comment]
Hi @guillaume-chervet 

This looks like it was an apache issue with the certs. All working now, sorry

Steve
