### ISSUE TITLE
CORS error occurred when fetching access token

### ISSUE THREAD

**Issue by fungcheukyin-TeamLab** [AxaGuilDEv/react-oidc#899]
### Issue and Steps to Reproduce
I tried to do a login action with the Google Auth api but the below error occurred when the authorization callback trying to fetch the access token from google token endpoint

`Access to fetch at 'https://accounts.google.com/o/oauth2/v2/token' from origin 'http://localhost:4001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.` 

``` javascript
const googleConfig: OidcConfiguration = {
  authority: 'https://accounts.google.com/o/oauth2/v2',
  client_id:
    {client_id}
  redirect_uri: 'http://localhost:4001/dev/auth/oauth_redirect',
  scope: 'openid',
  service_worker_only: false,
  token_request_extras: {
    client_secret: {client_secret}
  },
  authority_configuration: {
    issuer: 'https://accounts.google.com/o/oauth2/v2',
    authorization_endpoint: 'https://accounts.google.com/o/oauth2/v2/auth',
    token_endpoint: 'https://accounts.google.com/o/oauth2/v2/token',
    end_session_endpoint: '',
    revocation_endpoint: '',
  },
};
```

### Versions
NextJS

#### Expected
success response returned from token endpoint

#### Actual
CORS error occurred

### Additional Details

- Installed packages: 6.10.9-alpha0

**Comment by guillaume-chervet** [comment]
Hi @fungcheukyin-TeamLab,  i did not manage to make google api work with localhost. You may configure you host.config in order to get a real domain name in local.

**Comment by guillaume-chervet** [comment]
I am using that configuration which is working https://github.com/AxaGuilDEv/react-oidc/blob/2ef1d14f9f7cd88130e592d31c08d02a0e44ff44/packages/react/src/configurations.ts#L61

**Comment by fungcheukyin-TeamLab** [comment]
@guillaume-chervet 
Thank you for your advise!
I will try out that configuration later on.
