### ISSUE TITLE
Upgrading from 6.0.12 to 6.10.19 error

### ISSUE THREAD

**Issue by kelvin-homann** [AxaGuilDEv/react-oidc#910]
I just tried to upgrade from 6.0.12 to 6.10.19 and im getting greeted with the following error:

DOMException: Failed to execute 'postMessage' on 'ServiceWorker': Storage object could not be cloned.

![image](https://user-images.githubusercontent.com/29820609/203029410-1346fd62-c689-4964-b94a-563e1cbe41ce.png)

Is there something i should consider when upgrading? I can see the OidcServiceWorker.js file changed completely

**Comment by guillaume-chervet** [comment]
@kelvin-homann , thank you for you issue.

This is a really strange error, i never seen it before.

Do you still have the error after a page refresh ?

**Comment by kelvin-homann** [comment]
Unfortunately yes, this is the config we are using: 

```typescript
const port = window.location.port ? `:${window.location.port}` : ''
const baseUrl = `${window.location.protocol}//${window.location.hostname}${port}`

export const configurationKeycloak: OidcConfiguration = {
  client_id: window._marketrace_.CLIENT_ID ?? 'mr-frontend',
  redirect_uri: `${baseUrl}/authentication/callback`,
  silent_redirect_uri: `${baseUrl}/authentication/silent`,
  scope: 'openid profile email',
  authority: authority,
  service_worker_relative_url: '/OidcServiceWorker.js',
  service_worker_only: true,
  storage: sessionStorage
}
```

**Comment by kelvin-homann** [comment]
I managed to reproduce the error in the packages/react project with the following config: 

![image](https://user-images.githubusercontent.com/29820609/203110307-b1d1ee68-1511-4d20-9641-52f810d10401.png)

```typescript
export const configurationKeycloak = {
  client_id: 'mr-frontend',
  redirect_uri: 'http://localhost:4200/authentication/callback',
  scope: 'openid profile email',
  authority: 'http://localhost:8080/auth/realms/market-race',
  service_worker_relative_url: '/OidcServiceWorker.js',
  service_worker_only: true,
  storage: sessionStorage,
};
```

It worked with 6.0.12. 

With the new version I am not getting redirected to the login screen, I see the error instantly when i click the login Button. 
There shouldn't be any tokens to match in the first place.

**Comment by guillaume-chervet** [comment]
Thank you very much Kevin,

I have to manage version update between service worker and client side js. It is my priority.

**Comment by guillaume-chervet** [comment]
Oh i understood, you also set storage: sessionStorage,

I make a try

**Comment by kelvin-homann** [comment]
I removed sessionStorage and it works now.
Additionally i had to add the baseurl and /revoke url of our keycloak server to the trustedDomains: 
<img width="643" alt="image" src="https://user-images.githubusercontent.com/29820609/203293578-38ac3418-3d99-4fcf-8e16-36e1551dab39.png">

**Comment by guillaume-chervet** [comment]
Thank you very much Kevin for the feedback, I have some fix to do :/

**Comment by guillaume-chervet** [comment]
hi @kelvin-homann , I have done an emergency fix to update service worker : https://github.com/AxaGuilDEv/react-oidc/commit/4d561d61b7190357de1a67a18862bbaf63c1be5a
It is not clean but it will avoid big problem in production.
I will add event to be able to override the default behavior next week.

**Comment by kelvin-homann** [comment]
I hate to say it, but im still getting the error from above with v6.10.20

**Comment by guillaume-chervet** [comment]
Ans also thank you @kelvin-homann for your feedback/help :)

**Comment by kelvin-homann** [comment]
The error seems to be resolved now! Thanks 🚀
