### ISSUE TITLE
Logout with keycloak

### ISSUE THREAD

**Issue by oravagamer** [AxaGuilDEv/react-oidc#915]
How to logout a get redirected. When it logs out it redirects me to keycloak and i get a 400 error session not active.

![image](https://user-images.githubusercontent.com/74290722/205977865-d8e7d7a3-c54c-4c06-a92c-fb179f8fc997.png)
![image](https://user-images.githubusercontent.com/74290722/205978623-7c4b3799-7f02-42a5-a4a7-35fd53c80124.png)

**Comment by oravagamer** [comment]
I am using this configuration.
```
`import {OidcConfiguration} from "@axa-fr/react-oidc";

const keycloak: OidcConfiguration = {
    authority: window.location.origin + "/auth/realms/demo",
    client_id: "react-web-app",
    redirect_uri: window.location.origin + "/authentication/callback",
    monitor_session: true,
    scope: "profile"
}

export default keycloak;`
```

But i fixed that with:

```
logout("/", {
                    client_id: "react-web-app",
                    redirect_uri: window.location.origin
                })
```

**Comment by guillaume-chervet** [comment]
thank you @oravagamer for your feedback.

Does is work without "openid" scope ? 

Whithout openid, i encounter that behavior.
![image](https://user-images.githubusercontent.com/52236059/206243141-e5cf967c-e5dd-428c-bac4-d5b26906be58.png)

**Comment by noherczeg** [comment]
I encountered the same, logout breaks if the configuration does not contain the `openid` scope.

Maybe we should include this info in the docs! Unless of course if this is a bug.

**Comment by guillaume-chervet** [comment]
hi @Zamaletdinov , thank you for your issue.

I think, it will work with this correct syntaxe bellow =>

```javascript
const onSignOutClick = useCallback(() => { logout('${window.location.origin}/signed-out' }, [logout]);
```

**Comment by Zamaletdinov** [comment]
Hmm, interesting, your approach was the first one I tried, but somehow it didn't work properly - probably there were some other problems on my side, but anyway I started digging into the problem and found this issue 🤔

Anyway, now it works, thanks @guillaume-chervet!

**Comment by guillaume-chervet** [comment]
Thank you @Zamaletdinov for the feedback. I am interrested, what did you do to solve your issue?

**Comment by guillaume-chervet** [comment]
Thank you @Zamaletdinov for your feedback :)

**Comment by guillaume-chervet** [comment]
Hi @Zamaletdinov @oravagamer , thank you for your issue. I close it but feel free to reopen it if you need it.
