### ISSUE TITLE
Setting configuration storage: window.localStorage still references window.sessionStorage in code. Causes infinite loop with unauthorized component.

### ISSUE THREAD

**Issue by tielushko** [AxaGuilDEv/react-oidc#916]
### Issue and Steps to Reproduce
1. Set configuration to be window.localStorage in OidcProvider config.
2. Issue a token with the oidc provider of choice. 
3. Wait for the token to expire. Keep the page and browser tab hidden.
4. After token expiration, open the browser on the same page. 
5. Encounter infinite loop. 

I have been having issues with refreshing tokens when setting the storage configuration to be pointing at a window.localStorage. When the accessToken comes to an expiration, and I navigate the same page after expiration, I encounter infinite loop, as well as errors in the oidc.ts file. 

In particular, the file's getLoginParams function spits out error when trying to parse the data string.

I tried debugging the package code and noticed that the storage referenced there still remains to be sessionStorage when trying to get the params. 

I do not use service workers.

Here's the functions of interest.

```
const getLoginSessionKey = (configurationName:string, redirectUri:string) => {
    return `oidc_login.${configurationName}:${redirectUri}`;
};

const getLoginParams = (configurationName, redirectUri) => {
   // this line returns null
    const dataString = sessionStorage[getLoginSessionKey(configurationName, redirectUri)];
    if (!getLoginParamsCache) {

       // this gives an error 
        getLoginParamsCache = JSON.parse(dataString);
    }
    return getLoginParamsCache;
};
```

I haven't tracked where sessionStorage gets set, but when I was debugging, it seemed to reference the window.sessionStorage, while all the tokens were being set to window.localStorage correctly. 

### Versions
latest.

#### Expected
Send the refresh request.

#### Actual
get the error parsing JSON data (can't parse undefined).

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Thank you @tielushko for the issue.
We where searching for this issue a lot.

I will try to reproduce with you sept.

**Comment by guillaume-chervet** [comment]
Hi @tielushko , very sorry for the delay.
I manage to reproduce it. It happen also with the service worker mode.

**Comment by tielushko** [comment]
Hi Guillaume! Thank you for coming back to me and being able to reproduce it! I look forward to seeing the fix in the newest releases.

Best, 
Oleg

**Comment by guillaume-chervet** [comment]
Latest version already fix it for your case with localStorage. 😀

**Comment by tielushko** [comment]
Hey @guillaume-chervet I just tested the newest version from the demo app, and when I set storage to be localStorage, upon logging in, the page is stuck on redirection. I cloned the repo and ran sample app as is, with only change in identity server config to be:

`storage: localStorage`

**Comment by guillaume-chervet** [comment]
Thank you for the feedback @tielushko , I am very sorry for that big bug. I can reproduce it. I will try to fix it tomorrow.

**Comment by guillaume-chervet** [comment]
Hi @tielushko, the bug is fixed in version v6.12.1.
Very sorry for that and thank you for your help.

**Comment by tielushko** [comment]
I appreciate the quick turnaround and fix, @guillaume-chervet, I will test this in my project right away. Thank you!

**Comment by guillaume-chervet** [comment]
Hi close the issue @tielushko . Thank you for your help, feedback. I think it is resolved. Feel free to reopen it if you need.
