### ISSUE TITLE
Logto Integration - Accesstoken

### ISSUE THREAD

**Issue by mrige** [AxaGuilDEv/react-oidc#917]
### Issue and Steps to Reproduce

I am using logto as my Oidc provider and I amhaving issues with accesstoken, When i do the initial login without a resource it sends me an opaque format accesstoken, which i cannot use to protect my api resource but when i do the login with the a resource it returns a jwt accesstoken which can use to protect the api resource but this token isn't going to work to fetch the user. 
1. Is there a way around this, is there a way i can get a new accesstoken when making request to my api's 
2. Can i do this without hooks.

### Versions
latest

### Additional Info
https://docs.logto.io/docs/references/resources/
https://docs.logto.io/sdk/Kotlin/android/io.logto.sdk.android/-logto-client/get-access-token-constructor/
- Installed packages:

**Comment by guillaume-chervet** [comment]
hi @mrige, thank you for your issue.

If you want an access-token that work to fetch user you need to require "openid" scope (that may depend of your provider).
It should work with that scope.

If you do not want use hook, you can use the vanilla-oidc work whithout react. The react part is very light.

**Comment by guillaume-chervet** [comment]
Hi @mrige , does it solve your problem?

**Comment by guillaume-chervet** [comment]
I close the issue @mrige . Feel free to reopen it if you need it.
