### ISSUE TITLE
Custom login screen flow

### ISSUE THREAD

**Issue by abhilashlr7** [AxaGuilDEv/react-oidc#918]
### Issue and Steps to Reproduce

This isn't an issue, but more of a question / feature request. Is it possible to render a custom login component on say <app>/login and then make api calls for authentication? Something like how auth0 or okta sdks do. I'd like to know if there is already a way to do, it would be nice to add that as an example as well. I'm working with a NextJs app and got most of the wireups done even in version 13, but this one seemed like a missing piece in the puzzle. Would be great to address it and get it sorted.

PS: Thank you for this amazing library, was the easiest to integrate with a NextJS app having tried other libraries in the past :)  

### Versions

Latest

**Comment by guillaume-chervet** [comment]
Hi @abhilashlr7 , thank you for ypur issue.
Which oidc provider do you use?

The login page is on the oidc provider server side.
You can customize it with som provider like keycloack for example.

**Comment by abhilashlr7** [comment]
@guillaume-chervet we use Keycloak, but I wonder how should I retain the user on our domain itself without having to redirect to another page like Keycloak and perform auth. Is that on Keycloak side to be implemented then?

**Comment by guillaume-chervet** [comment]
Yes @abhilashlr7, oidc protocol use http redirection with application and OIDC server.
It is the only solution. You need to customize your login screen on the OIDC provider side.

**Comment by guillaume-chervet** [comment]
Thank you @abhilashlr7 for your help and advises :)
