### ISSUE TITLE
null is not an object error when app is served from a URL scheme other than http or https

### ISSUE THREAD

**Issue by karlvr** [AxaGuilDEv/react-oidc#919]
### Issue and Steps to Reproduce

When running the app using a URL scheme other than `https?://` the regex in `route-utils.ts`'s `getLocation` fails with a "null is not an object" error when attempting to authenticate.

This is reproduced when using [Capacitor][https://capacitorjs.com] on iOS with a production build—the app is served from `capacitor://` rather than `http://`.

### Versions

6.10.21

### Possible resolution

The regex in `route-utils.ts`'s `getLocation` function could have its match for the scheme changed like so:

```javascript
/^([a-z][\w-]+\:)\/\/(([^:\/?#]*)(?:\:([0-9]+))?)([\/]{0,1}[^?#]*)(\?[^#]*|)(#.*|)$/,
```

This correctly matches any URL scheme. It might also be worthwhile considering a more general regex e.g. from https://gist.github.com/gruber/249502

Also it would be useful to check for a `null` result from `href.match` to report a better error than "null is not an object ... t[6]" as it's quite hard to track down!

**Comment by guillaume-chervet** [comment]
Hi @karlvr , i will fix it today

**Comment by guillaume-chervet** [comment]
hi @karlvr ,

version [6.11.0] should fix you issue :)

Thank you very much for your help

**Comment by karlvr** [comment]
@guillaume-chervet thank you very much, we've tested this change and it works for our use-case. However the regex you've added won't support all valid URL schemes, particularly schemes that include a `-` or digits and others that might be commonly found. The actual list of what's supported is pretty intense. The Gist link I posted above is what I referenced as being somewhat pragmatic if the solution stays with regex.

**Comment by guillaume-chervet** [comment]
hi @karlvr , very sorry and thank you for your feedback.
I set up the regex your provided.
I hope that release [6.11.1] will work for your use case :)

**Comment by karlvr** [comment]
@guillaume-chervet not at all, I'm super impressed and thankful for your quick responses and actions. A+. This issue is resolved.

**Comment by guillaume-chervet** [comment]
Thank you @karlvr fornyour advise and help to make this library better :)
