### ISSUE TITLE
Query: Recompose dependency

### ISSUE THREAD

**Issue by LukaszGrela** [AxaGuilDEv/react-oidc#92]
Coud the react-oidc be updated to remove recompose and replace with hooks?

[A note from an author of recompose](https://github.com/acdlite/recompose#a-note-from-the-author-acdlite-oct-25-2018)
> Hi! I created Recompose about three years ago. About a year after that, I joined the React team. Today, we announced a proposal for Hooks. Hooks solves all the problems I attempted to address with Recompose three years ago, and more on top of that.

**Comment by youf-olivier** [comment]
Yes I will do that. But only after hook release =)

**Comment by youf-olivier** [comment]
PR will come very soon.

**Comment by guillaumechervetaxa** [comment]
I can wait for your PR Olivier :p

**Comment by youf-olivier** [comment]
I have to see with you some issues before !

**Comment by guillaumechervetaxa** [comment]
I am waiting to help you Olivier
