### ISSUE TITLE
When adding the 'refresh_time_before_tokens_expiration_in_second' to the OIDC config, it causes a loop in requests (token etc)

### ISSUE THREAD

**Issue by NickCain** [AxaGuilDEv/react-oidc#923]
### Issue and Steps to Reproduce

add refresh_time_before_tokens_expiration_in_second to the OIDC config, and set to any other value other than 60 (default) and then it causes the loop in the network tab, please see the screenshot.

### Versions

latest

### Screenshots

<img width="775" alt="Screenshot 2022-12-19 at 13 21 14" src="https://user-images.githubusercontent.com/13132002/208435957-eb541d0b-052c-404b-a981-930a13c85fd3.png">

#### Expected

For it not to loop.

#### Actual

Causing a request loop, and it keeps going until its manually stopped.

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Hi @NickCain , thank you for your issue. 
Which value did you set up?

What is your tokens life sans?
A collegue talk me about this last friday. He put a very big value so refresh append in loop. 
It may be a real bug :p

**Comment by NickCain** [comment]
Hi @guillaume-chervet,

Thanks so much for the quick reply. 

We passed in "900" so, refresh_time_before_tokens_expiration_in_second: 900, into the config.

Also, I believe our token lifespans are to be 2 minutes, I am just waiting on confirmation on this. 

The reason we found this issue, is due to one of our clients is taking a long time to auth due to network issues / latency on their end.

**Comment by guillaume-chervet** [comment]
2 minutes = 120 seconds it seems very short. is it for access_token?
so
120 - 900 = -780 seconds, the consequence, it refresh in loop.

A better value for refresh_time_before_tokens_expiration_in_second would be like 90 seconds, so it will start refreshing every 30 seconds (which seem short).

May you update your tokens lifetime (in your OIDC server configuration) to 5 minutes for example?

**Comment by NickCain** [comment]
Hi @guillaume-chervet,

yes you are right, that was for the access_token.

Ah I see from your example why the loop is now occurring, let me get back to my team and ask them to update the token lifetime to be longer than 2 minutes and see what happens. 

Thank you for your quick response with this matter.

**Comment by guillaume-chervet** [comment]
Hi @NickCain , thank you for your issue. I close it. Feel free tonreopen it if you need it.
