### ISSUE TITLE
Whenever the app is disconnected from the network, the entire app is going into a broken experience due to network disconnect.

### ISSUE THREAD

**Issue by abhilashlr7** [AxaGuilDEv/react-oidc#924]
### Issue and Steps to Reproduce

Whenever the app is disconnected from the network, the entire app is going into a broken experience due to network disconnect.

Login to the app, and close the lid or disconnect from the internet, then the token refetch mechanism fails. Therefore, the app goes to blank screen. This happens quite often in dev env. Is there a way to refetch the failed XHR call for token refetch when network connectivity is back online? 

### Versions
Latest version

**Comment by guillaume-chervet** [comment]
Hi @abhilashlr7,  thank you for your issue.
I think you can manage your use case by overiding yhe default behavior.
You can use onSessionLost attribut for that.
When internet connexion is back you can try a silent signin . If it fail connexion is really lost.

**Comment by abhilashlr7** [comment]
Ah nice! Thanks @guillaume-chervet :) How do I do a silent login mechanism? sorry for asking a noob question!

**Comment by guillaume-chervet** [comment]
Hi @abhilashlr7, sorry for the delay.
Silent login is done automaticaly in background if you set up the silent redirect uri.

**Comment by abhilashlr7** [comment]
> Hi @abhilashlr7, sorry for the delay. Silent login is done automaticaly in background if you set up the silent redirect uri.

I had this configured wrongly. basically to a page which never existed. Thanks for pointing my mistake @guillaume-chervet :) Will close this ticket.
