### ISSUE TITLE
mocking useOidcUser, OidcUserStatus for react testing library get type error and cant fix it

### ISSUE THREAD

**Issue by arezookheirabedi** [AxaGuilDEv/react-oidc#926]
### Issue and Steps to Reproduce

@axa-fr/react-oidc": "^6.10.21"

import {  useOidcUser, useOidc, OidcUserStatus } from "@axa-fr/react-oidc";

jest.mock("@axa-fr/react-oidc");

const useOidcMock = useOidc as jest.MockedFunction<typeof useOidc>;

const useOidcUserMock = useOidcUser as jest.MockedFunction<typeof useOidcUser>;

it("renders correctly", () => {
  useOidcUserMock.mockImplementation(({ oidcUser:{sub:"fgfhfghghj"}, oidcUserLoadingState: OidcUserStatus.Loaded }));
  useOidcMock.mockImplementation(({
    login: async () => { },
    logout: async () => { },
    renewTokens: async () => { },
    isAuthenticated: true,
  }));
  const tree = renderer
    .create(
      < BrowserRouter >
        <AccountPopover />
      </BrowserRouter>
    )
    .toJSON();
  expect(tree).toMatchSnapshot();
});

### Additional Details

- Installed packages:

**Comment by arezookheirabedi** [comment]
TypeError: Cannot destructure property 'logout' of '(0 , _reactOidc.useOidc)(...)' as it is undefined.

**Comment by guillaume-chervet** [comment]
Hi @arezookheirabedi, thank you for your issue. It is a very good one.

I do not use of mock any library because  https://link.medium.com/jJJbz3QRWvb

The problem is i do not know how to mock it with the use of hook (i understand why hook exist, but i am not a fan).

Many People use https://kentcdodds.com/blog/stop-mocking-fetch but it require many many intricate data to make it work.

I do not have the answer for the moment. What i do is to externalise untestable component and inject data in testable one.

**Comment by arezookheirabedi** [comment]
i moked it on this way and its worked for me
it("renders correctly", () => {
  useOidcUserMock.mockImplementation(
    () => {
      return {
        oidcUser: { sub: "fgfhfghghj" },
        oidcUserLoadingState: OidcUserStatus.Loaded,
      };
    }
  );

  useOidcMock.mockImplementation(() => {
    return {
      login: () => {
        return new Promise<void>((resolve) => {
          resolve();
        });
      },
      logout: () => {
        return new Promise<void>((resolve) => {
          resolve();
        });
      },
      renewTokens: () => {
        return new Promise<void>((resolve) => {
          resolve();
        });
      },
      isAuthenticated: true,
    };
  });
  const tree = renderer
    .create(
      <BrowserRouter>
        <AccountPopover />
      </BrowserRouter>
    )
    .toJSON();
  expect(tree).toMatchSnapshot();
});





describe("AccountPopover", () => {
  test("when click on element to navigate to another route", () => {
    useOidcUserMock.mockImplementation(
      () => {
        return {
          oidcUser: { sub: "fgfhfghghj" },
          oidcUserLoadingState: OidcUserStatus.Loaded,
        };
      }
    );

    useOidcMock.mockImplementation(() => {
      return {

        login: () => {
          return new Promise<void>((resolve) => {
            resolve();
          });
        },
        logout: () => {
          return new Promise<void>((resolve) => {
            resolve();
          });
        },
        renewTokens: () => {
          return new Promise<void>((resolve) => {
            resolve();
          });
        },
        isAuthenticated: true,
      };
    });
    render(
      < BrowserRouter >
        <AccountPopover />
      </BrowserRouter>
    );
    const AltText = screen.getByAltText("photoURL");
    fireEvent.click(AltText);
    const role = screen.getByRole("presentation");
    expect(role).toBeInTheDocument();
    userEvent.click(screen.getByText(/HOME/i));
    expect(screen.getByText(/HOME/i)).toBeInTheDocument();
    userEvent.click(screen.getByText(/Logout/i));
    expect(useOidcUserMock).toBeCalled();
  });
});

**Comment by guillaume-chervet** [comment]
Thank you @arezookheirabedi for the examplr, does it solve your initial issue?

**Comment by arezookheirabedi** [comment]
yes i  want to test some secure components and need to mock oidc hook it works
