### ISSUE TITLE
OidcProvider tag prevent rendering AppRoutes

### ISSUE THREAD

**Issue by reggspr** [AxaGuilDEv/react-oidc#927]
### Issue and Steps to Reproduce
Hello, i might be finding some clues if i open a new issue here. When i run the code, it's got stuck on "loading" page
![1](https://user-images.githubusercontent.com/34613790/209061654-3c7502de-a4b8-456d-8bd1-713cee3fe2a1.PNG)
i had to manually add the "auth" in the address bar for it to redirect to auth page. When i tried to debug and place some breakpoint on it one by one, it seems when the app load the index.tsx, it won't load the AppRoutes when OidcProvider tags are in, am i doing the right things when declaring those? or is there something missing (Already tried to change it from redirect uri from env, it really is redirect the app to the auth page, but it returns invalid request from the backend)

### Versions
react-oidc 6.5.10
### Screenshots
Configuration code
![2](https://user-images.githubusercontent.com/34613790/209062750-5ea58b05-bb0a-414f-b99f-624ab9b35879.PNG)
Error if i change the redirect uri
![error invalid](https://user-images.githubusercontent.com/34613790/209062993-2059ae42-234a-4ae8-80c0-58958cee79dd.PNG)
AppRoutes code
![appRoutes](https://user-images.githubusercontent.com/34613790/209063109-fb99b8ae-cbca-4923-b516-24b344d05900.PNG)

#### Expected
App start and then redirect to auth page
#### Actual
Stuck on loading page
![loading](https://user-images.githubusercontent.com/34613790/209063609-b535b20a-53c9-4c51-ac41-f6d8780050b3.PNG)

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Hi @reggspr , thank you for your issue.
Does your oidc provider provide a .weelknowurl.
You should see an HTTP 404 in the http network and that may be why it stay stuck on the loading page.

If it does not provide that weel know url, you can bypass it by configuration all technical oidc urls. Like 👎

**Comment by reggspr** [comment]
Hello @guillaume-chervet thanks for the response
what should i do to check if the oidc provider provide a wellknowurl? and for additional note, it's stuck not because of 404 error, i thought that as well in the first place, but ruling that out once i know when debugging oidcprovider tag is preventing the AppRoutes to load. Here's the before and after i remove the tag
before:
![network](https://user-images.githubusercontent.com/34613790/209101523-267cbb50-37e0-4839-ac1d-2874ce57a2a9.PNG)
after:
![after](https://user-images.githubusercontent.com/34613790/209101586-cbda9ece-95a9-4eaf-b0e9-47767843205d.PNG)

**Comment by guillaume-chervet** [comment]
Thank you @reggspr you right. What is strange is I do not seen any request about well know url.
What happen is you move OidcProvider at the top level of your application? Before QueryClientProvider.

**Comment by reggspr** [comment]
i tried move it on the top level, it doesn't do anything

**Comment by guillaume-chervet** [comment]
Did you tried your oidc configuration on the reactoidc demo?

**Comment by reggspr** [comment]
yes, i've tried it but still the same error @guillaume-chervet

**Comment by guillaume-chervet** [comment]
@reggspr that very strange.
So with your oidc configuration on the demo you never get any http call to your oidc server from react-oidc library?

I have no idea of what can happen to you.

May you print your configuration (please hide the domain for security reason)?

**Comment by reggspr** [comment]
this is the raw configuration, and don't worry the domain is still in localhost because it's still on debug environment @guillaume-chervet 
![raw config](https://user-images.githubusercontent.com/34613790/209263343-d74e1bc2-01a0-46b7-941d-b8d0f1b9b0e9.PNG)

**Comment by guillaume-chervet** [comment]
Thank you @reggspr , which oidc provider do you use?
Thank strange your configuration seem OK.

**Comment by guillaume-chervet** [comment]
Which browser do you use?

**Comment by reggspr** [comment]
i use chrome

**Comment by reggspr** [comment]
Thanks for trying to help @guillaume-chervet , i found the core of the problem
i need to add the /auth redirecturi's from duende's identity server so i can set the redirecturi from the configuration to domain/auth

**Comment by guillaume-chervet** [comment]
Thank you @reggspr for the feedback :)
Have fun
