### ISSUE TITLE
Silent re-login for tenant change 

### ISSUE THREAD

**Issue by IonescuDan00** [AxaGuilDEv/react-oidc#928]
### Issue and Steps to Reproduce
This is more of a question than an issue. 
I am building a portal in react which should work multi-tenant. Server-wise i am using the Identity Server 4.
During the login the users selects a tenant. which is then included as a claim in the access token. 
I would like to allow the user to change the tenant without re-login  which would mean a silent re-login with a custom grant type 
(the new tenant id will be sent to be replaced in the claim).
Is there any support for this type of functionality ?
Thank you in advance 

### Versions
 6.11.1
### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Hi @IonescuDan00 , the library is designed for that kind of use case.

**Comment by guillaume-chervet** [comment]
It require good configuration at oidc server side. If it does not work let me know. I have never test it.

**Comment by IonescuDan00** [comment]
Hi @guillaume-chervet ,

Really appreciate the quick answer. 
Regarding frontend configuration, we should exchange the token with a new one using a custom grant type "tenant".
Normally, this should call an endpoint on identity server : "connect/token" with grant_type: "tenant".
However, is not very clear how we can achieve this. 
Should I call login with extra params? 
How the response_type can be changed from authorization code to tenant? 
Thank you.

**Comment by guillaume-chervet** [comment]
I'am not sure but I think you may call

```
    renewTokensAsync(extras:StringMap = null):Promise<void> {
        return this._oidc.renewTokensAsync(extras);
    }

renewTokensAsync({"grant_type": "tenant"});

it will renew token adding grant_type attributes using token request.

```

**Comment by guillaume-chervet** [comment]
Hi @IonescuDan00 let me know if the use of extra work for your use case. If not i can update the library for it.

**Comment by IonescuDan00** [comment]
Hi @guillaume-chervet,

We did several tests yesterday and unfortunately it did not work. 
The steps called were: 
1)  **http://localhost:4200/authentication/silent-login?grant_type=tenant&tenantId=1234&prompt=none**
Here you can see that grant_type and tenantId were sent from  extras 

2) **http://localhost:4200/authentication/silent-callback**  with request URL : 
 https://localhost:7281/connect/authorize?redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fauthentication%2Fsilent-callback&client_id=tenantapp&response_type=code&state=zWKDxwqZa6&scope=openid%20profile%20tenantapp&grant_type=tenant&tenantId=1234&prompt=none&nonce=VwBMggAFWmEK&code_challenge=MM3BwSvApyPAM1e_s4_m1MTuXaI6bn4gKcETmW2hK0U&code_challenge_method=S256
Also here were sent. However the response_type is still "code". 

3) https://localhost:7281/connect/token
with Payload:
grant_type: authorization_code
client_id: tenantapp
redirect_uri: http://localhost:4200/authentication/silent-callback
code: 2E9AA7262EF620D839529F93FEA90E7BC3870B482D4E3BCD2DE08B038D8DDBC7
code_verifier: 4DimHNHYeAVPC4eFFeA6QxZ63DonkfjLPFbRGGN3kOnmEXabsRBNWEUck2jKkDLO1lHBolp5yURMvUWxqHScuMgmeT05gzjIPQbCxHQFwUXi3IZkZKBoUhSAvUsltnlo

In the payload it does not sent the extras params and also grant_type is still "authorization_code".

I believe only the last call should have been executed (because i just need to refresh the token), with the grant_type = "tenant"
and tenantId = "1234".

Of course in the identity server, because a new grant type was defined we will not validate ( IExtensionGrantValidator.ValidateAsync ) the authorization_code. 

Let me know if you have any suggestion about how we should proceed. 

Thank you,
Dan

**Comment by guillaume-chervet** [comment]
Hi @IonescuDan00 , thank you very much for your inputs. I think i have to make a change in the code. Iam in holiday until next year. Can you wait a litle bit? It is my priority to add that.

**Comment by IonescuDan00** [comment]
Hi @guillaume-chervet,
Thank you very much. 
It would be great if you can do a change once you are back.
Happy holidays !

**Comment by guillaume-chervet** [comment]
Hi @IonescuDan00 ,

I think I have to add an token_request_extras parameter.

Do you need to execute that request with that parmaeters once?

**Comment by guillaume-chervet** [comment]
hi @IonescuDan00 ,

I my need to add a breaking change.

I need to design a cleaner way to set up extra to to good actions. the difficulties is that the library auto_renew tokens once authentication is done.
`
const extras = {
    "tenantId:token_request:once": "123",
    "grant_type:token_request:once": "tenant",
    "prompt:authorize_request:once": "none",
    "client_secret:token_request:always": "secret",
    "client_secret:refresh_token_request:always": "secret",
}

const extras = {
    "tenantId": { value: "123", "destination": "token_request", "mode": "once" },
    "grant_type": { value: "tenant", "destination": "token_request", "mode": "once" },
    "prompt": { value: "none", "destination": "authorize_request", "mode": "once" },
    "client_secret": { value: "secret", destination: "refresh_token_request_and_token_request", "mode": "always" },
}
`

**Comment by IonescuDan00** [comment]
Hi @guillaume-chervet,
Sorry for late answer.
1) Regarding first question:
**Do you need to execute that request with that parmaeters once?**
We will execute each time the user will change the tenant is working on or other variable
that comes with the user Info ( for example we also sent and environment id that may change during user session).

2) **Regarding the breaking change.**
I think I would go with the second idea. But we can work with both outcomes.  

Thank you very much for your support.

**Comment by guillaume-chervet** [comment]
hi @IonescuDan00,

package 6.11.4-alpha1 may work for your use case. It is a first draft version.

You can silent login like bellow:
`
login(undefined, { 'grant_type:token_request': 'tenant', 'tenantId:token_request': '1234' }, true)

`

**Comment by IonescuDan00** [comment]
HI @guillaume-chervet ,

I have tested with the latest version (6.11.4-alpha1), but when i make 
the request the extras params are not sent to the authorize endpoint 
of the Identity server although they are created before in the silent login component. Request look as follow: 

![q8DHC0G9Wg](https://user-images.githubusercontent.com/121229381/210783766-425d933a-4fc8-4ecd-8e44-df5a7b0c6217.jpg)
![Screenshot 2023-01-05 144741](https://user-images.githubusercontent.com/121229381/210783787-84e7f2db-a34e-447c-be23-4693f068e6ff.png)


Thank you for your support.

**Comment by guillaume-chervet** [comment]
hi @IonescuDan00 , thank you very much for your feedback.
I'am on it, very sorry for the delay.

**Comment by guillaume-chervet** [comment]
![image](https://user-images.githubusercontent.com/52236059/211096347-6f0a6049-4199-49c2-b9d9-d665754d8297.png)

![image](https://user-images.githubusercontent.com/52236059/211096399-18aff2b1-395d-4f27-a557-e5087702eb63.png)

![image](https://user-images.githubusercontent.com/52236059/211096498-b584ad89-4472-49fe-bdaf-7093d70fb5e7.png)


I obtain that with 6.11.4-alpha2 @IonescuDan00

**Comment by guillaume-chervet** [comment]
hi @IonescuDan00 , version v6.12.1 should work.
To make param pass through authorization_request you may use 👍 

```javascript
login(undefined, { 'grant_type': 'tenant', 'tenantId': '1234' }, true)

```

**Comment by IonescuDan00** [comment]
Hi @guillaume-chervet,

I have tested also with the alpha version. And it works !
Thank you very much for your support.
