### ISSUE TITLE
Multiple `/token` calls are made in 1s intervals

### ISSUE THREAD

**Issue by abhilashlr7** [AxaGuilDEv/react-oidc#932]
![image](https://user-images.githubusercontent.com/118144617/210341072-6873da4a-60d4-4c63-9cf0-c18e22ba62b0.png)

If you look at the above image, there are multiple token api calls made in a short span of time and this keeps repeating every 1s.

I tried setting the following too, just in case to see if it will work as expected:

```ts
  token_request_timeout: 10000,
  silent_login_timeout: 10000,
```

Yet, it doesn't work and still makes those silent calls. Is this the expected behaviour? Asking because there are so many requests happening and it doesn't look great for debugging either.

Or is it something that I have messed up in my setup that I need to make sure to see this work properly.?

**Comment by guillaume-chervet** [comment]
hi @abhilashlr7,

Thank you very much for your PullRequest.
you will find more information here #923 
What is your access_token and id_token tokens lifespan?

**Comment by abhilashlr7** [comment]
> hi @abhilashlr7,
> 
> Thank you very much for your PullRequest. you will find more information here #923 What is your access_token and id_token tokens lifespan?

Interesting comment @guillaume-chervet , thanks for pointing me to it. I've setup the same and it works. Closing this ticket now.
