### ISSUE TITLE
It is directly redirecting me to google contact page

### ISSUE THREAD

**Issue by KumaravelPonnusamy** [AxaGuilDEv/react-oidc#933]
### Versions 
6.11.3

### Screenshots

Code
<img width="416" alt="image" src="https://user-images.githubusercontent.com/29377849/210440811-43ad9808-2f4b-4504-93ad-853fb534f5b8.png">

![image](https://user-images.githubusercontent.com/29377849/210440877-07d86ac0-195a-445e-a897-29e8181c79da.png)

Trusted domain
<img width="580" alt="image" src="https://user-images.githubusercontent.com/29377849/210441171-ac08b2a2-c1d3-41b1-9ce3-c0f13a26fb20.png">

#### Expected
On successful login it should redirect me to the redirect URI 
on Failure It should redirect me to the SSO page 

#### Actual
It is redirecting me to [google contact](https://about.google/contact-google/)

- Installed packages:
- "@axa-fr/react-oidc": "6.11.3"
- **Other Packages **

    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.3",
    "@types/react": "^18.0.25",
    "@types/react-dom": "^18.0.9",
    "axios": "^1.2.0",
    "bootstrap": "^5.2.2",
    "oidc-react": "^2.1.0",
    "react": "^18.2.0",
    "react-beforeunload": "^2.5.3",
    "react-bootstrap": "^2.6.0",
    "react-dom": "^18.2.0",
    "react-frame-component": "^5.2.3",
    "react-router-dom": "^6.4.3",
    "react-scripts": "5.0.1",
    "sass": "^1.56.1",
    "typescript": "^4.9.3",
    "web-vitals": "^2.1.4"

**Comment by guillaume-chervet** [comment]
hi @KumaravelPonnusamy ,

thank you for your issue.

What is your network history?

I think the problem may come from your OIDC server configuration.

**Comment by KumaravelPonnusamy** [comment]
Hi @guillaume-chervet 

Thanks for your kind support.

The network is related Azure ad.

I will check the OIDC configurations.

**Comment by guillaume-chervet** [comment]
Hi @KumaravelPonnusamy , did you resolve your problem?

**Comment by guillaume-chervet** [comment]
Hi @KumaravelPonnusamy , i close the issue. Feel free to reopen it if you need it. I hope you have found a solution.
