### ISSUE TITLE
Problem under Cloudflare

### ISSUE THREAD

**Issue by Alanm63** [AxaGuilDEv/react-oidc#943]
### Not sure if this is an issue, but have nowhere to turn

- Installed packages: @axa-fr/react-oidc": "^6.11.3 :"react": "^18.2.0"
I have built an app using the axa-fr package in a front end built with react.
The application sucessfully logs in to IdentityServer4, gets a token and then calls a data API (using the token) which returns data from a SQL database: Everything is hosted in IIS. I use a Certificate to sign the JWT.
It all works as expected in my local dev set up. It all works when it gets moved to UAT webfarm. However when Cloudflare is switched on it works for a while and then doesn't. In my logs it indicates the authorization has failed but not why. It seems like the api endpoint is trying to get authorized but times out and then a fail happens with 500 code. Maybe I configured something wrong, but again, it works as expected with no Cloudflare.

I don't know if this is the right place to post this but I just wanted to ask if anyone else has experienced this behaviour with Cloudflare. as I cannot see what the issue might be considering it all works fine when not going through Cloudflare. 

Thanks for any thoughts on the matter. I am including my configuration here 

  client_id: 'myreactapp',
    authority:"https://myIdentityServer",
    redirect_uri: window.location.origin + '/authentication/callback',
    silent_redirect_uri: window.location.origin + '/authentication/silent-callback',
    scope: 'openid profile mydataapi role',
    response_type: 'code',
    token_renew_mode: "access_token_invalid",
    refresh_time_before_tokens_expiration_in_second: 90,
    service_worker_relative_url:'/OidcServiceWorker.js',
    service_worker_only: true,
    storage: sessionStorage,
    monitor_session:false

**Comment by guillaume-chervet** [comment]
Hi @Alanm63 , thank you very much for using react-oidc :)
HTTP 500 come from server side.
Do you have a log or an information of the error which happen at the server side? Inside cloudflare or identity server side.

Identityserver is now renamed as dudende. You can also use that awesome framework that I am fan of:
https://github.com/openiddict/openiddict-core

**Comment by Alanm63** [comment]
The 500 error comes about because myDataAPI does not seem to communicate with myIdentityAPI at the point of Authorization. I have enclosed 2 files with the section from the logs. One is from my DeV machine where it is all good and the other is from teh UAT machine with cloudflare. It may be worth mentioning that it is all hosted under the same domain. ie
mywebsite.com/myIdentityAPI 
mywebsite.com/myDataAPI 

The frustrating thing is that everything works until Cloudflare is used. When CloudFlare is switched on I can still log in and authenticate, I can see that tokens are returned and refreshed but some thing gets into the mix that stops the dataApi from authorizing.
This may have nothing to do with your software here and I apologise if its not but I am stumped by this. I will be meeting with the Cloudflare person later.

[Dev_SuccessDataApiLog.txt](https://github.com/AxaGuilDEv/react-oidc/files/10510049/D
[DataApiLog.txt](https://github.com/AxaGuilDEv/react-oidc/files/10510050/DataApiLog.txt)
ev_SuccessDataApiLog.txt)

Thank you

**Comment by Alanm63** [comment]
I got the issue resolved. As it turned out the issue had nothing to do with code but rather Cloudflare and settings in Firewalls.

Thanks

**Comment by guillaume-chervet** [comment]
I  am glad you found your issue :)

**Comment by guillaume-chervet** [comment]
hi @Alanm63 , may we close the issue?

**Comment by Alanm63** [comment]
Yes, thank you 😊

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
