### ISSUE TITLE
Logout does not log the user out (AWS Cognito)

### ISSUE THREAD

**Issue by thekarel** [AxaGuilDEv/react-oidc#955]
### Issue and Steps to Reproduce

I've set up my web app to use AWS Cognito. I can sign in just fine and get a token in the app:

```ts
client_id: config.oidcClientId,
redirect_uri: `${location.origin}/authentication/callback`,
scope: '',
authority: config.oidcEndpoint, 
service_worker_only: false,
```

To log out I call

```ts
const {logout} = useOidc()

logout()
```

This logs the user out locally (all I can see is the login screen), but if I call `login` again, the user is logged back in instantly, **without the need to enter a password**.

### Versions

```
"@axa-fr/react-oidc": "^6.14.2",
```

#### Expected

The user is logged out and forced to enter a password / MFA again.

#### Actual

The user is logged back in without the need to enter a password / MFA.

### Additional Details

According to the Cognito documentation the logout URL is something like this:

https://CUSTOM_DOMAIN/logout?client_id=xxx&logout_url=xxx

This works fine if I navigate there manually and the user is forced to re-authenticate.

I've tried to add this to a custom logout call:

```ts
const logout = React.useCallback(async () => {
  const url = `${config.oidcEndpoint}/logout?client_id=${config.oidcClientId}&logout_uri=${location.origin}/`
  await oidcLogout(url, {
    post_logout_redirect_uri: url,
  })
}, [config.oidcClientId, config.oidcEndpoint, oidcLogout])
```

... but that didn't made a difference.

---

Maybe I'm doing something wrong, but what is the correct way to set up Cognito & logout?

**Comment by thekarel** [comment]
This trick seems to work for now:

```ts
// config.oidcEndpoint is the custom domain
const logout = React.useCallback(async () => {
  const logoutUrl = `${config.oidcEndpoint}/logout?client_id=${config.oidcClientId}&logout_uri=${location.origin}/`
  await oidcLogout()
  document.location.href = logoutUrl
}, [config.oidcClientId, config.oidcEndpoint, oidcLogout])
```

**Comment by guillaume-chervet** [comment]
Hi @thekarel ,

Logout require the scope openid.
I have to add this in warning in the console, if it is not set.

**Comment by guillaume-chervet** [comment]
Hi @thekarel , do you have the content return from the wellknowurl from cognito? I do not have any access to aws cognito rigth now. This url give the full configuration of the oidc server.

**Comment by guillaume-chervet** [comment]
@thekarel did you configure logout url on cognito side? https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html

It is mandatory, so you must set your logout url when calling it. Like

logout("/callback_afterlogount")

**Comment by guillaume-chervet** [comment]
Hi @thekarel , sorry i did not read well your message.
When you enter it manually it works, but not when coming feom ypur application. This look very strange. Do you have a video or something that may help to understand ?

**Comment by thekarel** [comment]
The response from `.well-known/openid-configuration` is the following:

```json
{
	"authorization_endpoint": "https://$CUSTOM_DOMAIN/oauth2/authorize",
	"id_token_signing_alg_values_supported": [
		"RS256"
	],
	"issuer": "https://cognito-idp.eu-west-2.amazonaws.com/$USER_POOL_ID",
	"jwks_uri": "https://cognito-idp.eu-west-2.amazonaws.com/$USER_POOL_ID/.well-known/jwks.json",
	"response_types_supported": [
		"code",
		"token"
	],
	"scopes_supported": [
		"openid",
		"email",
		"phone",
		"profile"
	],
	"subject_types_supported": [
		"public"
	],
	"token_endpoint": "https://$CUSTOM_DOMAIN/oauth2/token",
	"token_endpoint_auth_methods_supported": [
		"client_secret_basic",
		"client_secret_post"
	],
	"userinfo_endpoint": "https://$CUSTOM_DOMAIN/oauth2/userInfo"
}
```

There's no mention of logout here. Going into Cognito > User Pool > User Pool App Client > Edit Hosted UI I can specify the signout URLs. But, according to the documentation, these URLs are only used when hitting the logout endpoint (quote from the edit page):

> You can configure a sign-out URL for your app client. When your app calls the Amazon Cognito LOGOUT endpoint or the GlobalSignOut API, your user will be redirected to the URL you specify after their tokens are invalidated. You can configure more than one allowed sign-out URL for your app client.

This seems to say the same thing as the page you've linked above. More like a convenience and is only used after the provider logged the user out.

What I'm not sure about is what your example above `logout("/callback_afterlogount")` supposed to do? Is it supposed to redirect the user locally to this address or... something to do with the OIDC endpoint?

Anyway, it seems to me the logout, at least in Cognito, only happens if you hit the `/logout` endpoint. But it seems to be `react-oidc` is not trying to hit that ever.

One thing to note is that for Cognito there are actually 2 separate endpoints: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-userpools-server-contract-reference.html

One is `https://cognito-idp.Region.amazonaws.com/your user pool ID/` and the other is `https://Your Custom Domain`

When configuring `react-oidc`, one has to use the 1st one (`https://cognito-idp....`) as authority. But the logout endpoint is available at the second one only! So it's `https://CustomDomain/logout?client_id=xxx&logout_uri=xxx`

So at the moment I'm calling calling the logout method and then sending the browser to the logout endpoint:

```
await oidcLogout()
document.location.href = logoutUrl
```

Hope this helps! Let me know you need more from the to get to the bottom of this.

**Comment by guillaume-chervet** [comment]
Hi @thekarel thank you for your responses. To make it work, you may  add to configuration oidc config:

`
authority_configuration: PropTypes.shape({
      // Optional for providers that does not implement OIDC server auto discovery via a .wellknowurl
      authorization_endpoint: PropTypes.string,
      token_endpoint: PropTypes.string,
      userinfo_endpoint: PropTypes.string,
      end_session_endpoint: PropTypes.string,
      revocation_endpoint: PropTypes.string,
      check_session_iframe: PropTypes.string,
    }),
`

**Comment by guillaume-chervet** [comment]
I am pretty sure that it will work

**Comment by thekarel** [comment]
Merci for your response @guillaume-chervet !

I've added this to my config:

```ts
      authority_configuration: {
        authorization_endpoint: 'https://$CUSTOM_DOMAIN/oauth2/authorize',
        end_session_endpoint: 'https://$CUSTOM_DOMAIN/logout',
        issuer: 'https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_ABCabc123',
        revocation_endpoint: 'https://$CUSTOM_DOMAIN/logout',
        token_endpoint: 'https://$CUSTOM_DOMAIN/oauth2/token',
        userinfo_endpoint: 'https://$CUSTOM_DOMAIN/oauth2/userInfo',
      },
```

Now on `logout()` the library sends a POST request to the end_session_endpoint with token, token_type_hint and client_id as payload. But [the endpoint expects a GET request](https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html) with different payload.

So for now I think, at least for Cognito, one has do a quick redirect to the logout endpoint.

**Comment by guillaume-chervet** [comment]
Hi @thekarel , this is strange, the code should do the correct Get request to cognito look at the code https://github.com/AxaGuilDEv/react-oidc/blob/e486ae4bed064523e2cc98f953a3c0a936d261fb/packages/react/src/oidc/vanilla/logout.ts#L71
To end_session_endpoint. Do you have screen of network request or something that may help to understand your behavior?

**Comment by thekarel** [comment]
Ok, your're right! This is what I had to add to logout to work with Cognito/AWS:

Config:

```ts
  authority_configuration: {
    authorization_endpoint: 'https://$CUSTOM_DOMAIN/oauth2/authorize',
    end_session_endpoint: 'https://$CUSTOM_DOMAIN/logout',
    issuer: 'https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_ABCabc123',
    revocation_endpoint: 'https://$CUSTOM_DOMAIN/oauth2/revoke',
    token_endpoint: 'https://$CUSTOM_DOMAIN/oauth2/token',
    userinfo_endpoint: 'https://$CUSTOM_DOMAIN/oauth2/userInfo',
  },
```

Logout:

```ts
logout('/', {client_id: 'xxx', logout_uri: location.origin + '/'})
```

This way the token is revoked and the user is logged out for good!

One thing I'd note, is that the library makes 2 calls to the revoke endpoint: 1st with the access_token and then with the refresh_token. In case of Cognito, only the refresh token should be sent - so the 1st request results in a 400 error. This is not breaking anything but maybe worth adding it to the configuration?

Thanks for your help @guillaume-chervet 👍
