### ISSUE TITLE
Can renewTokens(); method return the actual renewed token itself instead of undefined?

### ISSUE THREAD

**Issue by abhilashlr7** [AxaGuilDEv/react-oidc#963]
As the title says, we make a `const token = await renewTokens();` whenever our API returns a 401 to make sure the user session is not lost, in case the user logs back in after a while. To keep the user logged in unless they explicity makes a `logout` call, we do this in our axios response interceptor. But once we get a new token, we are unable to make a `useOidcAccessToken()` since this invocation would be inside the response interceptor based on an if condition (if 401 then renew token, and use that renewed token to retry the failed request that had recvd a 401).

**Comment by guillaume-chervet** [comment]
hi @abhilashlr7 , sure it is possible to do.
Thank you for your issue.
I'am in holiday, I may do it next week.

**Comment by guillaume-chervet** [comment]
hi @abhilashlr7,

version 6.14.9 implement it !
