### ISSUE TITLE
[BUG] After deploying in Cloudfront + S3, accessing to my website, it fails on the /

### ISSUE THREAD

**Issue by rsareth** [AxaGuilDEv/react-oidc#964]
### Issue and Steps to Reproduce

I deploy my website on cloudfront + s3. When accessing it on the /, it fails because in the localStorage, the entry **oidc.login.default**  is not there. But if I go to /#/somewhere, it works.

So, even before running OidcServiceWorker.js, it fails. I added some console.log in it. It makes hard to debug. But according to the stacktrace, it is in the [**initWorker.ts:256**](https://github.com/AxaGuilDEv/react-oidc/blob/master/packages/react/src/oidc/vanilla/initWorker.ts#L256).

I tried with your demo react, it fails too. I see the same stack trace error.

Then, I logged out. So the entry on **oidc.login.default** is set. I go back on / and it fails too. I don't understand why it tries to get the token on /oauth2/token? I'm already logged out and it should check more things before. Just look at the second screenshot.

### Versions
@axa-fr/react-oidc@6.14.7

#### 1st login
![Screenshot 2023-02-20 at 11 53 45](https://user-images.githubusercontent.com/4334697/220085783-f58ec38f-83cc-4303-b4f3-4dbd4d7a0d82.png)

#### 2nd login
![Screenshot 2023-02-20 at 12 32 24](https://user-images.githubusercontent.com/4334697/220095128-cdea4a4b-dd04-4097-89f5-a87e952625c0.png)

### Additional Details
- The OicdServiceWorker.js and OidcTrustedDomains.js are in the public directory like the demo.
- The OidcConfiguration is provided programmatically.
- I'm using Cognito for the authentification mechanism.
- Installed packages:
    "@axa-fr/react-oidc": "^6.14.7",
    "@emotion/react": "^11.9.3",
    "@emotion/styled": "^11.9.3",
    "@mui/icons-material": "^5.1.1",
    "@mui/material": "^5.8.7",
    "@openid/appauth": "^1.3.1",
    "@react-google-maps/api": "^2.7.0",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/user-event": "^12.8.3",
    "@types/jest": "^26.0.24",
    "@types/jwt-decode": "^3.1.0",
    "@types/node": "^12.20.55",
    "@types/react": "^18.0.0",
    "axios": "^0.23.0",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.2",
    "npm-force-resolutions": "^0.0.10",
    "openapi-backend": "^5.0.0",
    "qs": "^6.11.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-notifications-component": "^4.0.1",
    "react-router-dom": "^5.3.3",
    "react-scripts": "^5.0.0",
    "tslib": "^2.3.1",
    "typescript": "^4.4.3"

**Comment by guillaume-chervet** [comment]
hi  @rsareth ,

thank you for your issue.

I may need more information to help you.

What does look like your redirectUrl in your configuration?
Did you configurer trustedDomains.js?

**Comment by rsareth** [comment]
Hi @guillaume-chervet ,

This is the configuration I set:
```ts
const getRedirectUri = (config: Map<string, any>): string => {
  return config.get('env') === "local" ? 'http://localhost:3000/login' : window.location.origin;
}

const oidcConfiguration: OidcConfiguration = {
    authority: `https://cognito-idp.${configJson.get("region")}.amazonaws.com/${configJson.get("userPoolId")}`,
    client_id: configJson.get("userPoolWebClientId"),
    redirect_uri: getRedirectUri(configJson),
    scope: "openid email",
    service_worker_only: true,
    service_worker_relative_url: '/OidcServiceWorker.js'
};
```

**Comment by rsareth** [comment]
I forgot the OidcTrustedDomains.js:

```js
const trustedDomains = {
    default: [
        'https://<custom>.auth.eu-west-1.amazoncognito.com',
        'https://cognito-idp.eu-west-1.amazonaws.com/<cognito_id>'
    ]
};
```

**Comment by guillaume-chervet** [comment]
thank you @rsareth ,

just an idea,
does it work with:

```js
const getRedirectUri = (config: Map<string, any>): string => {
  return config.get('env') === "local" ? 'http://localhost:3000/login' : window.location.origin#/login;
}
```

**Comment by rsareth** [comment]
I can't change the redirect uri. Cognito refuses the url with the `#`: ``https://domain/#/login``

And the path `/login` is not handled in the current application. On the local machine, it is trick set by someone else. So, does it mean that I have to implement the code handling the path?

**Comment by rsareth** [comment]
I have made another test locally. After removing the `/login` for redirect_uri, I face the same issue. In the console, I added some console.log in the file OidcServiceWorker.js in the switch statement. For each log, I display the current case. Look at the screenshot.

![Screenshot 2023-02-20 at 18 49 00](https://user-images.githubusercontent.com/4334697/220173365-9be50f99-a461-4ff3-acf4-bebb5248c6e4.png)

**Comment by guillaume-chervet** [comment]
I did not configure anything on azure.
I know the lib is working with cognito but  I do not have idea why you have this behavior.
Did you try whitout service worker?

`
const oidcConfiguration: OidcConfiguration = {
    authority: `https://cognito-idp.${configJson.get("region")}.amazonaws.com/${configJson.get("userPoolId")}`,
    client_id: configJson.get("userPoolWebClientId"),
    redirect_uri: getRedirectUri(configJson),
    scope: "openid email",
    // service_worker_only: true,
    // service_worker_relative_url: '/OidcServiceWorker.js'
  };
`

You should also try the configuration bellow:
`
const getRedirectUri = (config: Map<string, any>): string => {
  return config.get('env') === "local" ? 'http://localhost:3000/login' : window.location.origin/login;
}
`

React-oidc will handle this route for you once it is in the configuration.

**Comment by rsareth** [comment]
With your answers, I think the issue is on Cloudfront configuration. I watched this video: https://www.youtube.com/watch?v=Qo9ORPiRVVs I'm trying but it takes time to update the cloudfront distribution. I keep you posted in here.

**Comment by rsareth** [comment]
It was clearly a misconfiguration on Cloudfront. The solution in the video was right.

**Comment by rsareth** [comment]
Thank you for your @guillaumechervetaxa
