### ISSUE TITLE
OIDC service worker breaks cross-origin preflight check when using fetch

### ISSUE THREAD

**Issue by GNUGradyn** [AxaGuilDEv/react-oidc#965]
### Issue and Steps to Reproduce

Hello. I have written a React app that uses react-oidc for authentication. I am attempting to use `fetch` to access an API resource like so
```javascript
export function GetJournalSummary() {
    return fetch('http://localhost:5085/journal')
        .then(response => response.json())
        .then(data => {return data});
}
```
The current origin is `localhost:3000`, but using curl to simulate the preflight check we can verify Access-Control-Allow-Origin allows this
```shell
$ curl -H "Access-Control-Request-Method: GET" -H "Origin: http://localhost:3000" --head http://localhost:5085/journal
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 405 Method Not Allowed
Date: Tue, 21 Feb 2023 16:13:23 GMT
Server: Kestrel
Access-Control-Allow-Origin: *
Allow: GET
```
However, this does not appear to work yielding the following error
```
Access to fetch at 'http://localhost:5085/journal' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.
Uncaught (in promise) TypeError: Failed to fetch
    at handleFetch (OidcServiceWorker.js:293:43)
handleFetch @ OidcServiceWorker.js:293

```
Sounds to me like the service worker is trying to inject the auth token into the preflight check. I am not sure why you would ever want to do this.

### Versions
NodeJS: v18.13.0
├── @axa-fr/react-oidc@6.14.7
├── @testing-library/jest-dom@5.16.5
├── @testing-library/react@13.4.0
├── @testing-library/user-event@13.5.0
├── react-dom@18.2.0
├── react-scripts@5.0.1
├── react@18.2.0
└── web-vitals@2.1.4

### Screenshots
![image](https://user-images.githubusercontent.com/20762604/220401418-9a2cd0a3-1cd4-4057-88e5-41560f3c9936.png)

#### Expected
Preflight check succeeds, token is injected into fetch

#### Actual
Preflight check fails
### Additional Details

- Installed packages:
├── @axa-fr/react-oidc@6.14.7
├── @testing-library/jest-dom@5.16.5
├── @testing-library/react@13.4.0
├── @testing-library/user-event@13.5.0
├── react-dom@18.2.0
├── react-scripts@5.0.1
├── react@18.2.0
└── web-vitals@2.1.4

**Comment by guillaume-chervet** [comment]
Hi @GNUGradyn thank you for your issue.
The curl you give fail and return http 405.
You .NET server look like it may expect another verb like POST or DELETE.

So the result you get with service worker is normal. The http request from javascript with GET verb is not allowed by cors.

**Comment by GNUGradyn** [comment]
My bad. You are correct. I updated the .NET server to allow any verb and it works now. Thank you
