### ISSUE TITLE
Authorization headers not being set when request mode is navigate

### ISSUE THREAD

**Issue by mariaisid** [AxaGuilDEv/react-oidc#982]
### Issue and Steps to Reproduce

When trying to set the authorization headers in the service worker if the request mode is set as  'navigate' it produces an error and does not create the new request with the headers.

error: Uncaught (in promise) TypeError: Failed to construct 'Request': Cannot construct a Request with a RequestInit whose mode member is set as 'navigate'.

### Versions
6.15.2

### Screenshots

![image](https://user-images.githubusercontent.com/58230956/223151152-f7d8d97c-d36b-485a-b3d2-851484025789.png)

#### Expected

Set authorization headers in every request mode.

#### Actual

When request mode is 'navigate' it does not set authorization headers.

### Additional Details

Changing the original request mode before creating the new request worked for me, can this be implemented in any way in the service worker for future versions?

```
// OicdServiceWorker

handleFetch = async (event) => {
   ...
  originalRequest.mode = originalRequest.mode === "navigate" ? "cors" : originalRequest.mode;
  const newRequest = new Request(originalRequest, {
  ...
}
```

- Installed packages:

**Comment by guillaume-chervet** [comment]
hi @mariaisid ,

Thank you for your issue.

I think we have already a configuration property for that, that will resolve your need : 
    service_worker_convert_all_requests_to_cors: PropTypes.boolean,

Checkout the readme :
https://github.com/AxaGuilDEv/react-oidc/blob/master/packages/react/README.md#examples
