### ISSUE TITLE
[Question] Trusted domains in development environment/production

### ISSUE THREAD

**Issue by Thodor12** [AxaGuilDEv/react-oidc#987]
The trusted domains contains a list of authorized endpoints, however these tend to not match in development/production, in development you are likely targeting something in localhost whilst on production you want to refer to an actual domain.

For example:
```
const trustedDomains = {
    default: ["http://localhost:7068"],
    production: ["https://mypublicurl.com"]
};
```

What is the intended way to swap these out, short of providing multiple formats like shown in the example?
I'd prefer not to have to expose this development-like information in a production app.

**Comment by guillaume-chervet** [comment]
Hi @Thodor12 , thank you for your issue.
We use azure DevOps Release and we replace some variables during deployment.
We can set up different variable for different environment.

Example file we use : https://github.com/AxaGuilDEv/ecotag/blob/master/src/Ecotag/ClientApp/public/OidcTrustedDomains.production.js

For the public demo i hard coded file I just rename it at deployment time: https://github.com/AxaGuilDEv/ecotag/blob/master/src/Ecotag/ClientApp/public/

**Comment by Thodor12** [comment]
Alright, clear, I figured it would boil down to something like that but now I know for sure. Thanks.
