### ISSUE TITLE
Magiclink redirects showing Error UI component 

### ISSUE THREAD

**Issue by abhilashlr7** [AxaGuilDEv/react-oidc#988]
From this method:
https://github.com/AxaGuilDEv/react-oidc/blob/master/packages/react/src/oidc/vanilla/initSession.ts#L50-L56

it is clear that the method expects the dataString to be not null or undefined. We use Keycloak magiclink feature and the link generated redirects the user to the app url with session_state and code as query params. But what really happens is, in this method when the `JSON.parse(dataString)` line of code is executed, the config isn't available in localstorage/sessionstorage. Therefore this throws an exception and therefore the error component is loaded. If I debug step by step, the auth is actually successful, it does show the success message on auth and before it could take the user to the actual url, it renders the error component. 

How do we fix this?

**Comment by guillaume-chervet** [comment]
hi @abhilashlr thank you very much again for your issue.
It is a cool use case.

I think it is a litle bit more intricate. I think I need to read more information about that functionality on Keycloak.

react-oidc and vanila-oidc require an applicationPath after a callback like in the line.

https://github.com/AxaGuilDEv/react-oidc/blob/a3ae43e4f5dc530e6c5cec64d314cf91724e9bb1/packages/react/src/oidc/vanilla/login.ts#L167

with OIDC connect with PCKE the code verifier must be generate by the client like in 
https://github.com/AxaGuilDEv/react-oidc/blob/a3ae43e4f5dc530e6c5cec64d314cf91724e9bb1/packages/react/src/oidc/vanilla/requests.ts#L142
and in 
https://github.com/AxaGuilDEv/react-oidc/blob/a3ae43e4f5dc530e6c5cec64d314cf91724e9bb1/packages/react/src/oidc/vanilla/requests.ts#L122
I have to understand how magic link work.

**Comment by guillaume-chervet** [comment]
Hi @abhilashlr do you have a sample of the link generated ?

Magic link is interresting.

https://workos.com/blog/a-guide-to-magic-links

**Comment by abhilashlr7** [comment]
Unfortunately we do not have a public hosted app using keycloak that i can share. What we do is, we use https://github.com/p2-inc/keycloak-magic-link and run docker service of keycloak to setup email based magic link. 
So what it does is like it generates a token and sends to keycloak service. From there, it basically redirects to the app.

**Comment by abhilashlr7** [comment]
Also, from what I understand how this particular magic-link works, the generated token is appended to a keycloak service url (`http://localhost:8080/realms/<id>/login-actions/action-token` with client id as well. That jwt token contains the right redirect url (to the right app callback url) embedded in it. 

Now when the user clicks on this link in the email (keycloak link), it then figures out the `session_state` and the `code` value and sets the `authentication/callback` url of the actual application along with these values as query params like:

`http://localhost:3000/authentication/callback?session_state=<value>&code=<value>`.

Now when this happens, the lines of code inside `getLoginParams` fails to parse the `dataString` which apparently is because, this flow was completely outside of the regular login auth flow. Hence `storage[`oidc.login.${configurationName}`]` is undefined. Due to this, the parsing fails, but the app actually has authenticated. The tokens that were set are all valid. Also, post authentication, there is a react-oidc flow that takes the user to the root url of the app, that transition also happens, but the UI remains in the error state.

And how do I confirm that?
Just refresh the page `http://localhost:3000` that the authentication mechanism redirected and the app will continue as thought it logged the user in, as a regular flow.

Let me know if I wasn't clear in this comment, happy to post more thoughts or debugging stuff.

**Comment by guillaume-chervet** [comment]
Hi @abhilashlr,

Thank you very much for your response.

Do you know what does look like the "code" ?
Is it the code to send to retrieves all the tokens ?
It looks like a OIDC Code Flow Grant whithout PCKE.

Do you have a mode whithout any code in the callback url ?

You may callback on your custom route

/my-custom-callback
then on your custom component you can trigger a siglentlogin (if you are on the same domain than your oidc server) or a complete login flow.
Because you may already connected to you OIDC server with a cookie. I think it may work in a securest way.

**Comment by abhilashlr7** [comment]
I dont know if this is the right fix, but in the AuthenticationCallbackError component, doing a silent login works!

**Comment by guillaume-chervet** [comment]
hi @abhilashlr7 ,

This is perfect, so you just need to configure a callback to a route of your own and trigger silent login from it.
You do not need to use react OIDC callback.

**Comment by abhilashlr7** [comment]
So @guillaume-chervet , in the `AuthenticatingErrorComponent`, doing this is what makes it work, is this what you also propose?

```tsx
  const { login } = useOidc();

  useEffect(() => {
    (async () => {
      try {
        await login(window.location.href); // Doing `await login(window.location.href, {}, true);` actually breaks and shows the same error as [mentioned in the first comment](https://github.com/AxaGuilDEv/react-oidc/issues/988#issue-1617041343).
      } catch (error) {
        console.log(error)
      }
    })();
  }, [login, router]);
```

**Comment by guillaume-chervet** [comment]
Yes, but do it in a callback from manages you own route not in ErrorComponent.

**Comment by abhilashlr7** [comment]
Sounds good, that works now.
